version: "3.9"
services:
  # The Unleash server waits for the migrations to be applied by waiting on the 
  # migrations container to be healthy.
  unleash:
    image: unleashorg/unleash-server:latest # this is the latest stable release
    ports:
      - "4242:4242"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:4242/health || exit 1
      interval: 1s
      timeout: 1m
      retries: 5
      start_period: 15s

  db:
    ports:
      - "5432:5432"
    expose:
      - "5432"
    image: postgres:16
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "--username=postgres",
          "--host=127.0.0.1",
          "--port=5432",
        ]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s
