limitPerRun: 30
daysUntilStale: 30
daysUntilClose: 7

exemptLabels:
  - pinned
  - security
  - "[Status] Maybe Later"

exemptAssignees: true

staleLabel: wontfix

pulls:
  markComment: >
    This pull request has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.
issues:
  markComment: >
    This issue has been automatically marked as stale because it has not had
    recent activity. It will be closed if no further activity occurs. Thank you
    for your contributions.