import type { ChangeRequestItem } from './useChangeRequests';

// Mock data with varied projects and change requests (expanded to 35 items for pagination testing)
export const mockChangeRequests: ChangeRequestItem[] = [
    {
        id: 101,
        title: 'Activate harpoons',
        project: 'payment-service',
        projectName: 'Payment Service',
        features: ['securePaymentFlow'],
        segments: [],
        createdBy: { id: 1, username: 'alice', imageUrl: null },
        createdAt: '2024-01-10T10:22:00Z',
        environment: 'Production',
        state: 'In review',
    },
    {
        id: 102,
        title: 'change request #102',
        project: 'user-management',
        projectName: 'User Management',
        features: ['enhancedValidation'],
        segments: [],
        createdBy: { id: 2, username: 'bob', imageUrl: null },
        createdAt: '2024-01-10T08:15:00Z',
        environment: 'Production',
        state: 'Approved',
    },
    {
        id: 103,
        title: 'Enable new checkout flow',
        project: 'e-commerce-platform',
        projectName: 'E-commerce Platform',
        features: ['newCheckoutUX', 'paymentOptionsV2'],
        segments: [],
        createdBy: { id: 3, username: 'carol', imageUrl: null },
        createdAt: '2024-01-10T12:30:00Z',
        environment: 'Testing',
        state: 'In review',
    },
    {
        id: 104,
        title: 'Update user permissions',
        project: 'user-management',
        projectName: 'User Management',
        features: ['roleBasedAccess', 'permissionMatrix', 'adminDashboard'],
        segments: [],
        createdBy: { id: 4, username: 'david', imageUrl: null },
        createdAt: '2024-01-09T16:45:00Z',
        environment: 'Sandbox',
        state: 'In review',
    },
    {
        id: 105,
        title: 'Deploy feature rollback',
        project: 'analytics-platform',
        projectName: 'Analytics Platform',
        features: ['performanceTracking', 'realTimeAnalytics', 'customDashboards', 'dataExport'],
        segments: [],
        createdBy: { id: 5, username: 'eve', imageUrl: null },
        createdAt: '2024-01-09T14:20:00Z',
        environment: 'Sandbox',
        state: 'Scheduled',
        schedule: {
            scheduledAt: '2024-01-12T09:46:51+05:30',
            status: 'Pending',
        },
    },
    {
        id: 106,
        title: 'change request #106',
        project: 'notification-service',
        projectName: 'Notification Service',
        features: ['emailTemplates'],
        segments: [],
        createdBy: { id: 6, username: 'frank', imageUrl: null },
        createdAt: '2024-01-08T11:00:00Z',
        environment: 'Testing',
        state: 'Approved',
    },
    {
        id: 107,
        title: 'Optimize database queries',
        project: 'data-warehouse',
        projectName: 'Data Warehouse',
        features: ['queryOptimization'],
        segments: [],
        createdBy: { id: 7, username: 'grace', imageUrl: null },
        createdAt: '2024-01-08T09:30:00Z',
        environment: 'Testing',
        state: 'Approved',
    },
    {
        id: 108,
        title: 'change request #108',
        project: 'mobile-app',
        projectName: 'Mobile App',
        features: ['pushNotifications'],
        segments: [],
        createdBy: { id: 8, username: 'henry', imageUrl: null },
        createdAt: '2024-01-07T15:20:00Z',
        environment: 'Production',
        state: 'Approved',
    },
    {
        id: 109,
        title: 'Archive legacy features',
        project: 'payment-service',
        projectName: 'Payment Service',
        features: ['legacyPaymentGateway'],
        segments: [],
        createdBy: { id: 1, username: 'alice', imageUrl: null },
        createdAt: '2024-01-07T13:10:00Z',
        environment: 'Production',
        state: 'Scheduled',
        schedule: {
            scheduledAt: '2024-01-12T09:46:51+05:30',
            status: 'Failed',
            reason: 'Mr Freeze',
        },
    },
    // Additional 26 items to reach 35 total (ensuring >25 for pagination)
    {
        id: 110,
        title: 'Enable dark mode',
        project: 'design-system',
        projectName: 'Design System',
        features: ['darkTheme', 'themeToggle'],
        segments: [],
        createdBy: { id: 9, username: 'isabella', imageUrl: null },
        createdAt: '2024-01-06T14:30:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 111,
        title: 'API rate limiting',
        project: 'api-gateway',
        projectName: 'API Gateway',
        features: ['rateLimiting', 'throttling'],
        segments: ['premium-users'],
        createdBy: { id: 10, username: 'jack', imageUrl: null },
        createdAt: '2024-01-06T10:15:00Z',
        environment: 'Production',
        state: 'Approved',
    },
    {
        id: 112,
        title: 'Social media login',
        project: 'auth-service',
        projectName: 'Authentication Service',
        features: ['googleLogin', 'facebookLogin', 'twitterLogin'],
        segments: [],
        createdBy: { id: 11, username: 'karen', imageUrl: null },
        createdAt: '2024-01-05T16:45:00Z',
        environment: 'Testing',
        state: 'In review',
    },
    {
        id: 113,
        title: 'Real-time notifications',
        project: 'notification-service',
        projectName: 'Notification Service',
        features: ['websocketNotifications', 'notificationCenter'],
        segments: [],
        createdBy: { id: 12, username: 'liam', imageUrl: null },
        createdAt: '2024-01-05T12:00:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 114,
        title: 'Multi-currency support',
        project: 'payment-service',
        projectName: 'Payment Service',
        features: ['currencyConversion', 'multiCurrency'],
        segments: ['international-users'],
        createdBy: { id: 2, username: 'bob', imageUrl: null },
        createdAt: '2024-01-04T09:30:00Z',
        environment: 'Sandbox',
        state: 'Rejected',
    },
    {
        id: 115,
        title: 'Advanced search filters',
        project: 'e-commerce-platform',
        projectName: 'E-commerce Platform',
        features: ['advancedSearch', 'filterOptions', 'searchSuggestions'],
        segments: [],
        createdBy: { id: 13, username: 'mia', imageUrl: null },
        createdAt: '2024-01-03T14:15:00Z',
        environment: 'Testing',
        state: 'Applied',
    },
    {
        id: 116,
        title: 'Machine learning recommendations',
        project: 'recommendation-engine',
        projectName: 'Recommendation Engine',
        features: ['mlRecommendations', 'userBehaviorTracking'],
        segments: ['active-users'],
        createdBy: { id: 14, username: 'noah', imageUrl: null },
        createdAt: '2024-01-02T11:20:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 117,
        title: 'Video streaming optimization',
        project: 'media-service',
        projectName: 'Media Service',
        features: ['videoOptimization', 'adaptiveBitrate'],
        segments: [],
        createdBy: { id: 15, username: 'olivia', imageUrl: null },
        createdAt: '2024-01-01T08:45:00Z',
        environment: 'Production',
        state: 'Scheduled',
        schedule: {
            scheduledAt: '2024-01-15T10:00:00+05:30',
            status: 'Pending',
        },
    },
    {
        id: 118,
        title: 'Inventory management system',
        project: 'inventory-service',
        projectName: 'Inventory Service',
        features: ['stockTracking', 'lowStockAlerts', 'automaticReordering'],
        segments: [],
        createdBy: { id: 16, username: 'peter', imageUrl: null },
        createdAt: '2023-12-31T15:30:00Z',
        environment: 'Testing',
        state: 'In review',
    },
    {
        id: 119,
        title: 'Customer support chatbot',
        project: 'customer-service',
        projectName: 'Customer Service',
        features: ['aiChatbot', 'ticketRouting'],
        segments: ['support-tier-1'],
        createdBy: { id: 17, username: 'quinn', imageUrl: null },
        createdAt: '2023-12-30T13:15:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 120,
        title: 'Geolocation services',
        project: 'location-service',
        projectName: 'Location Service',
        features: ['geoLocation', 'addressAutocomplete'],
        segments: ['mobile-users'],
        createdBy: { id: 18, username: 'rachel', imageUrl: null },
        createdAt: '2023-12-29T10:00:00Z',
        environment: 'Sandbox',
        state: 'Cancelled',
    },
    {
        id: 121,
        title: 'Blockchain integration',
        project: 'crypto-service',
        projectName: 'Crypto Service',
        features: ['blockchainIntegration', 'cryptoWallet'],
        segments: ['crypto-users'],
        createdBy: { id: 19, username: 'sam', imageUrl: null },
        createdAt: '2023-12-28T16:20:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 122,
        title: 'Voice recognition',
        project: 'ai-service',
        projectName: 'AI Service',
        features: ['voiceRecognition', 'speechToText'],
        segments: [],
        createdBy: { id: 20, username: 'taylor', imageUrl: null },
        createdAt: '2023-12-27T12:45:00Z',
        environment: 'Testing',
        state: 'Approved',
    },
    {
        id: 123,
        title: 'Performance monitoring',
        project: 'monitoring-service',
        projectName: 'Monitoring Service',
        features: ['performanceMetrics', 'alerting', 'dashboards'],
        segments: [],
        createdBy: { id: 21, username: 'uma', imageUrl: null },
        createdAt: '2023-12-26T09:10:00Z',
        environment: 'Production',
        state: 'Applied',
    },
    {
        id: 124,
        title: 'Content moderation',
        project: 'content-service',
        projectName: 'Content Service',
        features: ['autoModeration', 'contentFiltering'],
        segments: ['user-generated-content'],
        createdBy: { id: 22, username: 'victor', imageUrl: null },
        createdAt: '2023-12-25T14:30:00Z',
        environment: 'Testing',
        state: 'In review',
    },
    {
        id: 125,
        title: 'Email marketing automation',
        project: 'marketing-service',
        projectName: 'Marketing Service',
        features: ['emailCampaigns', 'marketingAutomation'],
        segments: ['marketing-subscribers'],
        createdBy: { id: 23, username: 'wendy', imageUrl: null },
        createdAt: '2023-12-24T11:20:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 126,
        title: 'Data backup and recovery',
        project: 'backup-service',
        projectName: 'Backup Service',
        features: ['automaticBackup', 'dataRecovery'],
        segments: [],
        createdBy: { id: 24, username: 'xavier', imageUrl: null },
        createdAt: '2023-12-23T08:15:00Z',
        environment: 'Production',
        state: 'Scheduled',
        schedule: {
            scheduledAt: '2024-01-20T02:00:00+05:30',
            status: 'Pending',
        },
    },
    {
        id: 127,
        title: 'Load balancing optimization',
        project: 'infrastructure',
        projectName: 'Infrastructure',
        features: ['loadBalancer', 'trafficDistribution'],
        segments: [],
        createdBy: { id: 25, username: 'yara', imageUrl: null },
        createdAt: '2023-12-22T15:45:00Z',
        environment: 'Production',
        state: 'Approved',
    },
    {
        id: 128,
        title: 'Calendar integration',
        project: 'calendar-service',
        projectName: 'Calendar Service',
        features: ['calendarSync', 'eventReminders'],
        segments: [],
        createdBy: { id: 26, username: 'zoe', imageUrl: null },
        createdAt: '2023-12-21T13:30:00Z',
        environment: 'Testing',
        state: 'In review',
    },
    {
        id: 129,
        title: 'Document collaboration',
        project: 'document-service',
        projectName: 'Document Service',
        features: ['realTimeEditing', 'documentSharing'],
        segments: ['business-users'],
        createdBy: { id: 3, username: 'carol', imageUrl: null },
        createdAt: '2023-12-20T10:15:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 130,
        title: 'Mobile app security',
        project: 'mobile-app',
        projectName: 'Mobile App',
        features: ['biometricAuth', 'appSecurityScanning'],
        segments: ['mobile-users'],
        createdBy: { id: 27, username: 'adam', imageUrl: null },
        createdAt: '2023-12-19T16:00:00Z',
        environment: 'Testing',
        state: 'Approved',
    },
    {
        id: 131,
        title: 'Analytics dashboard v2',
        project: 'analytics-platform',
        projectName: 'Analytics Platform',
        features: ['advancedDashboard', 'customCharts', 'dataVisualization'],
        segments: ['analytics-users'],
        createdBy: { id: 5, username: 'eve', imageUrl: null },
        createdAt: '2023-12-18T12:20:00Z',
        environment: 'Development',
        state: 'In review',
    },
    {
        id: 132,
        title: 'Microservices migration',
        project: 'architecture',
        projectName: 'Architecture',
        features: ['microservicesArchitecture', 'serviceDecomposition'],
        segments: [],
        createdBy: { id: 28, username: 'blake', imageUrl: null },
        createdAt: '2023-12-17T09:45:00Z',
        environment: 'Development',
        state: 'Draft',
    },
    {
        id: 133,
        title: 'API versioning strategy',
        project: 'api-gateway',
        projectName: 'API Gateway',
        features: ['apiVersioning', 'backwardCompatibility'],
        segments: ['api-consumers'],
        createdBy: { id: 10, username: 'jack', imageUrl: null },
        createdAt: '2023-12-16T14:10:00Z',
        environment: 'Testing',
        state: 'Applied',
    },
    {
        id: 134,
        title: 'User onboarding flow',
        project: 'user-management',
        projectName: 'User Management',
        features: ['onboardingWizard', 'userTutorials'],
        segments: ['new-users'],
        createdBy: { id: 29, username: 'claire', imageUrl: null },
        createdAt: '2023-12-15T11:35:00Z',
        environment: 'Production',
        state: 'Scheduled',
        schedule: {
            scheduledAt: '2024-01-25T09:00:00+05:30',
            status: 'Suspended',
            reason: 'Resource constraints',
        },
    },
    {
        id: 135,
        title: 'Feature flag management',
        project: 'feature-management',
        projectName: 'Feature Management',
        features: ['featureFlags', 'gradualRollout'],
        segments: ['beta-testers'],
        createdBy: { id: 30, username: 'derek', imageUrl: null },
        createdAt: '2023-12-14T08:25:00Z',
        environment: 'Production',
        state: 'Approved',
    },
];