/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */

export type _ExportFormat = typeof _ExportFormat[keyof typeof _ExportFormat];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const _ExportFormat = {
    json: 'json',
    yaml: 'yaml',
} as const;
