/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Match the source of the signal
 */
export type ActionsSchemaMatchSource =
    (typeof ActionsSchemaMatchSource)[keyof typeof ActionsSchemaMatchSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionsSchemaMatchSource = {
    'signal-endpoint': 'signal-endpoint',
} as const;
