/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ActionSchema } from './actionSchema';
import type { ActionsSchemaMatch } from './actionsSchemaMatch';

/**
 * A response model with an identifiable action set.
 */
export interface ActionsSchema {
    /** The list of actions to execute in sequential order when the action set is triggered. */
    actions: ActionSchema[];
    /**
     * The id of the service account that will execute the action
     * @minimum 1
     */
    actorId: number;
    /** The date and time of when the action set was created. */
    createdAt: string;
    /** The ID of the user that created this action set. */
    createdByUserId: number;
    /**
     * The description of the action set
     * @nullable
     */
    description?: string | null;
    /** Whether this action set is enabled or not */
    enabled?: boolean;
    /**
     * The ID of the action set.
     * @minimum 1
     */
    id: number;
    /** Defines a matching rule for the signal that will trigger the action set */
    match: ActionsSchemaMatch;
    /** The name of the action set */
    name: string;
    /** The project that this action set belongs to. */
    project: string;
}
