/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Match the payload of the signal
 */
export type ActionSetEventSchemaActionSetMatchPayload = {
    [key: string]: unknown;
};
