/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of the parameter.
 */
export type ActionDefinitionParameterSchemaName =
    (typeof ActionDefinitionParameterSchemaName)[keyof typeof ActionDefinitionParameterSchemaName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionDefinitionParameterSchemaName = {
    project: 'project',
    environment: 'environment',
    featureName: 'featureName',
    tag: 'tag',
} as const;
