/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Match the source of the signal
 */
export type ActionSetEventSchemaActionSetMatchSource =
    (typeof ActionSetEventSchemaActionSetMatchSource)[keyof typeof ActionSetEventSchemaActionSetMatchSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActionSetEventSchemaActionSetMatchSource = {
    'signal-endpoint': 'signal-endpoint',
} as const;
