/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Parameters for the addon provider. This object has different required and optional properties depending on the provider you choose.
 */
export type AddonSchemaParameters = { [key: string]: unknown };
