/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */
import type { TagTypeSchema } from './tagTypeSchema';
import type { AddonParameterSchema } from './addonParameterSchema';

export interface AddonTypeSchema {
    name: string;
    displayName: string;
    documentationUrl: string;
    description: string;
    tagTypes?: TagTypeSchema[];
    parameters?: AddonParameterSchema[];
    events?: string[];
}
