/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */
import type { AddonSchema } from './addonSchema';
import type { AddonTypeSchema } from './addonTypeSchema';

export interface AddonsSchema {
    addons: AddonSchema[];
    providers: AddonTypeSchema[];
}
