/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { AddonSchema } from './addonSchema';
import type { AddonTypeSchema } from './addonTypeSchema';

/**
 * An object containing two things:
1. A list of all [addons](https://docs.getunleash.io/reference/addons) defined on this Unleash instance
2. A list of all addon providers defined on this instance
 */
export interface AddonsSchema {
    /** All the addons that exist on this instance of Unleash. */
    addons: AddonSchema[];
    /** A list of  all available addon providers, along with their parameters and descriptions. */
    providers: AddonTypeSchema[];
}
