/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.55
 */
import type { AddonSchemaParameters } from './addonSchemaParameters';

export interface AddonSchema {
    id?: number;
    createdAt?: string | null;
    provider: string;
    description?: string;
    enabled: boolean;
    parameters: AddonSchemaParameters;
    events: string[];
    projects?: string[];
    environments?: string[];
}
