/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { AddonSchema } from './addonSchema';
import type { AddonTypeSchema } from './addonTypeSchema';

export interface AddonsSchema {
    addons: AddonSchema[];
    providers: AddonTypeSchema[];
}
