/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */

export interface AdminPermissionSchema {
  id: number;
  name: string;
  displayName: string;
  type: string;
  environment?: string;
}
