/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { AdminPermissionSchema } from './adminPermissionSchema';
import type { AdminPermissionsSchemaPermissionsEnvironmentsItem } from './adminPermissionsSchemaPermissionsEnvironmentsItem';

export type AdminPermissionsSchemaPermissions = {
    root?: AdminPermissionSchema[];
    project: AdminPermissionSchema[];
    environments: AdminPermissionsSchemaPermissionsEnvironmentsItem[];
};
