/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ConstraintSchema } from './constraintSchema';

export interface AdminSegmentSchema {
    id: number;
    name: string;
    description?: string | null;
    constraints: ConstraintSchema[];
    createdBy?: string;
    createdAt: string;
}
