/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */
import type { AdminPermissionsSchemaPermissions } from './adminPermissionsSchemaPermissions';

export interface AdminPermissionsSchema {
    permissions: AdminPermissionsSchemaPermissions;
    version: number;
}
