/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export interface AdminFeaturesQuerySchema {
    /** Used to filter by tags. For each entry, a TAGTYPE:TAGVALUE is expected */
    tag?: string[];
    /** A case-insensitive prefix filter for the names of feature toggles */
    namePrefix?: string;
}
