/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The cumulative results of all the feature's strategies. Can be `true`,
                                  `false`, or `unknown`.
                                  This property will only be `unknown`
                                  if one or more of the strategies can't be fully evaluated and the rest of the strategies
                                  all resolve to `false`.
 */
export type AdvancedPlaygroundEnvironmentFeatureSchemaStrategiesResult =
    | boolean
    | 'unknown';
