/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Data about an project that have been used by applications.
 */
export interface ApplicationUsageSchema {
    /** Name of the project */
    project: string;
    /** Which environments have been accessed in this project. */
    environments: string[];
}
