/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ArchivedFeatureSchemaEnvironmentsItem = {
    /** The name of the environment */
    name?: string;
    /**
     * The date when metrics where last collected for the feature environment
     * @nullable
     */
    lastSeenAt?: string | null;
    /** `true` if the feature is enabled for the environment, otherwise `false`. */
    enabled?: boolean;
};
