/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ArchivedFeatureSchemaEnvironmentsItem } from './archivedFeatureSchemaEnvironmentsItem';

/**
 * An archived project feature flag definition
 */
export interface ArchivedFeatureSchema {
    /** The date the feature was archived */
    archivedAt?: string;
    /** The date the feature was created */
    createdAt?: string;
    /**
     * Detailed description of the feature
     * @nullable
     */
    description?: string | null;
    /**
     * The list of environments where the feature can be used
     * @deprecated
     */
    environments?: ArchivedFeatureSchemaEnvironmentsItem[];
    /** `true` if the impression data collection is enabled for the feature, otherwise `false`. */
    impressionData?: boolean;
    /**
     * The date when metrics where last collected for the feature. This field was deprecated in v5, use the one in featureEnvironmentSchema
     * @deprecated
     * @nullable
     */
    lastSeenAt?: string | null;
    /** Unique feature name */
    name: string;
    /** Name of the project the feature belongs to */
    project: string;
    /** `true` if the feature is stale based on the age and feature type, otherwise `false`. */
    stale?: boolean;
    /** Type of the flag e.g. experiment, kill-switch, release, operational, permission */
    type?: string;
}
