/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A list of feature flag names for batch operations
 */
export interface BatchFeaturesSchema {
    /** List of feature flag names */
    features: string[];
}
