/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { BulkRegistrationSchema } from './bulkRegistrationSchema';
import type { ClientMetricsEnvSchema } from './clientMetricsEnvSchema';

/**
 * A batch of metrics accumulated by Edge (or other compatible applications). Includes both application registrations as well usage metrics from clients
 */
export interface BulkMetricsSchema {
    /** A list of applications registered by an Unleash SDK */
    applications: BulkRegistrationSchema[];
    /** a list of client usage metrics registered by downstream providers. (Typically Unleash Edge) */
    metrics: ClientMetricsEnvSchema[];
}
