/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestsSchemaItemOneOf } from './changeRequestsSchemaItemOneOf.js';
import type { ChangeRequestsSchemaItemOneOfFive } from './changeRequestsSchemaItemOneOfFive.js';

/**
 * A simplified change request overview
 */
export type ChangeRequestsSchemaItem =
    | ChangeRequestsSchemaItemOneOf
    | ChangeRequestsSchemaItemOneOfFive;
