/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfFourzeroAction } from './changeRequestCreateSchemaOneOfFourzeroAction.js';
import type { ChangeRequestCreateSchemaOneOfFourzeroPayload } from './changeRequestCreateSchemaOneOfFourzeroPayload.js';

/**
 * Delete milestone progression.
 */
export type ChangeRequestCreateSchemaOneOfFourzero = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfFourzeroAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfFourzeroPayload;
};
