/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfOnefiveAction } from './changeRequestCreateSchemaOneOfOnefiveAction';
import type { ChangeRequestCreateSchemaOneOfOnefivePayload } from './changeRequestCreateSchemaOneOfOnefivePayload';

/**
 * Delete a strategy from this feature.
 */
export type ChangeRequestCreateSchemaOneOfOnefive = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfOnefiveAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfOnefivePayload;
};
