/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * User who created the change request.
 */
export type ChangeRequestSearchItemSchemaOneOfFourCreatedBy = {
    /** Unique identifier of the user. */
    id: number;
    /** Avatar image URL for the user. */
    imageUrl?: string;
    /** Username of the user. */
    username?: string;
};
