/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfTwosevenAction } from './changeRequestCreateSchemaOneOfTwosevenAction';

/**
 * Remove a parent feature dependency or all dependencies if no payload.
 */
export type ChangeRequestCreateSchemaOneOfTwoseven = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfTwosevenAction;
    /** The name of the feature that this change applies to. */
    feature: string;
};
