/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { TransitionConditionSchema } from './transitionConditionSchema.js';

export type ChangeRequestCreateFeatureSchemaOneOfThreezeroPayload = {
    /** The ID of the source milestone */
    sourceMilestone: string;
    /** The ID of the target milestone */
    targetMilestone: string;
    /** The condition configuration for the transition */
    transitionCondition: TransitionConditionSchema;
};
