/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfFournineAction =
    (typeof ChangeRequestCreateSchemaOneOfFournineAction)[keyof typeof ChangeRequestCreateSchemaOneOfFournineAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateSchemaOneOfFournineAction = {
    deleteReleasePlanSafeguard: 'deleteReleasePlanSafeguard',
} as const;
