/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfTwonineAction } from './changeRequestCreateSchemaOneOfTwonineAction';
import type { ReleasePlanTemplateIdSchema } from './releasePlanTemplateIdSchema';

/**
 * Add a release plan to this feature environment.
 */
export type ChangeRequestCreateSchemaOneOfTwonine = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfTwonineAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ReleasePlanTemplateIdSchema;
};
