/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFivefiveAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfFivefiveAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfFivefiveAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfFivefiveAction = {
    deleteFeatureEnvSafeguard: 'deleteFeatureEnvSafeguard',
} as const;
