/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfThreeoneAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfThreeoneAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfThreeoneAction];

export const ChangeRequestOneOrManyCreateSchemaOneOfThreeoneAction = {
    startMilestone: 'startMilestone',
} as const;
