/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestSchemaOneOf } from './changeRequestSchemaOneOf';
import type { ChangeRequestSchemaOneOfFive } from './changeRequestSchemaOneOfFive';

/**
 * A [change request](https://docs.getunleash.io/concepts/change-requests)
 */
export type ChangeRequestSchema =
    | ChangeRequestSchemaOneOf
    | ChangeRequestSchemaOneOfFive;
