/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * One or more strategy IDs.
 */
export type ChangeRequestScheduledQueryParamsSchemaStrategyId =
    | string[]
    | string;
