/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfFoursixAction } from './changeRequestCreateSchemaOneOfFoursixAction.ts';
import type { ChangeRequestCreateSchemaOneOfFoursixPayload } from './changeRequestCreateSchemaOneOfFoursixPayload.ts';

/**
 * Create or update a safeguard for a release plan.
 */
export type ChangeRequestCreateSchemaOneOfFoursix = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfFoursixAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfFoursixPayload;
};
