/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SdkContextSchema } from './sdkContextSchema.js';

/**
 * Data for the playground API to evaluate flags with change request applied in preview mode
 */
export interface ChangeRequestPlaygroundRequestSchema {
    context: SdkContextSchema;
}
