/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfThreetwoAction } from './changeRequestOneOrManyCreateSchemaOneOfThreetwoAction';
import type { ChangeRequestOneOrManyCreateSchemaOneOfThreetwoPayload } from './changeRequestOneOrManyCreateSchemaOneOfThreetwoPayload';

/**
 * Remove a release plan from feature environment.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfThreetwo = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfThreetwoAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    /** The Id of the release plan to remove. */
    payload: ChangeRequestOneOrManyCreateSchemaOneOfThreetwoPayload;
};
