/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfThreeeightAction } from './changeRequestCreateSchemaOneOfThreeeightAction';
import type { ChangeRequestCreateSchemaOneOfThreeeightPayload } from './changeRequestCreateSchemaOneOfThreeeightPayload';

/**
 * Delete milestone progression.
 */
export type ChangeRequestCreateSchemaOneOfThreeeight = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfThreeeightAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfThreeeightPayload;
};
