/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfTwotwoAction } from './changeRequestCreateFeatureSchemaOneOfTwotwoAction';

/**
 * Remove a parent feature dependency or all dependencies if no payload.
 */
export type ChangeRequestCreateFeatureSchemaOneOfTwotwo = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfTwotwoAction;
    /** The name of the feature that this change applies to. */
    feature: string;
};
