/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFourthreeAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfFourthreeAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfFourthreeAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfFourthreeAction = {
    resumeMilestoneProgression: 'resumeMilestoneProgression',
} as const;
