/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfOneoneAction } from './changeRequestOneOrManyCreateSchemaOneOfOneoneAction.js';
import type { UpdateFeatureStrategySchema } from './updateFeatureStrategySchema.js';

/**
 * Update a strategy belonging to this feature.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfOneone = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfOneoneAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: UpdateFeatureStrategySchema;
};
