/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Change password as long as the token is a valid token
 */
export interface ChangePasswordSchema {
    /** The new password for the user */
    password: string;
    /** A reset token used to validate that the user is allowed to change the password. */
    token: string;
}
