/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Information about the user who posted the comment
 */
export type ChangeRequestCommentSchemaCreatedBy = {
    /**
     * The user's username.
     * @nullable
     */
    username?: string | null;
    /**
     * The URL where the user's image can be found.
     * @nullable
     */
    imageUrl?: string | null;
};
