/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestChangeSchemaScheduleConflictsChangeRequestsItem } from './changeRequestChangeSchemaScheduleConflictsChangeRequestsItem.js';

/**
 * Information about scheduled change requests that would casue conflicts with this change if applied.
 */
export type ChangeRequestChangeSchemaScheduleConflicts = {
    /** The list of scheduled change requests that would cause conflict with this change. */
    changeRequests: ChangeRequestChangeSchemaScheduleConflictsChangeRequestsItem[];
};
