/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOf } from './changeRequestCreateSchemaOneOf';
import type { ChangeRequestCreateSchemaOneOfThree } from './changeRequestCreateSchemaOneOfThree';
import type { ChangeRequestCreateSchemaOneOfSix } from './changeRequestCreateSchemaOneOfSix';
import type { ChangeRequestCreateSchemaOneOfNine } from './changeRequestCreateSchemaOneOfNine';
import type { ChangeRequestCreateSchemaOneOfOneone } from './changeRequestCreateSchemaOneOfOneone';
import type { ChangeRequestCreateSchemaOneOfOnethree } from './changeRequestCreateSchemaOneOfOnethree';
import type { ChangeRequestCreateSchemaOneOfOnesix } from './changeRequestCreateSchemaOneOfOnesix';
import type { ChangeRequestCreateSchemaOneOfOneeight } from './changeRequestCreateSchemaOneOfOneeight';
import type { ChangeRequestCreateSchemaOneOfTwoone } from './changeRequestCreateSchemaOneOfTwoone';
import type { ChangeRequestCreateSchemaOneOfTwothree } from './changeRequestCreateSchemaOneOfTwothree';
import type { ChangeRequestCreateSchemaOneOfTwofive } from './changeRequestCreateSchemaOneOfTwofive';

/**
 * Data used to create a [change request](https://docs.getunleash.io/reference/change-requests) for a single feature or segment change.
 */
export type ChangeRequestCreateSchema =
    | ChangeRequestCreateSchemaOneOf
    | ChangeRequestCreateSchemaOneOfThree
    | ChangeRequestCreateSchemaOneOfSix
    | ChangeRequestCreateSchemaOneOfNine
    | ChangeRequestCreateSchemaOneOfOneone
    | ChangeRequestCreateSchemaOneOfOnethree
    | ChangeRequestCreateSchemaOneOfOnesix
    | ChangeRequestCreateSchemaOneOfOneeight
    | ChangeRequestCreateSchemaOneOfTwoone
    | ChangeRequestCreateSchemaOneOfTwothree
    | ChangeRequestCreateSchemaOneOfTwofive;
