/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateFeatureSchemaOneOfOnethreeAction =
    (typeof ChangeRequestCreateFeatureSchemaOneOfOnethreeAction)[keyof typeof ChangeRequestCreateFeatureSchemaOneOfOnethreeAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateFeatureSchemaOneOfOnethreeAction = {
    patchVariant: 'patchVariant',
} as const;
