/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ChangeRequestOneOrManyCreateSchemaOneOfTwofivePayload = {
    /** The name of the feature we want to remove dependency on. */
    feature: string;
};
