/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestEventSchemaPayloadOneOf } from './changeRequestEventSchemaPayloadOneOf';

export type ChangeRequestEventSchemaPayload =
    | string
    | boolean
    | ChangeRequestEventSchemaPayloadOneOf
    | number;
