/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfThreefiveAction } from './changeRequestCreateSchemaOneOfThreefiveAction.js';
import type { CreateMilestoneProgressionSchema } from './createMilestoneProgressionSchema.js';

/**
 * Create milestone progression from one milestone to another.
 */
export type ChangeRequestCreateSchemaOneOfThreefive = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfThreefiveAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: CreateMilestoneProgressionSchema;
};
