/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfTwofourAction } from './changeRequestCreateFeatureSchemaOneOfTwofourAction.ts';
import type { ReleasePlanTemplateIdSchema } from './releasePlanTemplateIdSchema.ts';

/**
 * Add a release plan to this feature environment.
 */
export type ChangeRequestCreateFeatureSchemaOneOfTwofour = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfTwofourAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ReleasePlanTemplateIdSchema;
};
