/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Data used to update a [change request](https://docs.getunleash.io/concepts/change-requests)'s title.
 */
export interface ChangeRequestUpdateTitleSchema {
    /** The new title to use for this change request. */
    title: string;
}
