/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfThreefiveAction } from './changeRequestCreateFeatureSchemaOneOfThreefiveAction.js';
import type { ChangeRequestCreateFeatureSchemaOneOfThreefivePayload } from './changeRequestCreateFeatureSchemaOneOfThreefivePayload.js';

/**
 * Delete milestone progression.
 */
export type ChangeRequestCreateFeatureSchemaOneOfThreefive = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfThreefiveAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateFeatureSchemaOneOfThreefivePayload;
};
