/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ChangeRequestCreateSchemaOneOfFourthreePayload = {
    /** The release plan's unique identifier (ULID format) */
    planId: string;
};
