/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfOneoneAction } from './changeRequestCreateSchemaOneOfOneoneAction';
import type { ChangeRequestCreateSchemaOneOfOneonePayload } from './changeRequestCreateSchemaOneOfOneonePayload';

export type ChangeRequestCreateSchemaOneOfOneone = {
    action: ChangeRequestCreateSchemaOneOfOneoneAction;
    payload: ChangeRequestCreateSchemaOneOfOneonePayload;
};
