/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfOnesixAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfOnesixAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfOnesixAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfOnesixAction = {
    archiveFeature: 'archiveFeature',
} as const;
