/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfThreesevenAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfThreesevenAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfThreesevenAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfThreesevenAction = {
    updateMilestoneProgression: 'updateMilestoneProgression',
} as const;
