/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfFourtwoAction } from './changeRequestCreateFeatureSchemaOneOfFourtwoAction.js';
import type { ChangeRequestCreateFeatureSchemaOneOfFourtwoPayload } from './changeRequestCreateFeatureSchemaOneOfFourtwoPayload.js';

/**
 * Delete a safeguard from a release plan.
 */
export type ChangeRequestCreateFeatureSchemaOneOfFourtwo = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfFourtwoAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateFeatureSchemaOneOfFourtwoPayload;
};
