/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestsSchemaItem } from './changeRequestsSchemaItem.js';

/**
 * A list of change requests
 */
export type ChangeRequestsSchema = ChangeRequestsSchemaItem[];
