/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfFoursevenAction } from './changeRequestCreateSchemaOneOfFoursevenAction.js';
import type { ChangeRequestCreateSchemaOneOfFoursevenPayload } from './changeRequestCreateSchemaOneOfFoursevenPayload.js';

/**
 * Delete a safeguard from a release plan.
 */
export type ChangeRequestCreateSchemaOneOfFourseven = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfFoursevenAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfFoursevenPayload;
};
