/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfTwothreeAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfTwothreeAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfTwothreeAction];

export const ChangeRequestOneOrManyCreateSchemaOneOfTwothreeAction = {
    reorderStrategy: 'reorderStrategy',
} as const;
