/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The user who created this change.
 */
export type ChangeRequestChangeSchemaCreatedBy = {
    /** The URL where the user's image can be found. */
    imageUrl?: string | null;
    /** The user's username. */
    username?: string | null;
};
