/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfTwonineAction } from './changeRequestCreateFeatureSchemaOneOfTwonineAction';
import type { ChangeRequestCreateFeatureSchemaOneOfTwoninePayload } from './changeRequestCreateFeatureSchemaOneOfTwoninePayload';

/**
 * Remove a release plan from feature environment.
 */
export type ChangeRequestCreateFeatureSchemaOneOfTwonine = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfTwonineAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    /** The Id of the release plan to remove. */
    payload: ChangeRequestCreateFeatureSchemaOneOfTwoninePayload;
};
