/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestSegmentChangeSchemaPayloadOneOf } from './changeRequestSegmentChangeSchemaPayloadOneOf.js';
import type { SetStrategySortOrderSchema } from './setStrategySortOrderSchema.js';

/**
 * The data required to perform this action.
 */
export type ChangeRequestSegmentChangeSchemaPayload =
    | string
    | boolean
    | ChangeRequestSegmentChangeSchemaPayloadOneOf
    | number
    | SetStrategySortOrderSchema;
