/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFourfourAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfFourfourAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfFourfourAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfFourfourAction = {
    changeSafeguard: 'changeSafeguard',
} as const;
