/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfTwooneAction } from './changeRequestOneOrManyCreateSchemaOneOfTwooneAction.js';
import type { SetStrategySortOrderSchema } from './setStrategySortOrderSchema.js';

/**
 * Reorder strategies for this feature
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfTwoone = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfTwooneAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: SetStrategySortOrderSchema;
};
