/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfFoursixAction } from './changeRequestOneOrManyCreateSchemaOneOfFoursixAction';
import type { ChangeRequestOneOrManyCreateSchemaOneOfFoursixPayload } from './changeRequestOneOrManyCreateSchemaOneOfFoursixPayload';

/**
 * Create or update a safeguard for a release plan.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFoursix = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfFoursixAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestOneOrManyCreateSchemaOneOfFoursixPayload;
};
