/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A mapping of each state this change request has entered to the most recent time when it entered that state. If a change request has entered the same state multiple times, only the most recent timestamp will be included.
 */
export type ChangeRequestSchemaOneOfFiveStateTimestamps = {
    [key: string]: string;
};
