/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfNineAction =
    (typeof ChangeRequestCreateSchemaOneOfNineAction)[keyof typeof ChangeRequestCreateSchemaOneOfNineAction];

export const ChangeRequestCreateSchemaOneOfNineAction = {
    addStrategy: 'addStrategy',
} as const;
