/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfThreesixAction } from './changeRequestCreateFeatureSchemaOneOfThreesixAction.js';
import type { ChangeRequestCreateFeatureSchemaOneOfThreesixPayload } from './changeRequestCreateFeatureSchemaOneOfThreesixPayload.js';

/**
 * Create or update a safeguard for a release plan.
 */
export type ChangeRequestCreateFeatureSchemaOneOfThreesix = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfThreesixAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateFeatureSchemaOneOfThreesixPayload;
};
