/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ChangeRequestOneOrManyCreateSchemaOneOfOnethreePayload = {
    /** The ID of the strategy to update. */
    id: string;
};
