/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfThreeAction =
    (typeof ChangeRequestCreateSchemaOneOfThreeAction)[keyof typeof ChangeRequestCreateSchemaOneOfThreeAction];

export const ChangeRequestCreateSchemaOneOfThreeAction = {
    deleteSegment: 'deleteSegment',
} as const;
