/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfThreeoneAction =
    (typeof ChangeRequestCreateSchemaOneOfThreeoneAction)[keyof typeof ChangeRequestCreateSchemaOneOfThreeoneAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateSchemaOneOfThreeoneAction = {
    startMilestone: 'startMilestone',
} as const;
