/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The necessary data to perform this change.
 */
export type ChangeRequestDefaultChangeSchemaPayload = {
    [key: string]: unknown;
};
