/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export interface ChangeRequestEnvironmentConfigSchema {
    environment: string;
    type: string;
    changeRequestEnabled: boolean;
    requiredApprovals: number | null;
}
