/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfSixAction } from './changeRequestOneOrManyCreateSchemaOneOfSixAction.ts';
import type { ChangeRequestOneOrManyCreateSchemaOneOfSixPayload } from './changeRequestOneOrManyCreateSchemaOneOfSixPayload.ts';

/**
 * Update the enabled state for a feature.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfSix = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfSixAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestOneOrManyCreateSchemaOneOfSixPayload;
};
