/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfOnefiveAction =
    (typeof ChangeRequestCreateSchemaOneOfOnefiveAction)[keyof typeof ChangeRequestCreateSchemaOneOfOnefiveAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateSchemaOneOfOnefiveAction = {
    deleteStrategy: 'deleteStrategy',
} as const;
