/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfTwosevenAction } from './changeRequestOneOrManyCreateSchemaOneOfTwosevenAction.js';
import type { ReleasePlanTemplateIdSchema } from './releasePlanTemplateIdSchema.js';

/**
 * Add a release plan to this feature environment.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfTwoseven = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfTwosevenAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ReleasePlanTemplateIdSchema;
};
