/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfAction } from './changeRequestCreateSchemaOneOfAction';
import type { ChangeRequestCreateSchemaOneOfPayload } from './changeRequestCreateSchemaOneOfPayload';

export type ChangeRequestCreateSchemaOneOf = {
    action: ChangeRequestCreateSchemaOneOfAction;
    payload: ChangeRequestCreateSchemaOneOfPayload;
};
