/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateSchemaOneOfFivefiveAction =
    (typeof ChangeRequestCreateSchemaOneOfFivefiveAction)[keyof typeof ChangeRequestCreateSchemaOneOfFivefiveAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateSchemaOneOfFivefiveAction = {
    deleteFeatureEnvSafeguard: 'deleteFeatureEnvSafeguard',
} as const;
