/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Count of change requests in different stages of the [process](https://docs.getunleash.io/reference/change-requests#change-request-flow).
 */
export interface ChangeRequestsCountSchema {
    /** The number of applied change requests */
    applied: number;
    /** The number of approved change requests */
    approved: number;
    /** The number of rejected change requests */
    rejected: number;
    /** The number of change requests awaiting the review */
    reviewRequired: number;
    /** The number of scheduled change requests */
    scheduled: number;
    /** The number of total change requests in this project */
    total: number;
}
