/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestScheduleSchemaStatus } from './changeRequestScheduleSchemaStatus';

/**
 * A schedule for a change request.
 */
export interface ChangeRequestScheduleSchema {
    /** The reason the scheduled failed to apply. */
    failureReason?: string | null;
    /** When this change request is to be applied. */
    scheduledAt: string;
    /** The status of the schedule. */
    status: ChangeRequestScheduleSchemaStatus;
}
