/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of one or more feature flags.
 */
export type ChangeRequestScheduledQueryParamsSchemaFeature = string[] | string;
