/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateSafeguardSchema } from './createSafeguardSchema';

export type ChangeRequestCreateSchemaOneOfFourfourPayload = {
    /** The ID of the release plan. This ID is an ulid */
    planId: string;
    safeguard: CreateSafeguardSchema;
};
