/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestApprovalSchema } from './changeRequestApprovalSchema.js';
import type { ChangeRequestCommentSchema } from './changeRequestCommentSchema.js';
import type { ChangeRequestSchemaOneOfCreatedBy } from './changeRequestSchemaOneOfCreatedBy.js';
import type { ChangeRequestFeatureSchema } from './changeRequestFeatureSchema.js';
import type { ChangeRequestSegmentChangeSchema } from './changeRequestSegmentChangeSchema.js';
import type { ChangeRequestSchemaOneOfState } from './changeRequestSchemaOneOfState.js';
import type { ChangeRequestSchemaOneOfStateTimestamps } from './changeRequestSchemaOneOfStateTimestamps.js';

export type ChangeRequestSchemaOneOf = {
    /** A list of approvals that this change request has received. */
    approvals?: ChangeRequestApprovalSchema[];
    /** All comments that have been made on this change request. */
    comments?: ChangeRequestCommentSchema[];
    /** When this change request was created. */
    createdAt: string;
    /** The user who created this change request. */
    createdBy: ChangeRequestSchemaOneOfCreatedBy;
    /** The environment in which the changes should be applied. */
    environment: string;
    /** The list of features and their changes that relate to this change request. */
    features: ChangeRequestFeatureSchema[];
    /** This change requests's ID. */
    id: number;
    /** The minimum number of approvals required before this change request can be applied. */
    minApprovals: number;
    /** The project this change request belongs to. */
    project: string;
    /** A list of rejections that this change request has received.  */
    rejections?: ChangeRequestApprovalSchema[];
    /** The list of segments and their changes that relate to this change request. */
    segments: ChangeRequestSegmentChangeSchema[];
    /** The current state of the change request. */
    state: ChangeRequestSchemaOneOfState;
    /** A mapping of each state this change request has entered to the most recent time when it entered that state. If a change request has entered the same state multiple times, only the most recent timestamp will be included. */
    stateTimestamps: ChangeRequestSchemaOneOfStateTimestamps;
    /** A title describing the change request's content. */
    title?: string;
};
