/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfFournineAction } from './changeRequestOneOrManyCreateSchemaOneOfFournineAction';
import type { ChangeRequestOneOrManyCreateSchemaOneOfFourninePayload } from './changeRequestOneOrManyCreateSchemaOneOfFourninePayload';

/**
 * Delete a safeguard from a release plan.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFournine = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfFournineAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestOneOrManyCreateSchemaOneOfFourninePayload;
};
