/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfFourAction } from './changeRequestCreateSchemaOneOfFourAction';
import type { CreateFeatureStrategySchema } from './createFeatureStrategySchema';

export type ChangeRequestCreateSchemaOneOfFour = {
    action: ChangeRequestCreateSchemaOneOfFourAction;
    payload: CreateFeatureStrategySchema;
};
