/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The user who created this change request.
 */
export type ChangeRequestSchemaOneOfCreatedBy = {
    /** The URL of the user's profile image. */
    imageUrl?: string | null;
    username?: string | null;
};
