/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfOnefiveAction } from './changeRequestCreateFeatureSchemaOneOfOnefiveAction';
import type { ChangeRequestCreateFeatureSchemaOneOfOnefivePayload } from './changeRequestCreateFeatureSchemaOneOfOnefivePayload';

/**
 * Update variants for this feature.
 */
export type ChangeRequestCreateFeatureSchemaOneOfOnefive = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfOnefiveAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateFeatureSchemaOneOfOnefivePayload;
};
