/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The Id of the release plan to remove.
 */
export type ChangeRequestCreateSchemaOneOfThreetwoPayload = {
    /** The Id of the release plan. This id is an ulid */
    planId: string;
};
