/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestOneOrManyCreateSchemaOneOfFouroneAction } from './changeRequestOneOrManyCreateSchemaOneOfFouroneAction.js';
import type { ChangeRequestOneOrManyCreateSchemaOneOfFouronePayload } from './changeRequestOneOrManyCreateSchemaOneOfFouronePayload.js';

/**
 * Resume paused milestone progressions for a release plan.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfFourone = {
    /** The name of this action. */
    action: ChangeRequestOneOrManyCreateSchemaOneOfFouroneAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestOneOrManyCreateSchemaOneOfFouronePayload;
};
