/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateFeatureSchemaOneOfTwosixAction =
    (typeof ChangeRequestCreateFeatureSchemaOneOfTwosixAction)[keyof typeof ChangeRequestCreateFeatureSchemaOneOfTwosixAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateFeatureSchemaOneOfTwosixAction = {
    startMilestone: 'startMilestone',
} as const;
