/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOf } from './changeRequestCreateSchemaOneOf.js';
import type { ChangeRequestCreateSchemaOneOfThree } from './changeRequestCreateSchemaOneOfThree.js';
import type { ChangeRequestCreateSchemaOneOfSix } from './changeRequestCreateSchemaOneOfSix.js';
import type { ChangeRequestCreateSchemaOneOfNine } from './changeRequestCreateSchemaOneOfNine.js';
import type { ChangeRequestCreateSchemaOneOfOneone } from './changeRequestCreateSchemaOneOfOneone.js';
import type { ChangeRequestCreateSchemaOneOfOnethree } from './changeRequestCreateSchemaOneOfOnethree.js';
import type { ChangeRequestCreateSchemaOneOfOnesix } from './changeRequestCreateSchemaOneOfOnesix.js';
import type { ChangeRequestCreateSchemaOneOfOneeight } from './changeRequestCreateSchemaOneOfOneeight.js';
import type { ChangeRequestCreateSchemaOneOfTwoone } from './changeRequestCreateSchemaOneOfTwoone.js';
import type { ChangeRequestCreateSchemaOneOfTwothree } from './changeRequestCreateSchemaOneOfTwothree.js';
import type { ChangeRequestCreateSchemaOneOfTwofive } from './changeRequestCreateSchemaOneOfTwofive.js';
import type { ChangeRequestCreateSchemaOneOfTwoseven } from './changeRequestCreateSchemaOneOfTwoseven.js';
import type { ChangeRequestCreateSchemaOneOfTwonine } from './changeRequestCreateSchemaOneOfTwonine.js';
import type { ChangeRequestCreateSchemaOneOfThreetwo } from './changeRequestCreateSchemaOneOfThreetwo.js';
import type { ChangeRequestCreateSchemaOneOfThreefive } from './changeRequestCreateSchemaOneOfThreefive.js';
import type { ChangeRequestCreateSchemaOneOfThreeeight } from './changeRequestCreateSchemaOneOfThreeeight.js';
import type { ChangeRequestCreateSchemaOneOfFourone } from './changeRequestCreateSchemaOneOfFourone.js';
import type { ChangeRequestCreateSchemaOneOfFourfour } from './changeRequestCreateSchemaOneOfFourfour.js';
import type { ChangeRequestCreateSchemaOneOfFourseven } from './changeRequestCreateSchemaOneOfFourseven.js';

/**
 * Data used to create a [change request](https://docs.getunleash.io/reference/change-requests) for a single feature or segment change.
 */
export type ChangeRequestCreateSchema =
    | ChangeRequestCreateSchemaOneOf
    | ChangeRequestCreateSchemaOneOfThree
    | ChangeRequestCreateSchemaOneOfSix
    | ChangeRequestCreateSchemaOneOfNine
    | ChangeRequestCreateSchemaOneOfOneone
    | ChangeRequestCreateSchemaOneOfOnethree
    | ChangeRequestCreateSchemaOneOfOnesix
    | ChangeRequestCreateSchemaOneOfOneeight
    | ChangeRequestCreateSchemaOneOfTwoone
    | ChangeRequestCreateSchemaOneOfTwothree
    | ChangeRequestCreateSchemaOneOfTwofive
    | ChangeRequestCreateSchemaOneOfTwoseven
    | ChangeRequestCreateSchemaOneOfTwonine
    | ChangeRequestCreateSchemaOneOfThreetwo
    | ChangeRequestCreateSchemaOneOfThreefive
    | ChangeRequestCreateSchemaOneOfThreeeight
    | ChangeRequestCreateSchemaOneOfFourone
    | ChangeRequestCreateSchemaOneOfFourfour
    | ChangeRequestCreateSchemaOneOfFourseven;
