/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction = {
    deleteStrategy: 'deleteStrategy',
} as const;
