/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */

export type ChangeRequestStateSchemaState =
    typeof ChangeRequestStateSchemaState[keyof typeof ChangeRequestStateSchemaState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestStateSchemaState = {
    Draft: 'Draft',
    In_review: 'In review',
    Approved: 'Approved',
    Applied: 'Applied',
    Cancelled: 'Cancelled',
} as const;
