/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfThreeAction } from './changeRequestCreateSchemaOneOfThreeAction.js';
import type { ChangeRequestCreateSchemaOneOfThreePayload } from './changeRequestCreateSchemaOneOfThreePayload.js';

export type ChangeRequestCreateSchemaOneOfThree = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfThreeAction;
    /** Required data to delete a segment. */
    payload: ChangeRequestCreateSchemaOneOfThreePayload;
};
