/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfAction } from './changeRequestCreateSchemaOneOfAction.ts';
import type { UpsertSegmentSchema } from './upsertSegmentSchema.ts';

export type ChangeRequestCreateSchemaOneOf = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfAction;
    payload: UpsertSegmentSchema;
};
