/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfTwozeroAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfTwozeroAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfTwozeroAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestOneOrManyCreateSchemaOneOfTwozeroAction = {
    patchVariant: 'patchVariant',
} as const;
