/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateFeatureSchemaOneOfOnezeroAction } from './changeRequestCreateFeatureSchemaOneOfOnezeroAction';
import type { ChangeRequestCreateFeatureSchemaOneOfOnezeroPayload } from './changeRequestCreateFeatureSchemaOneOfOnezeroPayload';

/**
 * Delete a strategy from this feature.
 */
export type ChangeRequestCreateFeatureSchemaOneOfOnezero = {
    /** The name of this action. */
    action: ChangeRequestCreateFeatureSchemaOneOfOnezeroAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateFeatureSchemaOneOfOnezeroPayload;
};
