/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestCreateFeatureSchemaOneOfFouroneAction =
    (typeof ChangeRequestCreateFeatureSchemaOneOfFouroneAction)[keyof typeof ChangeRequestCreateFeatureSchemaOneOfFouroneAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateFeatureSchemaOneOfFouroneAction = {
    changeSafeguard: 'changeSafeguard',
} as const;
