/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ChangeRequestCreateSchemaOneOfFivetwoAction } from './changeRequestCreateSchemaOneOfFivetwoAction';
import type { ChangeRequestCreateSchemaOneOfFivetwoPayload } from './changeRequestCreateSchemaOneOfFivetwoPayload';

/**
 * Create or update a safeguard for a feature environment.
 */
export type ChangeRequestCreateSchemaOneOfFivetwo = {
    /** The name of this action. */
    action: ChangeRequestCreateSchemaOneOfFivetwoAction;
    /** The name of the feature that this change applies to. */
    feature: string;
    payload: ChangeRequestCreateSchemaOneOfFivetwoPayload;
};
