/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ChangeRequestCreateSchemaOneOfFourAction =
    typeof ChangeRequestCreateSchemaOneOfFourAction[keyof typeof ChangeRequestCreateSchemaOneOfFourAction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ChangeRequestCreateSchemaOneOfFourAction = {
    addStrategy: 'addStrategy',
} as const;
