/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The name of this action.
 */
export type ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction =
    (typeof ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction)[keyof typeof ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction];

export const ChangeRequestOneOrManyCreateSchemaOneOfOnethreeAction = {
    updateStrategy: 'updateStrategy',
} as const;
