/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ClientApplicationSchemaStarted } from './clientApplicationSchemaStarted';

export interface ClientApplicationSchema {
    appName: string;
    instanceId?: string;
    sdkVersion?: string;
    environment?: string;
    interval: number;
    started: ClientApplicationSchemaStarted;
    strategies: string[];
}
