/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ClientFeaturesDeltaSchemaEventsItemAnyOfFiveType =
    (typeof ClientFeaturesDeltaSchemaEventsItemAnyOfFiveType)[keyof typeof ClientFeaturesDeltaSchemaEventsItemAnyOfFiveType];

export const ClientFeaturesDeltaSchemaEventsItemAnyOfFiveType = {
    'segment-updated': 'segment-updated',
} as const;
