/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType =
    (typeof ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType)[keyof typeof ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType = {
    'feature-removed': 'feature-removed',
} as const;
