/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType } from './clientFeaturesDeltaSchemaEventsItemAnyOfThreeType';

export type ClientFeaturesDeltaSchemaEventsItemAnyOfThree = {
    eventId: number;
    type: ClientFeaturesDeltaSchemaEventsItemAnyOfThreeType;
    featureName: string;
    project: string;
};
