/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ClientFeaturesDeltaSchemaEventsItemAnyOfNineType =
    (typeof ClientFeaturesDeltaSchemaEventsItemAnyOfNineType)[keyof typeof ClientFeaturesDeltaSchemaEventsItemAnyOfNineType];

export const ClientFeaturesDeltaSchemaEventsItemAnyOfNineType = {
    hydration: 'hydration',
} as const;
