/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */
import type { DateSchema } from './dateSchema';
import type { ClientMetricsSchemaBucketToggles } from './clientMetricsSchemaBucketToggles';

export type ClientMetricsSchemaBucket = {
    start: DateSchema;
    stop: DateSchema;
    toggles: ClientMetricsSchemaBucketToggles;
};
