/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ClientMetricsSchemaBucketTogglesVariants } from './clientMetricsSchemaBucketTogglesVariants';

/**
 * an object containing feature names with yes/no plus variant usage
 */
export type ClientMetricsSchemaBucketToggles = {
    [key: string]: {
        /** How many times the toggle evaluated to true */
        yes?: number;
        /** How many times the toggle evaluated to false */
        no?: number;
        /** How many times each variant was returned */
        variants?: ClientMetricsSchemaBucketTogglesVariants;
    };
};
