/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ConstraintSchema } from './constraintSchema.js';

/**
 * Represents a client API segment of users defined by a set of constraints.
 */
export interface ClientSegmentSchema {
    /** List of constraints that determine which users are part of the segment */
    constraints: ConstraintSchema[];
    /** The segment's id. */
    id: number;
    /** The name of the segment. */
    name?: string;
}
