/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { LegalValueSchema } from './legalValueSchema';

export interface ContextFieldSchema {
    name: string;
    description?: string;
    stickiness?: boolean;
    sortOrder?: number;
    createdAt?: string | null;
    legalValues?: LegalValueSchema[];
}
