/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ContextFieldSchema } from './contextFieldSchema.ts';

/**
 * A list of context fields
 */
export type ContextFieldsSchema = ContextFieldSchema[];
