/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ContextFieldStrategiesSchemaStrategiesItem } from './contextFieldStrategiesSchemaStrategiesItem';

/**
 * A wrapper object containing all strategies that use a specific context field
 */
export interface ContextFieldStrategiesSchema {
    /** List of strategies using the context field */
    strategies: ContextFieldStrategiesSchemaStrategiesItem[];
}
