/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ConstraintSchema } from './constraintSchema';
import type { ParametersSchema } from './parametersSchema';
import type { CreateStrategyVariantSchema } from './createStrategyVariantSchema';

/**
 * Create a strategy configuration in a feature
 */
export interface CreateFeatureStrategySchema {
    /** A list of the constraints attached to the strategy. See https://docs.getunleash.io/concepts/activation-strategies#constraints */
    constraints?: ConstraintSchema[];
    /**
     * A toggle to disable the strategy. defaults to false. Disabled strategies are not evaluated or returned to the SDKs
     * @nullable
     */
    disabled?: boolean | null;
    /** The name of the strategy type */
    name: string;
    /** An object containing the parameters for the strategy */
    parameters?: ParametersSchema;
    /** Ids of segments to use for this strategy */
    segments?: number[];
    /** The order of the strategy in the list */
    sortOrder?: number;
    /**
     * A descriptive title for the strategy
     * @nullable
     */
    title?: string | null;
    /** Strategy level variants */
    variants?: CreateStrategyVariantSchema[];
}
