/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.2
 */
import type { ConstraintSchema } from './constraintSchema';
import type { ParametersSchema } from './parametersSchema';

export interface CreateFeatureStrategySchema {
    name: string;
    sortOrder?: number;
    constraints?: ConstraintSchema[];
    parameters?: ParametersSchema;
}
