/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * [Custom project roles](https://docs.getunleash.io/concepts/rbac#custom-project-roles) contain a specific set of permissions for project resources.
 */
export type CreateRoleWithPermissionsSchemaAnyOfFourType =
    (typeof CreateRoleWithPermissionsSchemaAnyOfFourType)[keyof typeof CreateRoleWithPermissionsSchemaAnyOfFourType];

export const CreateRoleWithPermissionsSchemaAnyOfFourType = {
    custom: 'custom',
} as const;
