/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { TransitionConditionSchema } from './transitionConditionSchema.js';

/**
 * Request body to create a milestone progression
 */
export interface CreateMilestoneProgressionSchema {
    /** The ID of the source milestone */
    sourceMilestone: string;
    /** The ID of the target milestone */
    targetMilestone: string;
    /** The condition configuration for the transition */
    transitionCondition: TransitionConditionSchema;
}
