/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateApiTokenSchema
 */
export interface CreateApiTokenSchema {
    /**
     * 
     * @type {string}
     * @memberof CreateApiTokenSchema
     */
    secret?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiTokenSchema
     */
    username: string;
    /**
     * client, admin, frontend.
     * @type {string}
     * @memberof CreateApiTokenSchema
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiTokenSchema
     */
    environment?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateApiTokenSchema
     */
    project?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateApiTokenSchema
     */
    projects?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof CreateApiTokenSchema
     */
    expiresAt?: Date | null;
}

/**
 * Check if a given object implements the CreateApiTokenSchema interface.
 */
export function instanceOfCreateApiTokenSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "type" in value;

    return isInstance;
}

export function CreateApiTokenSchemaFromJSON(json: any): CreateApiTokenSchema {
    return CreateApiTokenSchemaFromJSONTyped(json, false);
}

export function CreateApiTokenSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateApiTokenSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'secret': !exists(json, 'secret') ? undefined : json['secret'],
        'username': json['username'],
        'type': json['type'],
        'environment': !exists(json, 'environment') ? undefined : json['environment'],
        'project': !exists(json, 'project') ? undefined : json['project'],
        'projects': !exists(json, 'projects') ? undefined : json['projects'],
        'expiresAt': !exists(json, 'expiresAt') ? undefined : (json['expiresAt'] === null ? null : new Date(json['expiresAt'])),
    };
}

export function CreateApiTokenSchemaToJSON(value?: CreateApiTokenSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'secret': value.secret,
        'username': value.username,
        'type': value.type,
        'environment': value.environment,
        'project': value.project,
        'projects': value.projects,
        'expiresAt': value.expiresAt === undefined ? undefined : (value.expiresAt === null ? null : value.expiresAt.toISOString()),
    };
}

