/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateApiTokenSchemaOneOf } from './createApiTokenSchemaOneOf.js';

/**
 * The data required to create an [Unleash API token](https://docs.getunleash.io/concepts/api-tokens-and-client-keys).
 */
export type CreateApiTokenSchema = CreateApiTokenSchemaOneOf;
