/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Match the payload of the observable event
 */
export type CreateActionsSchemaMatchPayload = { [key: string]: any };
