/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Reported application information from Unleash SDKs
 */
export interface CreateApplicationSchema {
    /** Name of the application */
    appName?: string;
    /** Which SDK and version the application reporting uses. Typically represented as `<identifier>:<version>` */
    sdkVersion?: string;
    /** Which [strategies](https://docs.getunleash.io/topics/the-anatomy-of-unleash#activation-strategies) the application has loaded. Useful when trying to figure out if your [custom strategy](https://docs.getunleash.io/reference/custom-activation-strategies) has been loaded in the SDK */
    strategies?: string[];
    /** A link to reference the application reporting the metrics. Could for instance be a GitHub link to the repository of the application */
    url?: string;
    /** Css color to be used to color the application's entry in the application list */
    color?: string;
    /** An URL to an icon file to be used for the applications's entry in the application list */
    icon?: string;
    [key: string]: any;
}
