/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateReleasePlanMilestoneSchemaTransitionConditionOneOfType } from './createReleasePlanMilestoneSchemaTransitionConditionOneOfType';

/**
 * Transition after a fixed amount of time from milestone start
 */
export type CreateReleasePlanMilestoneSchemaTransitionConditionOneOf = {
    /**
     * The interval in minutes before transitioning
     * @minimum 1
     */
    intervalMinutes: number;
    /** Discriminator for time-based transitions. Omitting it means time-based. */
    type?: CreateReleasePlanMilestoneSchemaTransitionConditionOneOfType;
};
