/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The aggregation mode for the metric data.
 */
export type CreateImpactMetricsConfigSchemaAggregationMode =
    (typeof CreateImpactMetricsConfigSchemaAggregationMode)[keyof typeof CreateImpactMetricsConfigSchemaAggregationMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateImpactMetricsConfigSchemaAggregationMode = {
    rps: 'rps',
    count: 'count',
    avg: 'avg',
    sum: 'sum',
    p95: 'p95',
    p99: 'p99',
    p50: 'p50',
} as const;
