/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The role to assign to the user. Can be either the role's ID or its unique name.
 */
export type CreateUserSchemaRootRole =
    | number
    | 'Admin'
    | 'Editor'
    | 'Viewer'
    | 'Owner'
    | 'Member'
    | 'Reader';
