/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateSafeguardSchemaImpactMetricAggregationMode } from './createSafeguardSchemaImpactMetricAggregationMode.js';
import type { CreateSafeguardSchemaImpactMetricLabelSelectors } from './createSafeguardSchemaImpactMetricLabelSelectors.js';
import type { CreateSafeguardSchemaImpactMetricTimeRange } from './createSafeguardSchemaImpactMetricTimeRange.js';

/**
 * Metric configuration that should be evaluated for the safeguard.
 */
export type CreateSafeguardSchemaImpactMetric = {
    /** The aggregation mode for the metric data. */
    aggregationMode: CreateSafeguardSchemaImpactMetricAggregationMode;
    /** The selected labels and their values for filtering the metric data. */
    labelSelectors: CreateSafeguardSchemaImpactMetricLabelSelectors;
    /** The Prometheus metric series to query. It includes both unleash prefix and metric type and display name */
    metricName: string;
    /** The time range for the metric data. */
    timeRange: CreateSafeguardSchemaImpactMetricTimeRange;
};
