/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { LegalValueSchema } from './legalValueSchema.js';

/**
 * Data used to create a context field configuration.
 */
export interface CreateContextFieldSchema {
    /** A description of the context field */
    description?: string;
    /** A list of allowed values for this context field */
    legalValues?: LegalValueSchema[];
    /** The name of the context field. */
    name: string;
    /** How this context field should be sorted if no other sort order is selected */
    sortOrder?: number;
    /** `true` if this field should be available for use with [custom stickiness](https://docs.getunleash.io/concepts/stickiness#custom-stickiness), otherwise `false` */
    stickiness?: boolean;
}
