/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateActionsSchemaMatchPayload } from './createActionsSchemaMatchPayload';

/**
 * Defines a matching rule for the observable event that will trigger the action set
 */
export type CreateActionsSchemaMatch = {
    /** Match the payload of the observable event */
    payload: CreateActionsSchemaMatchPayload;
    /** Match the source of the observable event */
    source: string;
    /** Match the source id of the observable event */
    sourceId: number;
};
