/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateApiTokenSchemaOneOfAllOf } from './createApiTokenSchemaOneOfAllOf';
import type { CreateApiTokenSchemaOneOfAllOfTwo } from './createApiTokenSchemaOneOfAllOfTwo';

export type CreateApiTokenSchemaOneOf = CreateApiTokenSchemaOneOfAllOf &
    CreateApiTokenSchemaOneOfAllOfTwo;
