/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Labels to categorize the metric
 */
export type CustomMetricSchemaLabels = { [key: string]: string };
