/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type DeleteAddon401 = {
    /** The ID of the error instance */
    id?: string;
    /** The name of the error kind */
    name?: string;
    /** A description of what went wrong. */
    message?: string;
};
