/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * `true` when any dependencies exist, `false` when no dependencies exist.
 */
export type DependenciesExistSchema = boolean;
