/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export interface DetailedInvoicesLineSchema {
    /** Optional consumption associated with the line item */
    consumption?: number;
    /** Currency code */
    currency: string;
    /** Description of the line item */
    description: string;
    /** Optional limit associated with the line item */
    limit?: number;
    /** Lookup key identifying the product/pricing */
    lookupKey: string;
    /** Quantity of the item */
    quantity: number;
    /** Total amount for this line item in minor currency units */
    totalAmount: number;
}
