/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Representing latency for an Edge operation.
 */
export interface EdgeLatencyMetricsSchema {
    /**
     * Average time per request in milliseconds.
     * @minimum 0
     */
    avg: number;
    /**
     * Total number of requests made.
     * @minimum 0
     */
    count: number;
    /**
     * 99% of requests finished within this amount of milliseconds.
     * @minimum 0
     */
    p99: number;
}
