/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { EnvironmentSchema } from './environmentSchema';

/**
 * A versioned list of environments
 */
export interface EnvironmentsSchema {
    /** Version of the environments schema */
    version: number;
    /** List of environments */
    environments: EnvironmentSchema[];
}
