/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */

export interface EnvironmentProjectSchema {
    name: string;
    type: string;
    enabled: boolean;
    protected?: boolean;
    sortOrder?: number;
    projectApiTokenCount?: number | null;
    projectEnabledToggleCount?: number | null;
}
