/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { EnvironmentProjectSchema } from './environmentProjectSchema';

export interface EnvironmentsProjectSchema {
    version: number;
    environments: EnvironmentProjectSchema[];
}
