/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ExecutiveSummarySchemaFlagsTrendsItem } from './executiveSummarySchemaFlagsTrendsItem';
import type { ExecutiveSummarySchemaUserStats } from './executiveSummarySchemaUserStats';
import type { ExecutiveSummarySchemaUserTrendsItem } from './executiveSummarySchemaUserTrendsItem';

/**
 * Executive summary of Unleash usage
 */
export interface ExecutiveSummarySchema {
    /** How number of flags changed over time */
    flagsTrends: ExecutiveSummarySchemaFlagsTrendsItem[];
    /** The type of single-sign option configured for the Unleash instance */
    ssoType?: string;
    /** High level user count statistics */
    userStats: ExecutiveSummarySchemaUserStats;
    /** How number of users changed over time */
    userTrends: ExecutiveSummarySchemaUserTrendsItem[];
}
