/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */
import type { ContextFieldSchema } from './contextFieldSchema';
import type { ExportResultSchemaSegmentsItem } from './exportResultSchemaSegmentsItem';
import type { FeatureEnvironmentSchema } from './featureEnvironmentSchema';
import type { FeatureSchema } from './featureSchema';
import type { FeatureStrategySchema } from './featureStrategySchema';
import type { FeatureTagSchema } from './featureTagSchema';
import type { TagTypeSchema } from './tagTypeSchema';

export interface ExportResultSchema {
    features: FeatureSchema[];
    featureStrategies: FeatureStrategySchema[];
    featureEnvironments?: FeatureEnvironmentSchema[];
    contextFields?: ContextFieldSchema[];
    featureTags?: FeatureTagSchema[];
    segments?: ExportResultSchemaSegmentsItem[];
    tagTypes: TagTypeSchema[];
}
