/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */
import type { ExportFormat } from './exportFormat';

export type ExportParams = {
    format?: ExportFormat;
    download?: boolean | string | number;
    strategies?: boolean | string | number;
    featureToggles?: boolean | string | number;
    projects?: boolean | string | number;
    tags?: boolean | string | number;
    environments?: boolean | string | number;
};
