/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ExportQuerySchemaAnyOf } from './exportQuerySchemaAnyOf';
import type { ExportQuerySchemaAnyOfTwo } from './exportQuerySchemaAnyOfTwo';
import type { ExportQuerySchemaAnyOfThree } from './exportQuerySchemaAnyOfThree';

/**
 * Available query parameters for  the deprecated export/import functionality.
 */
export type ExportQuerySchema =
    | ExportQuerySchemaAnyOf
    | ExportQuerySchemaAnyOfTwo
    | ExportQuerySchemaAnyOfThree;
