/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FeatureSchemaCollaboratorsUsersItem } from './featureSchemaCollaboratorsUsersItem';

/**
 * Information related to users who have made changes to this feature flage.
 */
export type FeatureSchemaCollaborators = {
    /** Users who have made any changes to this feature flags. The list is sorted in reverse chronological order (most recent changes first) */
    users: FeatureSchemaCollaboratorsUsersItem[];
};
