/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * User who created the feature flag
 */
export type FeatureSearchResponseSchemaCreatedBy = {
    /** The user id */
    id: number;
    /** URL used for the user profile image */
    imageUrl: string;
    /** Name of the user */
    name: string;
};
