/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ConstraintSchema } from './ConstraintSchema';
import {
    ConstraintSchemaFromJSON,
    ConstraintSchemaFromJSONTyped,
    ConstraintSchemaToJSON,
} from './ConstraintSchema';

/**
 * 
 * @export
 * @interface FeatureStrategySchema
 */
export interface FeatureStrategySchema {
    /**
     * 
     * @type {string}
     * @memberof FeatureStrategySchema
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureStrategySchema
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof FeatureStrategySchema
     */
    sortOrder?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof FeatureStrategySchema
     */
    segments?: Array<number>;
    /**
     * 
     * @type {Array<ConstraintSchema>}
     * @memberof FeatureStrategySchema
     */
    constraints?: Array<ConstraintSchema>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof FeatureStrategySchema
     */
    parameters?: { [key: string]: string; };
}

/**
 * Check if a given object implements the FeatureStrategySchema interface.
 */
export function instanceOfFeatureStrategySchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function FeatureStrategySchemaFromJSON(json: any): FeatureStrategySchema {
    return FeatureStrategySchemaFromJSONTyped(json, false);
}

export function FeatureStrategySchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureStrategySchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'sortOrder': !exists(json, 'sortOrder') ? undefined : json['sortOrder'],
        'segments': !exists(json, 'segments') ? undefined : json['segments'],
        'constraints': !exists(json, 'constraints') ? undefined : ((json['constraints'] as Array<any>).map(ConstraintSchemaFromJSON)),
        'parameters': !exists(json, 'parameters') ? undefined : json['parameters'],
    };
}

export function FeatureStrategySchemaToJSON(value?: FeatureStrategySchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'sortOrder': value.sortOrder,
        'segments': value.segments,
        'constraints': value.constraints === undefined ? undefined : ((value.constraints as Array<any>).map(ConstraintSchemaToJSON)),
        'parameters': value.parameters,
    };
}

