/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ConstraintSchema } from './constraintSchema.js';
import type { ParametersSchema } from './parametersSchema.js';
import type { StrategyVariantSchema } from './strategyVariantSchema.js';

/**
 * A single activation strategy configuration schema for a feature
 */
export interface FeatureStrategySchema {
    /** A list of the constraints attached to the strategy. See https://docs.getunleash.io/reference/activation-strategies#constraints */
    constraints?: ConstraintSchema[];
    /**
     * A toggle to disable the strategy. defaults to false. Disabled strategies are not evaluated or returned to the SDKs
     * @nullable
     */
    disabled?: boolean | null;
    /** The name or feature the strategy is attached to */
    featureName?: string;
    /** A uuid for the feature strategy */
    id?: string;
    /** The name or type of strategy */
    name: string;
    parameters?: ParametersSchema;
    /** A list of segment ids attached to the strategy */
    segments?: number[];
    /** The order of the strategy in the list */
    sortOrder?: number;
    /**
     * A descriptive title for the strategy
     * @nullable
     */
    title?: string | null;
    /** Strategy level variants */
    variants?: StrategyVariantSchema[];
}
