/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { DependentFeatureSchema } from './dependentFeatureSchema';

/**
 * Feature dependency connection between a child feature and its dependencies
 */
export interface FeatureDependenciesSchema {
    /** List of parent features for the child feature */
    dependencies: DependentFeatureSchema[];
    /** The name of the child feature. */
    feature: string;
}
