/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Disable a feature in an environment when triggered.
 */
export type FeatureEnvironmentSafeguardSchemaAction = {
    /** The environment this safeguard applies to. */
    environment: string;
    /** The feature flag name this safeguard applies to. */
    featureName: string;
    /** The project this safeguard applies to. */
    project: string;
    /** The type of action to perform. */
    type: string;
};
