/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */

export interface FeatureTagSchema {
    featureName: string;
    tagType?: string;
    tagValue: string;
    type?: string;
    value?: string;
}
