/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FeatureTypesSchemaVersion } from './featureTypesSchemaVersion';
import type { FeatureTypeSchema } from './featureTypeSchema';

/**
 * A list of [feature toggle types](https://docs.getunleash.io/reference/feature-toggle-types) and the schema version used to represent those feature types.
 */
export interface FeatureTypesSchema {
    /** The schema version used to describe the feature toggle types listed in the `types` property. */
    version: FeatureTypesSchemaVersion;
    /** The list of feature toggle types. */
    types: FeatureTypeSchema[];
}
