/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The Prometheus data source for this metric. Internal is the Unleash-managed Prometheus, external is a customer-provided Prometheus instance. Defaults to internal if not specified.
 */
export type FeatureEnvironmentSafeguardSchemaImpactMetricSource =
    (typeof FeatureEnvironmentSafeguardSchemaImpactMetricSource)[keyof typeof FeatureEnvironmentSafeguardSchemaImpactMetricSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeatureEnvironmentSafeguardSchemaImpactMetricSource = {
    internal: 'internal',
    external: 'external',
} as const;
