/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The link to any URL related to the feature
 */
export interface FeatureLinkSchema {
    /**
     * The description of the link
     * @nullable
     */
    title?: string | null;
    /** The URL the feature is linked to */
    url: string;
}
