/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { VariantSchema } from './variantSchema';

/**
 * A versioned collection of feature flag variants.
 */
export interface FeatureVariantsSchema {
    /** The version of the feature variants schema. */
    version: number;
    /** All variants defined for a specific feature flag. */
    variants: VariantSchema[];
}
