/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * An API versioning number
 * @minimum 1
 */
export type FeatureEventsSchemaVersion =
    (typeof FeatureEventsSchemaVersion)[keyof typeof FeatureEventsSchemaVersion];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeatureEventsSchemaVersion = {
    NUMBER_1: 1,
} as const;
