/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FeatureSchema } from './featureSchema';

/**
 * A list of features
 * @deprecated
 */
export interface FeaturesSchema {
    /** A list of features */
    features: FeatureSchema[];
    /** The version of the feature's schema */
    version: number;
}
