/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureStrategySegmentSchema
 */
export interface FeatureStrategySegmentSchema {
    /**
     * 
     * @type {number}
     * @memberof FeatureStrategySegmentSchema
     */
    segmentId: number;
    /**
     * 
     * @type {string}
     * @memberof FeatureStrategySegmentSchema
     */
    featureStrategyId: string;
}

/**
 * Check if a given object implements the FeatureStrategySegmentSchema interface.
 */
export function instanceOfFeatureStrategySegmentSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "segmentId" in value;
    isInstance = isInstance && "featureStrategyId" in value;

    return isInstance;
}

export function FeatureStrategySegmentSchemaFromJSON(json: any): FeatureStrategySegmentSchema {
    return FeatureStrategySegmentSchemaFromJSONTyped(json, false);
}

export function FeatureStrategySegmentSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureStrategySegmentSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'segmentId': json['segmentId'],
        'featureStrategyId': json['featureStrategyId'],
    };
}

export function FeatureStrategySegmentSchemaToJSON(value?: FeatureStrategySegmentSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'segmentId': value.segmentId,
        'featureStrategyId': value.featureStrategyId,
    };
}

