/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FlagCreatorsSchemaFlagCreatorsItem } from './flagCreatorsSchemaFlagCreatorsItem';

/**
 * A paginated list of users who have created flags across accessible projects.
 */
export interface FlagCreatorsSchema {
    /** The flag creators returned in the current page. */
    flagCreators: FlagCreatorsSchemaFlagCreatorsItem[];
    /** The total number of flag creators matching the search and access filters. */
    total: number;
}
