/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FrontendApiFeatureSchemaVariantPayloadType } from './frontendApiFeatureSchemaVariantPayloadType.js';

/**
 * Extra data configured for this variant
 */
export type FrontendApiFeatureSchemaVariantPayload = {
    /** The format of the payload. */
    type: FrontendApiFeatureSchemaVariantPayloadType;
    /** The payload value stringified. */
    value: string;
};
