/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FrontendApiFeatureSchema } from './frontendApiFeatureSchema';

/**
 * Frontend SDK features list
 */
export interface FrontendApiFeaturesSchema {
    /** The actual features returned to the Frontend SDK */
    toggles: FrontendApiFeatureSchema[];
}
