/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { GetConnectionsForPeriodGrouping } from './getConnectionsForPeriodGrouping';

export type GetConnectionsForPeriodParams = {
    /**
     * Whether to aggregate the data by month or by day
     */
    grouping: GetConnectionsForPeriodGrouping;
    /**
     * The starting date of the traffic data usage search in IS:yyyy-MM-dd format
     */
    from: string;
    /**
     * The starting date of the traffic data usage search in IS:yyyy-MM-dd format
     */
    to: string;
};
