/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { GetFeatureFeedbackSchemaMetadata } from './getFeatureFeedbackSchemaMetadata';

/**
 * Feedback passed from SDK to Unleash.
 */
export interface GetFeatureFeedbackSchema {
    /** Unique id for this feedback. */
    id: number;
    /** Timestamp for when this feedback was created. */
    createdAt: string;
    /** Number representing user feedback rating. 1-5. */
    payload: string;
    /** The name of the feature toggle this feedback applies to. */
    featureName: string;
    /** A hash of the context that this feedback was provided for. */
    contextHash?: string | null;
    /** Metadata saved alongside the feedback. */
    metadata?: GetFeatureFeedbackSchemaMetadata;
}
