/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { GetRequestsForPeriodGrouping } from './getRequestsForPeriodGrouping.js';

export type GetRequestsForPeriodParams = {
    /**
     * Whether to aggregate the data by month or by day
     */
    grouping: GetRequestsForPeriodGrouping;
    /**
     * The starting date of the traffic data usage search in IS:yyyy-MM-dd format
     */
    from: string;
    /**
     * The starting date of the traffic data usage search in IS:yyyy-MM-dd format
     */
    to: string;
};
