/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type GetUserRolesParams = {
    /**
     * The id of the project you want to check permissions for
     */
    projectId?: string;
};
