/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */

export interface GoogleSettingsSchema {
    enabled?: boolean;
    clientId: string;
    clientSecret: string;
    unleashHostname: string;
    autoCreate?: boolean;
    emailDomains?: string;
}
