/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { GroupUserModelSchema } from './groupUserModelSchema';

export interface GroupSchema {
    id?: number;
    name: string;
    description?: string | null;
    mappingsSSO?: string[];
    createdBy?: string | null;
    createdAt?: string | null;
    users?: GroupUserModelSchema[];
    projects?: string[];
    [key: string]: any;
}
