/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A detailed information about a user group
 */
export interface GroupItemSchema {
    /**
     * A custom description of the group
     * @nullable
     */
    description?: string | null;
    /** The group id */
    id?: number;
    /** A list of SSO groups that should map to this Unleash group */
    mappingsSSO?: string[];
    /** The name of the group */
    name: string;
    /**
     * A role id that is used as the root role for all users in this group. This can be either the id of the Viewer, Editor or Admin role.
     * @nullable
     */
    rootRole?: number | null;
    /**
     * The SCIM ID of the group, only present if managed by SCIM
     * @nullable
     */
    scimId?: string | null;
}
