/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { GroupSchema } from './groupSchema';

export interface GroupsSchema {
    groups?: GroupSchema[];
}
