/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckSchema
 */
export interface HealthCheckSchema {
    /**
     * 
     * @type {string}
     * @memberof HealthCheckSchema
     */
    health: HealthCheckSchemaHealthEnum;
}


/**
 * @export
 */
export const HealthCheckSchemaHealthEnum = {
    Good: 'GOOD',
    Bad: 'BAD'
} as const;
export type HealthCheckSchemaHealthEnum = typeof HealthCheckSchemaHealthEnum[keyof typeof HealthCheckSchemaHealthEnum];


/**
 * Check if a given object implements the HealthCheckSchema interface.
 */
export function instanceOfHealthCheckSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "health" in value;

    return isInstance;
}

export function HealthCheckSchemaFromJSON(json: any): HealthCheckSchema {
    return HealthCheckSchemaFromJSONTyped(json, false);
}

export function HealthCheckSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'health': json['health'],
    };
}

export function HealthCheckSchemaToJSON(value?: HealthCheckSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'health': value.health,
    };
}

