/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { HealthCheckSchemaHealth } from './healthCheckSchemaHealth';

export interface HealthCheckSchema {
    health: HealthCheckSchemaHealth;
}
