/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A mode of the project affecting what actions are possible in this project. During a rollout of project modes this feature can be optional or `null`
 */
export type HealthReportSchemaMode =
    typeof HealthReportSchemaMode[keyof typeof HealthReportSchemaMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthReportSchemaMode = {
    open: 'open',
    protected: 'protected',
    null: null,
} as const;
