/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { HealthCheckSchemaHealth } from './healthCheckSchemaHealth';

/**
 * Used by service orchestrators to decide whether this Unleash instance should be marked as healthy or unhealthy
 */
export interface HealthCheckSchema {
    /** The state this Unleash instance is in. GOOD if the server is up and running. It never returns BAD, if the server is unhealthy you will get an unsuccessful http response. */
    health: HealthCheckSchemaHealth;
}
