/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */

export type HealthCheckSchemaHealth = typeof HealthCheckSchemaHealth[keyof typeof HealthCheckSchemaHealth];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HealthCheckSchemaHealth = {
  GOOD: 'GOOD',
  BAD: 'BAD',
} as const;
