/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ImpactMetricsConfigSchemaSelectedLabels } from './impactMetricsConfigSchemaSelectedLabels.js';
import type { ImpactMetricsConfigSchemaSelectedRange } from './impactMetricsConfigSchemaSelectedRange.js';

/**
 * Describes the configuration for a single impact metric chart.
 */
export interface ImpactMetricsConfigSchema {
    /** The aggregation mode for the metric data. */
    aggregationMode: string;
    /** Whether the chart should begin at zero on the y-axis. */
    beginAtZero: boolean;
    /**
     * Optional feature name that this impact metric is associated with.
     * @nullable
     */
    feature?: string | null;
    /** The unique ULID identifier for this impact metric configuration. Generated automatically if not provided. */
    id?: string;
    /** The selected labels and their values for filtering the metric data. */
    selectedLabels: ImpactMetricsConfigSchemaSelectedLabels;
    /** The time range for the metric data. */
    selectedRange: ImpactMetricsConfigSchemaSelectedRange;
    /** The Prometheus metric series to display. */
    selectedSeries: string;
    /**
     * Optional title for the impact metric chart.
     * @nullable
     */
    title?: string | null;
}
