/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The type of metric
 */
export type ImpactMetricsConfigSchemaType =
    (typeof ImpactMetricsConfigSchemaType)[keyof typeof ImpactMetricsConfigSchemaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImpactMetricsConfigSchemaType = {
    counter: 'counter',
    gauge: 'gauge',
    histogram: 'histogram',
    unknown: 'unknown',
} as const;
