/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ImpactMetricsDataSchemaSeriesItemDataItemItem } from './impactMetricsDataSchemaSeriesItemDataItemItem';
import type { ImpactMetricsDataSchemaSeriesItemMetric } from './impactMetricsDataSchemaSeriesItemMetric';

export type ImpactMetricsDataSchemaSeriesItem = {
    /** Array of [timestamp, value] data points. Timestamps are Unix epoch seconds; values are strings. */
    data: ImpactMetricsDataSchemaSeriesItemDataItemItem[][];
    /** Label key-value pairs identifying this series. */
    metric: ImpactMetricsDataSchemaSeriesItemMetric;
};
