/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ImpactMetricsConfigSchemaAggregationMode } from './impactMetricsConfigSchemaAggregationMode';
import type { ImpactMetricsConfigSchemaLabelSelectors } from './impactMetricsConfigSchemaLabelSelectors';
import type { ImpactMetricsConfigSchemaMode } from './impactMetricsConfigSchemaMode';
import type { ImpactMetricsConfigSchemaStep } from './impactMetricsConfigSchemaStep';
import type { ImpactMetricsConfigSchemaTimeRange } from './impactMetricsConfigSchemaTimeRange';
import type { ImpactMetricsConfigSchemaType } from './impactMetricsConfigSchemaType';
import type { ImpactMetricsConfigSchemaYAxisMin } from './impactMetricsConfigSchemaYAxisMin';

/**
 * Describes the configuration for a single impact metric chart.
 */
export interface ImpactMetricsConfigSchema {
    /** The aggregation mode for the metric data. */
    aggregationMode: ImpactMetricsConfigSchemaAggregationMode;
    /** The human readable display name of the impact metric */
    displayName: string;
    /** The unique ULID identifier for this impact metric configuration. Generated automatically if not provided. */
    id: string;
    /** The selected labels and their values for filtering the metric data. */
    labelSelectors: ImpactMetricsConfigSchemaLabelSelectors;
    /** The Prometheus metric series to query. It includes both unleash prefix and metric type and display name */
    metricName: string;
    /** The access mode for this impact metric configuration: "read" when referenced by a safeguard, "write" otherwise. */
    mode?: ImpactMetricsConfigSchemaMode;
    /**
     * The step interval for querying metrics data. This is automatically calculated from the timeRange and stored when the metric is created or updated.
     * @nullable
     */
    step?: ImpactMetricsConfigSchemaStep;
    /** The time range for the metric data. */
    timeRange: ImpactMetricsConfigSchemaTimeRange;
    /**
     * Optional title for the impact metric chart.
     */
    title?: string;
    /** The type of metric */
    type: ImpactMetricsConfigSchemaType;
    /** Whether the chart should begin at zero on the y-axis. */
    yAxisMin: ImpactMetricsConfigSchemaYAxisMin;
}
