/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ImpactMetricsSchemaOneOfSamplesItem } from './impactMetricsSchemaOneOfSamplesItem';
import type { ImpactMetricsSchemaOneOfType } from './impactMetricsSchemaOneOfType';

export type ImpactMetricsSchemaOneOf = {
    /** Human-readable description of what the metric measures */
    help: string;
    /** Name of the impact metric */
    name: string;
    /** Samples of the numeric metric */
    samples: ImpactMetricsSchemaOneOfSamplesItem[];
    /** Type of the metric */
    type: ImpactMetricsSchemaOneOfType;
};
