/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ImpactMetricsConfigSchema } from './impactMetricsConfigSchema.js';

/**
 * A list of impact metrics configurations for a feature flag.
 */
export interface ImpactMetricsConfigListSchema {
    /** The list of impact metrics configurations. */
    configs: ImpactMetricsConfigSchema[];
}
