/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Type of the metric
 */
export type ImpactMetricsSchemaType =
    (typeof ImpactMetricsSchemaType)[keyof typeof ImpactMetricsSchemaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImpactMetricsSchemaType = {
    counter: 'counter',
    gauge: 'gauge',
} as const;
