/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The selected labels and their values for filtering the metric data.
 */
export type ImpactMetricsConfigSchemaLabelSelectors = {
    [key: string]: string[];
};
