/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Optional labels for the metric sample
 */
export type ImpactMetricsSchemaOneOfSamplesItemLabels = {
    [key: string]: string | number;
};
