/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A description of an error or warning pertaining to a feature flag import job.
 */
export interface ImportTogglesValidateItemSchema {
    /** The items affected by this error message  */
    affectedItems: string[];
    /** The validation error message */
    message: string;
}
