/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ExportResultSchema } from './exportResultSchema';

export interface ImportTogglesSchema {
    project: string;
    environment: string;
    data: ExportResultSchema;
}
