/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { IncomingWebhookEventSchema } from './incomingWebhookEventSchema';

/**
 * A response model with a list of incoming webhook events.
 */
export interface IncomingWebhookEventsSchema {
    /** A list of incoming webhook events. */
    incomingWebhookEvents: IncomingWebhookEventSchema[];
}
