/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { InstanceInsightsSchemaEnvironmentTypeTrendsItem } from './instanceInsightsSchemaEnvironmentTypeTrendsItem';
import type { InstanceInsightsSchemaFlagTrendsItem } from './instanceInsightsSchemaFlagTrendsItem';
import type { InstanceInsightsSchemaMetricsSummaryTrendsItem } from './instanceInsightsSchemaMetricsSummaryTrendsItem';
import type { InstanceInsightsSchemaProjectFlagTrendsItem } from './instanceInsightsSchemaProjectFlagTrendsItem';
import type { InstanceInsightsSchemaUserTrendsItem } from './instanceInsightsSchemaUserTrendsItem';

/**
 * A summary of this Unleash instance's usage statistics, including user and flag counts, and trends over time.
 */
export interface InstanceInsightsSchema {
    /** How updates per environment type changed over time */
    environmentTypeTrends: InstanceInsightsSchemaEnvironmentTypeTrendsItem[];
    /** How number of flags changed over time */
    flagTrends: InstanceInsightsSchemaFlagTrendsItem[];
    /** How metrics data per project changed over time */
    metricsSummaryTrends: InstanceInsightsSchemaMetricsSummaryTrendsItem[];
    /** How number of flags per project changed over time */
    projectFlagTrends: InstanceInsightsSchemaProjectFlagTrendsItem[];
    /** How number of users changed over time */
    userTrends: InstanceInsightsSchemaUserTrendsItem[];
}
