/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The billable number of edge instances in the last 30, 60 and 90 days
 */
export type InstanceAdminStatsSchemaEdgeInstances = {
    /**
     * The billable number of edge instances in the last 30 days
     * @minimum 0
     */
    last30?: number;
    /**
     * The billable number of edge instances in the last 60 days
     * @minimum 0
     */
    last60?: number;
    /**
     * The billable number of edge instances in the last 90 days
     * @minimum 0
     */
    last90?: number;
};
