/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { InstanceInsightsSchemaLifecycleTrendsProductionCategories } from './instanceInsightsSchemaLifecycleTrendsProductionCategories.js';

export type InstanceInsightsSchemaLifecycleTrendsProduction = {
    totalFlags: number;
    averageTimeInStageDays: number;
    categories: InstanceInsightsSchemaLifecycleTrendsProductionCategories;
};
