/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesExperimental } from './instanceInsightsSchemaLifecycleTrendsDevelopCategoriesExperimental.js';
import type { InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesRelease } from './instanceInsightsSchemaLifecycleTrendsDevelopCategoriesRelease.js';
import type { InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesPermanent } from './instanceInsightsSchemaLifecycleTrendsDevelopCategoriesPermanent.js';

export type InstanceInsightsSchemaLifecycleTrendsDevelopCategories = {
    experimental: InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesExperimental;
    release: InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesRelease;
    permanent: InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesPermanent;
};
