/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type InstanceInsightsSchemaLifecycleTrendsProductionCategoriesPermanent =
    {
        flagsOlderThanWeek: number;
        newFlagsThisWeek: number;
    };
