/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Count of newly created flags by flag type
 */
export type InstanceInsightsSchemaCreationArchiveTrendsItemCreatedFlags = {
    [key: string]: number;
};
