/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type InstanceInsightsSchemaLifecycleTrendsDevelopCategoriesRelease = {
    flagsOlderThanWeek: number;
    newFlagsThisWeek: number;
};
