/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A description of a time range
 */
export type InstanceAdminStatsSchemaClientAppsItemRange =
    typeof InstanceAdminStatsSchemaClientAppsItemRange[keyof typeof InstanceAdminStatsSchemaClientAppsItemRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InstanceAdminStatsSchemaClientAppsItemRange = {
    allTime: 'allTime',
    '30d': '30d',
    '7d': '7d',
} as const;
