/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { IntegrationEventSchemaDetails } from './integrationEventSchemaDetails.js';
import type { EventSchema } from './eventSchema.js';
import type { IntegrationEventSchemaState } from './integrationEventSchemaState.js';

/**
 * An object describing an integration event.
 */
export interface IntegrationEventSchema {
    /** The date and time of when the integration event was created. In other words, the date and time of when the integration handled the event. */
    createdAt: string;
    /** Detailed information about the integration event. The contents vary depending on the type of integration and the specific details. */
    details: IntegrationEventSchemaDetails;
    /** The event that triggered this integration event. */
    event: EventSchema;
    /**
     * The integration event's ID. Integration event IDs are incrementing integers. In other words, a more recently created integration event will always have a higher ID than an older one. This ID is represented as a string since it is a BigInt.
     * @pattern ^[0-9]+$
     */
    id: string;
    /** The ID of the integration that the integration event belongs to. */
    integrationId: number;
    /** The state of the integration event. Can be one of `success`, `failed` or `successWithErrors`. */
    state: IntegrationEventSchemaState;
    /** Details about the state of the integration event. */
    stateDetails: string;
}
