/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Describes a legal value. Typically used to limit possible values for contextFields or strategy properties
 */
export interface LegalValueSchema {
    /** Describes this specific legal value */
    description?: string;
    /** The valid value */
    value: string;
}
