/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { LifecycleTrendsSchemaLifecycleTrendsCleanupCategories } from './lifecycleTrendsSchemaLifecycleTrendsCleanupCategories';

export type LifecycleTrendsSchemaLifecycleTrendsCleanup = {
    categories: LifecycleTrendsSchemaLifecycleTrendsCleanupCategories;
    medianDaysHistorically: number;
    medianDaysInCurrentStage: number;
    totalFlags: number;
};
