/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesExperimental } from './lifecycleTrendsSchemaLifecycleTrendsProductionCategoriesExperimental';
import type { LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesPermanent } from './lifecycleTrendsSchemaLifecycleTrendsProductionCategoriesPermanent';
import type { LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesRelease } from './lifecycleTrendsSchemaLifecycleTrendsProductionCategoriesRelease';

export type LifecycleTrendsSchemaLifecycleTrendsProductionCategories = {
    experimental: LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesExperimental;
    permanent: LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesPermanent;
    release: LifecycleTrendsSchemaLifecycleTrendsProductionCategoriesRelease;
};
