/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The type of event. `login` for sign-in attempts and `logout` for sign-outs.
 */
export type LoginEventSchemaType =
    (typeof LoginEventSchemaType)[keyof typeof LoginEventSchemaType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LoginEventSchemaType = {
    login: 'login',
    logout: 'logout',
} as const;
