/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export interface MarkNotificationsAsReadSchema {
    notifications: number[];
    [key: string]: any;
}
