/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { MetricQuerySchemaAggregationMode } from './metricQuerySchemaAggregationMode';
import type { MetricQuerySchemaLabelSelectors } from './metricQuerySchemaLabelSelectors';
import type { MetricQuerySchemaTimeRange } from './metricQuerySchemaTimeRange';

/**
 * Common metric query configuration for selecting and filtering metric data.
 */
export interface MetricQuerySchema {
    /** The aggregation mode for the metric data. */
    aggregationMode: MetricQuerySchemaAggregationMode;
    /** The selected labels and their values for filtering the metric data. */
    labelSelectors: MetricQuerySchemaLabelSelectors;
    /** The Prometheus metric series to query. It includes both unleash prefix and metric type and display name */
    metricName: string;
    /** The time range for the metric data. */
    timeRange: MetricQuerySchemaTimeRange;
}
