/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The time range for the metric data.
 */
export type MetricQuerySchemaTimeRange =
    (typeof MetricQuerySchemaTimeRange)[keyof typeof MetricQuerySchemaTimeRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MetricQuerySchemaTimeRange = {
    hour: 'hour',
    day: 'day',
    week: 'week',
    month: 'month',
} as const;
