/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { TransitionConditionSchema } from './transitionConditionSchema';

/**
 * A milestone progression configuration
 */
export interface MilestoneProgressionSchema {
    /** The ID of the source milestone */
    sourceMilestone: string;
    /** The ID of the target milestone */
    targetMilestone: string;
    /** The condition that triggers the transition */
    transitionCondition: TransitionConditionSchema;
}
