/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NameSchema
 */
export interface NameSchema {
    /**
     * 
     * @type {string}
     * @memberof NameSchema
     */
    name: string;
}

/**
 * Check if a given object implements the NameSchema interface.
 */
export function instanceOfNameSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function NameSchemaFromJSON(json: any): NameSchema {
    return NameSchemaFromJSONTyped(json, false);
}

export function NameSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function NameSchemaToJSON(value?: NameSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

