/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { NotificationsSchemaItem } from './notificationsSchemaItem';

/**
 * A list of [notifications](https://docs.getunleash.io/concepts/notifications)
 */
export type NotificationsSchema = NotificationsSchemaItem[];
