/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type NotificationsSchemaItemCreatedBy = {
    /**
     * The avatar url of the user who triggered the notification
     * @nullable
     */
    imageUrl?: string | null;
    /**
     * The name of the user who triggered the notification
     * @nullable
     */
    username?: string | null;
};
