/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The signing algorithm used to sign our token. Refer to the [JWT signatures](https://jwt.io/introduction) documentation for more information.
 */
export type OidcSettingsSchemaIdTokenSigningAlgorithm =
    typeof OidcSettingsSchemaIdTokenSigningAlgorithm[keyof typeof OidcSettingsSchemaIdTokenSigningAlgorithm];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OidcSettingsSchemaIdTokenSigningAlgorithm = {
    RS256: 'RS256',
    RS384: 'RS384',
    RS512: 'RS512',
} as const;
