/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { OnboardingStatusSchemaOneOf } from './onboardingStatusSchemaOneOf.ts';
import type { OnboardingStatusSchemaOneOfThree } from './onboardingStatusSchemaOneOfThree.ts';

/**
 * The current onboarding status of a project.
 */
export type OnboardingStatusSchema =
    | OnboardingStatusSchemaOneOf
    | OnboardingStatusSchemaOneOfThree;
