/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type OnboardingStatusSchemaOneOfStatus =
    (typeof OnboardingStatusSchemaOneOfStatus)[keyof typeof OnboardingStatusSchemaOneOfStatus];

export const OnboardingStatusSchemaOneOfStatus = {
    'onboarding-started': 'onboarding-started',
    'sdk-connected': 'sdk-connected',
    onboarded: 'onboarded',
} as const;
