/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type OutdatedSdksSchemaSdksItem = {
    /** An outdated SDK version identifier. Usually formatted as "unleash-client-<language>:<version>" */
    sdkVersion: string;
    /** A list of applications using the SDK version */
    applications: string[];
};
