/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */

export type PatchSchemaOp = typeof PatchSchemaOp[keyof typeof PatchSchemaOp];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchSchemaOp = {
    add: 'add',
    remove: 'remove',
    replace: 'replace',
    copy: 'copy',
    move: 'move',
} as const;
