/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { PatchSchema } from './patchSchema.js';

/**
 * A list of patches
 */
export type PatchesSchema = PatchSchema[];
