/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export interface PermissionSchema {
    permission: string;
    project?: string;
    environment?: string;
}
