/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { OnboardingStatusSchema } from './onboardingStatusSchema.ts';
import type { PersonalDashboardProjectDetailsSchemaInsights } from './personalDashboardProjectDetailsSchemaInsights.ts';
import type { PersonalDashboardProjectDetailsSchemaLatestEventsItem } from './personalDashboardProjectDetailsSchemaLatestEventsItem.ts';
import type { PersonalDashboardProjectDetailsSchemaOwners } from './personalDashboardProjectDetailsSchemaOwners.ts';
import type { PersonalDashboardProjectDetailsSchemaRolesItem } from './personalDashboardProjectDetailsSchemaRolesItem.ts';

/**
 * Project details in personal dashboard
 */
export interface PersonalDashboardProjectDetailsSchema {
    /** Insights for the project, including flag data and project health information. */
    insights: PersonalDashboardProjectDetailsSchemaInsights;
    /** The latest events for the project. */
    latestEvents: PersonalDashboardProjectDetailsSchemaLatestEventsItem[];
    onboardingStatus: OnboardingStatusSchema;
    /** The users and/or groups that have the "owner" role in this project. If no such users or groups exist, the list will contain the "system" owner instead. */
    owners: PersonalDashboardProjectDetailsSchemaOwners;
    /** The list of roles that the user has in this project. */
    roles: PersonalDashboardProjectDetailsSchemaRolesItem[];
}
