/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type PersonalDashboardSchemaAdminsItem = {
    /** The user ID. */
    id: number;
    /** The user's name. */
    name?: string;
    /** The user's username. */
    username?: string;
    imageUrl?: string;
    email?: string;
};
