/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { PersonalDashboardProjectDetailsSchemaLatestEventsItem } from './personalDashboardProjectDetailsSchemaLatestEventsItem';
import type { PersonalDashboardProjectDetailsSchemaOwners } from './personalDashboardProjectDetailsSchemaOwners';
import type { PersonalDashboardProjectDetailsSchemaRolesItem } from './personalDashboardProjectDetailsSchemaRolesItem';
import type { ProjectOverviewSchemaOnboardingStatus } from './projectOverviewSchemaOnboardingStatus';

/**
 * Project details in personal dashboard
 */
export interface PersonalDashboardProjectDetailsSchema {
    /** The latest events for the project. */
    latestEvents: PersonalDashboardProjectDetailsSchemaLatestEventsItem[];
    /** The users and/or groups that have the "owner" role in this project. If no such users or groups exist, the list will contain the "system" owner instead. */
    owners: PersonalDashboardProjectDetailsSchemaOwners;
    /**
     * The list of roles that the user has in this project.
     * @minItems 1
     */
    roles: PersonalDashboardProjectDetailsSchemaRolesItem[];
    onboardingStatus: ProjectOverviewSchemaOnboardingStatus;
}
