/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { PlaygroundStrategySchemaResultAnyOfFourVariantPayloadType } from './playgroundStrategySchemaResultAnyOfFourVariantPayloadType';

/**
 * An optional payload attached to the variant.
 */
export type PlaygroundStrategySchemaResultAnyOfFourVariantPayload = {
    /** The format of the payload. */
    type: PlaygroundStrategySchemaResultAnyOfFourVariantPayloadType;
    /** The payload value stringified. */
    value: string;
};
