/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { PlaygroundConstraintSchema } from './playgroundConstraintSchema.js';
import type { PlaygroundStrategySchemaLinks } from './playgroundStrategySchemaLinks.js';
import type { ParametersSchema } from './parametersSchema.js';
import type { PlaygroundStrategySchemaResult } from './playgroundStrategySchemaResult.js';
import type { PlaygroundSegmentSchema } from './playgroundSegmentSchema.js';

/**
 * An evaluated feature flag strategy as used by the Playground
 */
export interface PlaygroundStrategySchema {
    /** The strategy's constraints and their evaluation results. */
    constraints: PlaygroundConstraintSchema[];
    /**
     * The strategy's status. Disabled strategies are not evaluated
     * @nullable
     */
    disabled: boolean | null;
    /** The strategy's id. */
    id: string;
    /** A set of links to actions you can perform on this strategy */
    links: PlaygroundStrategySchemaLinks;
    /** The strategy's name. */
    name: string;
    /** The strategy's constraints and their evaluation results. */
    parameters: ParametersSchema;
    /** The strategy's evaluation result. If the strategy is a custom strategy that Unleash can't evaluate, `evaluationStatus` will be `unknown`. Otherwise, it will be `true` or `false` */
    result: PlaygroundStrategySchemaResult;
    /** The strategy's segments and their evaluation results. */
    segments: PlaygroundSegmentSchema[];
    /** Description of the feature's purpose. */
    title?: string;
}
