/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */
import type { PlaygroundFeatureSchemaStrategiesResult } from './playgroundFeatureSchemaStrategiesResult';
import type { PlaygroundStrategySchema } from './playgroundStrategySchema';

export type PlaygroundFeatureSchemaStrategies = {
    /** The cumulative results of all the feature's strategies. Can be `true`,
                                  `false`, or `unknown`.
                                  This property will only be `unknown`
                                  if one or more of the strategies can't be fully evaluated and the rest of the strategies
                                  all resolve to `false`. */
    result: PlaygroundFeatureSchemaStrategiesResult;
    /** The strategies that apply to this feature. */
    data: PlaygroundStrategySchema[];
};
