/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A list of projects to check for feature flags in.
 */
export type PlaygroundRequestSchemaProjects = string[] | '*';
