/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */
import type { PlaygroundStrategySchemaResultAnyOfFourEvaluationStatus } from './playgroundStrategySchemaResultAnyOfFourEvaluationStatus';

export type PlaygroundStrategySchemaResultAnyOfFour = {
    /** Signals that this strategy was evaluated successfully. */
    evaluationStatus: PlaygroundStrategySchemaResultAnyOfFourEvaluationStatus;
    /** Whether this strategy evaluates to true or not. */
    enabled: boolean;
};
