/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { FeatureSchema } from './featureSchema.js';
import type { RoleSchema } from './roleSchema.js';

/**
 * User profile overview
 */
export interface ProfileSchema {
    /** Deprecated, always returns empty array */
    features: FeatureSchema[];
    /** Which projects this user is a member of */
    projects: string[];
    rootRole: RoleSchema;
    /** Which email subscriptions this user is subscribed to */
    subscriptions: string[];
}
