/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Details about the newly created project.
 */
export interface ProjectCreatedSchema {
    /** The project's identifier. */
    id: string;
    /** The project's name. */
    name: string;
    /** The project's description. */
    description?: string | null;
}
