/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchemaOwnersOneOfItemAnyOf } from './projectSchemaOwnersOneOfItemAnyOf';
import type { ProjectSchemaOwnersOneOfItemAnyOfFive } from './projectSchemaOwnersOneOfItemAnyOfFive';

export type ProjectSchemaOwnersOneOfItem =
    | ProjectSchemaOwnersOneOfItemAnyOf
    | ProjectSchemaOwnersOneOfItemAnyOfFive;
