/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */
import type { GroupSchema } from './groupSchema';
import type { UserWithProjectRoleSchema } from './userWithProjectRoleSchema';
import type { RoleSchema } from './roleSchema';

export interface ProjectAccessSchema {
    groups: GroupSchema[];
    users: UserWithProjectRoleSchema[];
    roles: RoleSchema[];
}
