/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType } from './projectSchemaOwnersOneOfItemAnyOfThreeOwnerType.ts';

export type ProjectSchemaOwnersOneOfItemAnyOfThree = {
    name: string;
    ownerType: ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType;
};
