/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectStatusSchemaLifecycleSummaryArchived } from './projectStatusSchemaLifecycleSummaryArchived.ts';
import type { ProjectStatusSchemaLifecycleSummaryCompleted } from './projectStatusSchemaLifecycleSummaryCompleted.ts';
import type { ProjectStatusSchemaLifecycleSummaryInitial } from './projectStatusSchemaLifecycleSummaryInitial.ts';
import type { ProjectStatusSchemaLifecycleSummaryLive } from './projectStatusSchemaLifecycleSummaryLive.ts';
import type { ProjectStatusSchemaLifecycleSummaryPreLive } from './projectStatusSchemaLifecycleSummaryPreLive.ts';

/**
 * Feature flag lifecycle statistics for this project.
 */
export type ProjectStatusSchemaLifecycleSummary = {
    /** Information on archived flags in this project. */
    archived: ProjectStatusSchemaLifecycleSummaryArchived;
    /** Statistics on feature flags in a given stage in this project. */
    completed: ProjectStatusSchemaLifecycleSummaryCompleted;
    /** Statistics on feature flags in a given stage in this project. */
    initial: ProjectStatusSchemaLifecycleSummaryInitial;
    /** Statistics on feature flags in a given stage in this project. */
    live: ProjectStatusSchemaLifecycleSummaryLive;
    /** Statistics on feature flags in a given stage in this project. */
    preLive: ProjectStatusSchemaLifecycleSummaryPreLive;
};
