/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectFlagCreatorsSchemaItem } from './projectFlagCreatorsSchemaItem.js';

/**
 * A list of project flag creators
 */
export type ProjectFlagCreatorsSchema = ProjectFlagCreatorsSchemaItem[];
