/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType } from './projectSchemaOwnersOneOfItemAnyOfThreeOwnerType';

export type ProjectSchemaOwnersOneOfItemAnyOfThree = {
    ownerType: ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType;
    name: string;
};
