/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectApplicationSchema } from './projectApplicationSchema';

/**
 * A list of project applications
 */
export interface ProjectApplicationsSchema {
    /** The total number of project applications. */
    total: number;
    /** All applications defined for a specific project. */
    applications: ProjectApplicationSchema[];
}
