/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchemaOwnersOneOfItemAnyOf } from './projectSchemaOwnersOneOfItemAnyOf.ts';
import type { ProjectSchemaOwnersOneOfItemAnyOfThree } from './projectSchemaOwnersOneOfItemAnyOfThree.ts';

export type ProjectSchemaOwnersOneOfItem =
    | ProjectSchemaOwnersOneOfItemAnyOf
    | ProjectSchemaOwnersOneOfItemAnyOfThree;
