/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchemaOwnersOneOfItem } from './projectSchemaOwnersOneOfItem';
import type { ProjectSchemaOwnersOneOfSixItem } from './projectSchemaOwnersOneOfSixItem';

/**
 * The users and/or groups that have the "owner" role in this project. If no such users or groups exist, the list will contain the "system" owner instead.
 */
export type ProjectSchemaOwners =
    | ProjectSchemaOwnersOneOfItem[]
    | ProjectSchemaOwnersOneOfSixItem[];
