/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectFeatureEnvironmentSchema } from './projectFeatureEnvironmentSchema';
import type { TagSchema } from './tagSchema';

/**
 * A project feature flag definition
 */
export interface ProjectFeatureSchema {
    /** Unique feature name */
    name: string;
    /** Type of the flag e.g. experiment, kill-switch, release, operational, permission */
    type: string;
    /**
     * Detailed description of the feature
     * @nullable
     */
    description: string | null;
    /** `true` if the feature is stale based on the age and feature type, otherwise `false`. */
    stale: boolean;
    /** `true` if the feature was favorited, otherwise `false`. */
    favorite: boolean;
    /** `true` if the impression data collection is enabled for the feature, otherwise `false`. */
    impressionData: boolean;
    /** The date the feature was created */
    createdAt: string;
    /**
     * The date and time when metrics where last collected for this flag in any environment. This field was deprecated in v5. You should instead use the `lastSeenAt` property on the individual environments listed under the `environments` property.
     * @deprecated
     * @nullable
     */
    lastSeenAt: string | null;
    /** The list of environments where the feature can be used */
    environments: ProjectFeatureEnvironmentSchema[];
    /**
     * The list of feature tags
     * @nullable
     */
    tags?: TagSchema[] | null;
}
