/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */
import type { GroupSchema } from './groupSchema';
import type { RoleSchema } from './roleSchema';
import type { UserWithProjectRoleSchema } from './userWithProjectRoleSchema';

export interface ProjectAccessSchema {
    groups: GroupSchema[];
    users: UserWithProjectRoleSchema[];
    roles: RoleSchema[];
}
