/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectFeatureSchema } from './projectFeatureSchema';

/**
 * A list of features in a project
 * @deprecated
 */
export interface ProjectFeaturesSchema {
    /** A list of features */
    features: ProjectFeatureSchema[];
    /** The version of the feature's schema */
    version: number;
}
