/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ProjectSchemaOwnersOneOfSixItemOwnerType =
    (typeof ProjectSchemaOwnersOneOfSixItemOwnerType)[keyof typeof ProjectSchemaOwnersOneOfSixItemOwnerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectSchemaOwnersOneOfSixItemOwnerType = {
    system: 'system',
} as const;
