/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType =
    (typeof ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType)[keyof typeof ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectSchemaOwnersOneOfItemAnyOfThreeOwnerType = {
    group: 'group',
} as const;
