/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectOverviewSchemaOnboardingStatusOneOfThreeStatus } from './projectOverviewSchemaOnboardingStatusOneOfThreeStatus';

export type ProjectOverviewSchemaOnboardingStatusOneOfThree = {
    status: ProjectOverviewSchemaOnboardingStatusOneOfThreeStatus;
    /** The name of the feature flag */
    feature: string;
};
