/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */

export interface ProjectSchema {
    id: string;
    name: string;
    description?: string;
    health?: number;
    featureCount?: number;
    memberCount?: number;
    createdAt?: string;
    updatedAt?: string | null;
    changeRequestsEnabled?: boolean;
    favorite?: boolean;
}
