/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateFeatureStrategySchema } from './createFeatureStrategySchema.js';

/**
 * Add an environment to a project, optionally also sets if change requests are enabled for this environment on the project
 */
export interface ProjectEnvironmentSchema {
    /** Whether change requests should be enabled or for this environment on the project or not */
    changeRequestsEnabled?: boolean;
    /** A default strategy to create for this environment on the project. */
    defaultStrategy?: CreateFeatureStrategySchema;
    /** The environment to add to the project */
    environment: string;
}
