/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchema } from './projectSchema';

export interface ProjectsOverviewSchema {
    featureCount: number;
    memberCount: number;
    projects: ProjectSchema[];
}
