/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProjectSchema } from './projectSchema';

/**
 * An overview of all the projects in the Unleash instance
 */
export interface ProjectsSchema {
    /** A list of projects in the Unleash instance */
    projects: ProjectSchema[];
    /** The schema version used to represent the project data. */
    version: number;
}
