/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProxyFeatureSchemaVariantPayload } from './proxyFeatureSchemaVariantPayload';

/**
 * Variant details
 */
export type ProxyFeatureSchemaVariant = {
    /** Whether the variant is enabled or not. */
    enabled: boolean;
    /** Whether the feature is enabled or not. */
    feature_enabled?: boolean;
    /**
     * Use `feature_enabled` instead.
     * @deprecated
     */
    featureEnabled?: boolean;
    /** The variants name. Is unique for this feature toggle */
    name: string;
    /** Extra data configured for this variant */
    payload?: ProxyFeatureSchemaVariantPayload;
};
