/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */
import type { ProxyMetricsSchemaBucketTogglesVariants } from './proxyMetricsSchemaBucketTogglesVariants';

export type ProxyMetricsSchemaBucketToggles = {
    [key: string]: {
        yes?: number;
        no?: number;
        variants?: ProxyMetricsSchemaBucketTogglesVariants;
    };
};
