/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.55
 */
import type { ProxyClientSchemaStarted } from './proxyClientSchemaStarted';

export interface ProxyClientSchema {
    /** Name of the application using Unleash */
    appName: string;
    /** Instance id for this application (typically hostname, podId or similar) */
    instanceId?: string;
    /** Optional field that describes the sdk version (name:version) */
    sdkVersion?: string;
    /** @deprecated */
    environment?: string;
    /** At which interval, in milliseconds, will this client be expected to send metrics */
    interval: number;
    /** When this client started. Should be reported as ISO8601 time. */
    started: ProxyClientSchemaStarted;
    /** List of strategies implemented by this application */
    strategies: string[];
}
