/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProxyFeatureSchemaVariantPayloadType } from './proxyFeatureSchemaVariantPayloadType';

export type ProxyFeatureSchemaVariantPayload = {
    type: ProxyFeatureSchemaVariantPayloadType;
    value: string;
};
