/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.3
 */
import type { ProxyMetricsSchemaBucketToggles } from './proxyMetricsSchemaBucketToggles';

export type ProxyMetricsSchemaBucket = {
    start: string;
    stop: string;
    toggles: ProxyMetricsSchemaBucketToggles;
};
