/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The format of the payload.
 */
export type ProxyFeatureSchemaVariantPayloadType =
    (typeof ProxyFeatureSchemaVariantPayloadType)[keyof typeof ProxyFeatureSchemaVariantPayloadType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProxyFeatureSchemaVariantPayloadType = {
    json: 'json',
    csv: 'csv',
    string: 'string',
    number: 'number',
} as const;
