/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ProxyFeatureSchemaVariant } from './proxyFeatureSchemaVariant';

export interface ProxyFeatureSchema {
    name: string;
    enabled: boolean;
    impressionData: boolean;
    variant?: ProxyFeatureSchemaVariant;
}
