/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */
import type { UserSchema } from './userSchema';
import type { RoleSchema } from './roleSchema';

export interface PublicSignupTokenSchema {
    secret: string;
    /** The public signup link for the token. Users who follow this link will be taken to a signup page where they can create an Unleash user. */
    url: string;
    name: string;
    enabled: boolean;
    expiresAt: string;
    createdAt: string;
    createdBy: string | null;
    /** Array of users that have signed up using the token. */
    users?: UserSchema[] | null;
    /** Users who sign up using this token will be given this role. */
    role: RoleSchema;
}
