/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.21.0-beta.1
 */
import type { PublicSignupTokenSchema } from './publicSignupTokenSchema';

export interface PublicSignupTokensSchema {
    tokens: PublicSignupTokenSchema[];
}
