/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicSignupTokenCreateSchema
 */
export interface PublicSignupTokenCreateSchema {
    /**
     * 
     * @type {string}
     * @memberof PublicSignupTokenCreateSchema
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicSignupTokenCreateSchema
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the PublicSignupTokenCreateSchema interface.
 */
export function instanceOfPublicSignupTokenCreateSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "expiresAt" in value;

    return isInstance;
}

export function PublicSignupTokenCreateSchemaFromJSON(json: any): PublicSignupTokenCreateSchema {
    return PublicSignupTokenCreateSchemaFromJSONTyped(json, false);
}

export function PublicSignupTokenCreateSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicSignupTokenCreateSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'expiresAt': (new Date(json['expiresAt'])),
    };
}

export function PublicSignupTokenCreateSchemaToJSON(value?: PublicSignupTokenCreateSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'expiresAt': (value.expiresAt.toISOString()),
    };
}

