/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { VariantSchema } from './variantSchema';

export interface PushVariantsSchema {
    variants?: VariantSchema[];
    environments?: string[];
}
