/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { RegisterImpactMetricSchemaType } from './registerImpactMetricSchemaType';

/**
 * Describes a new impact metric to register with a zero initial value.
 */
export interface RegisterImpactMetricSchema {
    /**
     * The metric name. Must start with a letter or underscore and contain only alphanumerics, underscores or colons.
     * @pattern ^[a-zA-Z_:][a-zA-Z0-9_:]*$
     */
    name: string;
    /** The type of metric to register. */
    type: RegisterImpactMetricSchemaType;
}
