/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A field to distinguish between release plans and release templates.
 */
export type ReleasePlanSchemaDiscriminator =
    (typeof ReleasePlanSchemaDiscriminator)[keyof typeof ReleasePlanSchemaDiscriminator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReleasePlanSchemaDiscriminator = {
    plan: 'plan',
} as const;
