/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { ReleasePlanTemplateSchema } from './releasePlanTemplateSchema';

/**
 * A collection of release plan templates
 */
export type ReleasePlanTemplatesSchema = ReleasePlanTemplateSchema[];
