/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The condition configuration for the transition
 * @nullable
 */
export type ReleasePlanMilestoneSchemaTransitionCondition = {
    /**
     * The interval in minutes before transitioning
     * @minimum 1
     */
    intervalMinutes: number;
} | null;
