/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * An object describing the remote MCP server settings.
 */
export interface RemoteMcpSettingsSchema {
    /** Whether the remote MCP server is currently enabled. */
    enabled: boolean;
    /** Experimental: Whether the instance has opted in to sharing remote MCP usage feedback with Unleash. */
    feedbackOptIn?: boolean;
}
