/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A key value set representing the metric
 */
export type RequestsPerSecondSchemaDataResultItemMetric = {
    /** Name of the application this metric relates to */
    appName?: string;
    /** Which endpoint has been accessed */
    endpoint?: string;
};
