/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { RequestsPerSecondSchema } from './requestsPerSecondSchema.js';

/**
 * Get usage metrics separated by client and admin paths
 */
export interface RequestsPerSecondSegmentedSchema {
    adminMetrics?: RequestsPerSecondSchema;
    clientMetrics?: RequestsPerSecondSchema;
}
