/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */

/**
 * A key value set representing the metric
 */
export type RequestsPerSecondSchemaDataResultItemMetric = {
    appName?: string;
    endpoint?: string;
};
