/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Prometheus compatible result type.
 */
export type RequestsPerSecondSchemaDataResultType =
    (typeof RequestsPerSecondSchemaDataResultType)[keyof typeof RequestsPerSecondSchemaDataResultType];

export const RequestsPerSecondSchemaDataResultType = {
    matrix: 'matrix',
    vector: 'vector',
    scalar: 'scalar',
    string: 'string',
} as const;
