/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { RequestConsumptionSchemaItem } from './requestConsumptionSchemaItem';

export type RequestConsumptionSchema = RequestConsumptionSchemaItem[];
