/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { RequestsPerSecondSchemaDataResultType } from './requestsPerSecondSchemaDataResultType';
import type { RequestsPerSecondSchemaDataResultItem } from './requestsPerSecondSchemaDataResultItem';

/**
 * The query result from prometheus
 */
export type RequestsPerSecondSchemaData = {
    /** Prometheus compatible result type. */
    resultType?: RequestsPerSecondSchemaDataResultType;
    /** An array of values per metric. Each one represents a line in the graph labeled by its metric name */
    result?: RequestsPerSecondSchemaDataResultItem[];
};
