/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { RoleSchema } from './roleSchema';

export interface RoleWithVersionSchema {
    version: number;
    roles: RoleSchema;
}
