/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SafeguardSchemaAction } from './safeguardSchemaAction';
import type { SafeguardSchemaImpactMetric } from './safeguardSchemaImpactMetric';
import type { SafeguardTriggerConditionSchema } from './safeguardTriggerConditionSchema';

/**
 * A safeguard configuration for a release plan.
 */
export interface SafeguardSchema {
    /** The action to take when the safeguard is triggered. */
    action: SafeguardSchemaAction;
    /** The unique ULID identifier for this safeguard */
    id: string;
    /** The metric configuration used to evaluate the safeguard condition. */
    impactMetric: SafeguardSchemaImpactMetric;
    /** The condition that triggers the safeguard. */
    triggerCondition: SafeguardTriggerConditionSchema;
}
