/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SafeguardSchemaImpactMetricAggregationMode } from './safeguardSchemaImpactMetricAggregationMode';
import type { SafeguardSchemaImpactMetricLabelSelectors } from './safeguardSchemaImpactMetricLabelSelectors';
import type { SafeguardSchemaImpactMetricTimeRange } from './safeguardSchemaImpactMetricTimeRange';

/**
 * The metric configuration used to evaluate the safeguard condition.
 */
export type SafeguardSchemaImpactMetric = {
    /** The aggregation mode for the metric data. */
    aggregationMode: SafeguardSchemaImpactMetricAggregationMode;
    /** The unique identifier for this impact metric */
    id: string;
    /** The selected labels and their values for filtering the metric data. */
    labelSelectors: SafeguardSchemaImpactMetricLabelSelectors;
    /** The Prometheus metric series to query. It includes both unleash prefix and metric type and display name */
    metricName: string;
    /** The time range for the metric data. */
    timeRange: SafeguardSchemaImpactMetricTimeRange;
};
