/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The comparison operator for the threshold check.
 */
export type SafeguardSchemaTriggerConditionOperator =
    (typeof SafeguardSchemaTriggerConditionOperator)[keyof typeof SafeguardSchemaTriggerConditionOperator];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SafeguardSchemaTriggerConditionOperator = {
    '>': '>',
    '<': '<',
} as const;
