/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SamlSettingsSchemaDefaultRootRole } from './samlSettingsSchemaDefaultRootRole';

/**
 * Settings used to authenticate via SAML
 */
export interface SamlSettingsSchema {
    /** Should Unleash create users based on the emails coming back in the authentication reply from the SAML server */
    autoCreate?: boolean;
    /** The X509 certificate used to validate requests */
    certificate: string;
    /** Assign this root role to auto created users */
    defaultRootRole?: SamlSettingsSchemaDefaultRootRole;
    /** Assign this root role to auto created users. Should be a role ID and takes precedence over `defaultRootRole`. */
    defaultRootRoleId?: number;
    /** A comma separated list of email domains that Unleash will auto create user accounts for. */
    emailDomains?: string;
    /** Is SAML authentication enabled */
    enabled?: boolean;
    /** The SAML 2.0 entity ID */
    entityId: string;
    /** Which URL to use for Single Sign On */
    signOnUrl: string;
    /** Which URL to use for Single Sign Out */
    signOutUrl?: string;
    /** Signing certificate for sign out requests */
    spCertificate?: string;
}
