/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Assign this root role to auto created users
 */
export type SamlSettingsSchemaOneOfDefaultRootRole =
    (typeof SamlSettingsSchemaOneOfDefaultRootRole)[keyof typeof SamlSettingsSchemaOneOfDefaultRootRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SamlSettingsSchemaOneOfDefaultRootRole = {
    Viewer: 'Viewer',
    Editor: 'Editor',
    Admin: 'Admin',
} as const;
