/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The Unleash context with flattened properties
 */
export interface SdkFlatContextSchema {
    /** The name of the application. */
    appName: string;
    /** A DateTime (or similar) data class instance or a string in an RFC3339-compatible format. Defaults to the current time if not set by the user. */
    currentTime?: string;
    /**
     * The environment the app is running in.
     * @deprecated
     */
    environment?: string;
    /** The app's IP address */
    remoteAddress?: string;
    /** An identifier for the current session */
    sessionId?: string;
    /** An identifier for the current user */
    userId?: string;
    [key: string]: any;
}
