/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type SearchEventsParams = {
    /**
     * Find events by a free-text search query. The query will be matched against the event data payload (if any).
     */
    query?: string;
    /**
     * Filter by event ID using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([0-9]+))*$
     */
    id?: string;
    /**
     * Filter by group ID using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([0-9]+))*$
     */
    groupId?: string;
    /**
     * Filter by feature name using supported operators: IS, IS_ANY_OF
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([a-zA-Z0-9_]+))*$
     */
    feature?: string;
    /**
     * Filter by projects ID using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([a-zA-Z0-9_]+))*$
     */
    project?: string;
    /**
     * Filter by event type using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([a-zA-Z0-9_]+))*$
     */
    type?: string;
    /**
     * Filter by the ID of the event creator, using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([a-zA-Z0-9_]+))*$
     */
    createdBy?: string;
    /**
     * The starting date of the creation date range in IS:yyyy-MM-dd format
     * @pattern ^(IS):\d{4}-\d{2}-\d{2}$
     */
    from?: string;
    /**
     * The ending date of the creation date range in IS:yyyy-MM-dd format
     * @pattern ^(IS):\d{4}-\d{2}-\d{2}$
     */
    to?: string;
    /**
     * The number of features to skip when returning a page. By default it is set to 0.
     */
    offset?: string;
    /**
     * The number of feature environments to return in a page. By default it is set to 50. The maximum is 1000.
     */
    limit?: string;
    /**
     * Filter by environment name using supported operators: IS, IS_ANY_OF.
     * @pattern ^(IS|IS_ANY_OF):(.*?)(,([a-zA-Z0-9_]+))*$
     */
    environment?: string;
};
