/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type SearchChangeRequestsState =
    (typeof SearchChangeRequestsState)[keyof typeof SearchChangeRequestsState];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchChangeRequestsState = {
    'IS:open': 'IS:open',
    'IS:closed': 'IS:closed',
} as const;
