/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

export type SegmentStrategiesSchemaChangeRequestStrategiesItem = {
    /** The ID of the environment that the strategy belongs to. */
    environment: string;
    /** The name of the feature flag that this strategy belongs to. */
    featureName: string;
    /** The ID of the strategy. Not present on new strategies that haven't been added to the feature flag yet. */
    id?: string;
    /** The ID of the project that the strategy belongs to. */
    projectId: string;
    /** The name of the strategy's type. */
    strategyName: string;
};
