/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */
import type { AdminSegmentSchema } from './adminSegmentSchema';

export interface SegmentsSchema {
  segments?: AdminSegmentSchema[];
}
