/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SetExternalImpactMetricsSourceSchemaOneOf } from './setExternalImpactMetricsSourceSchemaOneOf';
import type { SetExternalImpactMetricsSourceSchemaOneOfTwo } from './setExternalImpactMetricsSourceSchemaOneOfTwo';

/**
 * Configuration for connecting to an external impact-metrics source (any Prometheus-compatible endpoint). Either disabled, or enabled with a URL.
 */
export type SetExternalImpactMetricsSourceSchema =
    | SetExternalImpactMetricsSourceSchemaOneOf
    | SetExternalImpactMetricsSourceSchemaOneOfTwo;
