/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Disabled.
 */
export type SetExternalImpactMetricsSourceSchemaOneOfTwo = {
    enabled: boolean;
};
