/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.2
 */

export type SetStrategySortOrderSchemaItem = {
    id: string;
    sortOrder: number;
};
