/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A strategy with its new sort order
 */
export type SetStrategySortOrderSchemaItem = {
    /** The ID of the strategy */
    id: string;
    /** The new sort order of the strategy */
    sortOrder: number;
};
