/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SetStrategySortOrderSchemaItem } from './setStrategySortOrderSchemaItem';

export type SetStrategySortOrderSchema = SetStrategySortOrderSchemaItem[];
