/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { SetUiConfigSchemaFrontendSettings } from './setUiConfigSchemaFrontendSettings';

/**
 * Unleash configuration settings affect the admin UI.
 */
export interface SetUiConfigSchema {
    /** Settings related to the front-end API. */
    frontendSettings?: SetUiConfigSchemaFrontendSettings;
}
