/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * An object describing the user and company signup data.
 */
export interface SignupDataSchema {
    /** Whether the company is based in North America. */
    companyIsNA?: boolean;
    /** The name of the company. */
    companyName?: string;
    /** The role of the user within the company. */
    companyRole?: string;
    /** The user's name. */
    name?: string;
    /** Whether the user has consented to receive product update emails. */
    productUpdatesEmailConsent?: boolean;
    /** Whether the user should set a password as part of the signup process. */
    shouldSetPassword?: boolean;
}
