/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SplashSchema
 */
export interface SplashSchema {
    /**
     * 
     * @type {number}
     * @memberof SplashSchema
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof SplashSchema
     */
    splashId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SplashSchema
     */
    seen: boolean;
}

/**
 * Check if a given object implements the SplashSchema interface.
 */
export function instanceOfSplashSchema(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "splashId" in value;
    isInstance = isInstance && "seen" in value;

    return isInstance;
}

export function SplashSchemaFromJSON(json: any): SplashSchema {
    return SplashSchemaFromJSONTyped(json, false);
}

export function SplashSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SplashSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'splashId': json['splashId'],
        'seen': json['seen'],
    };
}

export function SplashSchemaToJSON(value?: SplashSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'splashId': value.splashId,
        'seen': value.seen,
    };
}

