/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The type of the value. Commonly used types are string, json and csv.
 */
export type StrategyVariantSchemaPayloadType =
    typeof StrategyVariantSchemaPayloadType[keyof typeof StrategyVariantSchemaPayloadType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StrategyVariantSchemaPayloadType = {
    json: 'json',
    csv: 'csv',
    string: 'string',
} as const;
