/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { StrategySchemaParametersItem } from './strategySchemaParametersItem';

export interface StrategySchema {
    name: string;
    displayName: string | null;
    description: string;
    editable: boolean;
    deprecated: boolean;
    parameters: StrategySchemaParametersItem[];
}
