/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Representation of a [tag](https://docs.getunleash.io/reference/tags)
 */
export interface TagSchema {
    /** The value of the tag */
    value: string;
    /** The [type](https://docs.getunleash.io/reference/tags#tag-types) of the tag */
    type: string;
}
