/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Contains information about which settings are configured for version info collection and feature usage collection.
 */
export interface TelemetrySettingsSchema {
    /** Whether collection of feature usage metrics is enabled/active. */
    featureInfoCollectionEnabled: boolean;
    /** Whether collection of version info is enabled/active. */
    versionInfoCollectionEnabled: boolean;
}
