/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Input data required for the action
 */
export interface ToggleFeatureActionSchema {
    /** The environment we want to target */
    environment: string;
    /** The name of the feature we want to target */
    featureName: string;
    /** The project where the feature is located */
    project: string;
}
