/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Whether the data is aggregated by month or by day.
 */
export type TrafficUsageDataSegmentedCombinedSchemaGrouping =
    (typeof TrafficUsageDataSegmentedCombinedSchemaGrouping)[keyof typeof TrafficUsageDataSegmentedCombinedSchemaGrouping];

export const TrafficUsageDataSegmentedCombinedSchemaGrouping = {
    monthly: 'monthly',
    daily: 'daily',
} as const;
