/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { TrafficUsageApiMonthlyDataSchemaMonthsItemTrafficTypesItem } from './trafficUsageApiMonthlyDataSchemaMonthsItemTrafficTypesItem.js';

export type TrafficUsageApiMonthlyDataSchemaMonthsItem = {
    /**
     * The month this data usage is recorded for
     * @pattern ^[0-9]{4}-[0-9]{2}$
     */
    month: string;
    /** Contains the recorded data usage for each type of traffic group */
    trafficTypes: TrafficUsageApiMonthlyDataSchemaMonthsItemTrafficTypesItem[];
};
