/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * A transition condition for milestone progression
 */
export interface TransitionConditionSchema {
    /**
     * The interval in minutes before transitioning
     * @minimum 1
     */
    intervalMinutes: number;
}
