/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { TransitionConditionSchemaOneOf } from './transitionConditionSchemaOneOf.ts';
import type { TransitionConditionSchemaOneOfThree } from './transitionConditionSchemaOneOfThree.ts';

/**
 * A transition condition for milestone progression
 */
export type TransitionConditionSchema =
    | TransitionConditionSchemaOneOf
    | TransitionConditionSchemaOneOfThree;
