/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { CreateFeatureNamingPatternSchema } from './createFeatureNamingPatternSchema.js';
import type { ProjectLinkTemplateSchema } from './projectLinkTemplateSchema.js';
import type { UpdateProjectEnterpriseSettingsSchemaMode } from './updateProjectEnterpriseSettingsSchemaMode.js';

/**
 * Data used to update a [project](https://docs.getunleash.io/concepts/projects) settings
 */
export interface UpdateProjectEnterpriseSettingsSchema {
    featureNaming?: CreateFeatureNamingPatternSchema;
    /** A list of link templates that can be automatically added to new feature flags. */
    linkTemplates?: ProjectLinkTemplateSchema[];
    /** A mode of the project affecting what actions are possible in this project */
    mode?: UpdateProjectEnterpriseSettingsSchemaMode;
}
