/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserSchema
 */
export interface UpdateUserSchema {
    [key: string]: any | any;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserSchema
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserSchema
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateUserSchema
     */
    rootRole?: number;
}

/**
 * Check if a given object implements the UpdateUserSchema interface.
 */
export function instanceOfUpdateUserSchema(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserSchemaFromJSON(json: any): UpdateUserSchema {
    return UpdateUserSchemaFromJSONTyped(json, false);
}

export function UpdateUserSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserSchema {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
            ...json,
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'rootRole': !exists(json, 'rootRole') ? undefined : json['rootRole'],
    };
}

export function UpdateUserSchemaToJSON(value?: UpdateUserSchema | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
            ...value,
        'email': value.email,
        'name': value.name,
        'rootRole': value.rootRole,
    };
}

