/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */

export type UpsertStrategySchemaParametersItem = {
    name?: string;
    type?: string;
    description?: string;
    required?: boolean;
};
