/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */

export interface UserWithProjectRoleSchema {
    isAPI: boolean;
    name?: string;
    email?: string | null;
    id: number;
    imageUrl?: string | null;
    addedAt?: string;
    roleId?: number;
}
