/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { UserSchema } from './userSchema';

/**
 * A list of users
 */
export type UsersSearchSchema = UserSchema[];
