/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import type { UserAccessOverviewSchemaProjectRolesItemPermissionsItem } from './userAccessOverviewSchemaProjectRolesItemPermissionsItem';

export type UserAccessOverviewSchemaProjectRolesItem = {
    /** A more detailed description of the role and what use it's intended for */
    description?: string;
    /**
     * The role id
     * @minimum 0
     */
    id: number;
    /** The name of the role */
    name: string;
    /** The permissions that this role has */
    permissions: UserAccessOverviewSchemaProjectRolesItemPermissionsItem[];
    /**
     * What project the role belongs to
     * @nullable
     */
    project?: string | null;
    /** A role can either be a global root role (applies to all projects) or a project role */
    type: string;
};
