/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.19.1
 */
import type { UserSchema } from './userSchema';

export type UsersSearchSchema = UserSchema[];
