/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * The high-level device type the session was started from, derived from the User-Agent. May be null when unknown or not captured.
 * @nullable
 */
export type UserSessionSchemaDeviceType =
    | (typeof UserSessionSchemaDeviceType)[keyof typeof UserSessionSchemaDeviceType]
    | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserSessionSchemaDeviceType = {
    desktop: 'desktop',
    mobile: 'mobile',
    tablet: 'tablet',
} as const;
