/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Data used to validate a feature toggle's name.
 */
export interface ValidateFeatureSchema {
    /** The feature name to validate. */
    name: string;
}
