/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */

/**
 * Data used to validate a project ID
 */
export interface ValidateProjectSchema {
    /** The project ID to validate */
    id: string;
}
