/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.1
 */
import type { VersionSchemaCurrent } from './versionSchemaCurrent';
import type { VersionSchemaLatest } from './versionSchemaLatest';

export interface VersionSchema {
    current: VersionSchemaCurrent;
    latest: VersionSchemaLatest;
    isLatest: boolean;
    instanceId: string;
}
