import Ajv, { Schema } from 'ajv';
import { schemas } from '.';

const ajv = new Ajv();

type SchemaNames = keyof typeof schemas;
type Rule = {
    name: string;
    match?: (
        schemaName: string,
        schema: typeof schemas[SchemaNames],
    ) => boolean;
    metaSchema: Schema;
    knownExceptions?: string[];
};

const metaRules: Rule[] = [
    {
        name: 'should have a type',
        metaSchema: {
            type: 'object',
            properties: {
                type: { type: 'string', enum: ['object', 'array'] },
            },
            required: ['type'],
        },
        knownExceptions: ['dateSchema'],
    },
    {
        name: 'should have an $id with the expected format',
        metaSchema: {
            type: 'object',
            properties: {
                $id: {
                    type: 'string',
                    pattern: '^#/components/schemas/[a-z][a-zA-Z]+$',
                },
            },
            required: ['$id'],
        },
    },
    {
        name: 'should have a description',
        metaSchema: {
            type: 'object',
            properties: {
                description: { type: 'string' },
            },
            required: ['description'],
        },
        knownExceptions: [
            'adminFeaturesQuerySchema',
            'addonParameterSchema',
            'addonSchema',
            'addonsSchema',
            'addonTypeSchema',
            'apiTokenSchema',
            'apiTokensSchema',
            'applicationSchema',
            'applicationsSchema',
            'batchFeaturesSchema',
            'batchStaleSchema',
            'bulkRegistrationSchema',
            'bulkMetricsSchema',
            'changePasswordSchema',
            'clientApplicationSchema',
            'clientFeatureSchema',
            'clientFeaturesQuerySchema',
            'clientFeaturesSchema',
            'clientMetricsSchema',
            'clientMetricsEnvSchema',
            'cloneFeatureSchema',
            'contextFieldSchema',
            'contextFieldsSchema',
            'createApiTokenSchema',
            'createFeatureSchema',
            'createFeatureStrategySchema',
            'createInvitedUserSchema',
            'createUserSchema',
            'dateSchema',
            'edgeTokenSchema',
            'emailSchema',
            'environmentsSchema',
            'eventSchema',
            'eventsSchema',
            'exportResultSchema',
            'exportQuerySchema',
            'featureEnvironmentMetricsSchema',
            'featureEventsSchema',
            'featureMetricsSchema',
            'featureSchema',
            'featuresSchema',
            'featureStrategySchema',
            'featureStrategySegmentSchema',
            'featureTagSchema',
            'featureTypeSchema',
            'featureTypesSchema',
            'featureUsageSchema',
            'featureVariantsSchema',
            'feedbackSchema',
            'groupSchema',
            'groupsSchema',
            'groupUserModelSchema',
            'healthCheckSchema',
            'healthOverviewSchema',
            'healthReportSchema',
            'idSchema',
            'instanceAdminStatsSchema',
            'legalValueSchema',
            'loginSchema',
            'maintenanceSchema',
            'toggleMaintenanceSchema',
            'meSchema',
            'nameSchema',
            'overrideSchema',
            'parametersSchema',
            'passwordSchema',
            'patchesSchema',
            'patchSchema',
            'patSchema',
            'patsSchema',
            'permissionSchema',
            'playgroundSegmentSchema',
            'playgroundStrategySchema',
            'profileSchema',
            'projectEnvironmentSchema',
            'proxyClientSchema',
            'proxyFeatureSchema',
            'proxyFeaturesSchema',
            'publicSignupTokenCreateSchema',
            'publicSignupTokenSchema',
            'publicSignupTokensSchema',
            'publicSignupTokenUpdateSchema',
            'pushVariantsSchema',
            'resetPasswordSchema',
            'requestsPerSecondSchema',
            'requestsPerSecondSegmentedSchema',
            'roleSchema',
            'segmentSchema',
            'setStrategySortOrderSchema',
            'setUiConfigSchema',
            'sortOrderSchema',
            'splashSchema',
            'stateSchema',
            'strategiesSchema',
            'strategySchema',
            'tagsBulkAddSchema',
            'tagSchema',
            'tagsSchema',
            'tagTypeSchema',
            'tagTypesSchema',
            'tagWithVersionSchema',
            'tokenUserSchema',
            'uiConfigSchema',
            'updateApiTokenSchema',
            'updateFeatureSchema',
            'updateFeatureStrategySchema',
            'updateTagTypeSchema',
            'updateUserSchema',
            'updateTagsSchema',
            'upsertContextFieldSchema',
            'upsertSegmentSchema',
            'upsertStrategySchema',
            'userSchema',
            'usersGroupsBaseSchema',
            'usersSchema',
            'usersSearchSchema',
            'validateEdgeTokensSchema',
            'validatePasswordSchema',
            'validateTagTypeSchema',
            'variantSchema',
            'variantsSchema',
            'versionSchema',
            'importTogglesSchema',
            'importTogglesValidateSchema',
            'importTogglesValidateItemSchema',
        ],
    },
    {
        name: 'should have properties with examples and descriptions',
        match: (schemaName, schema) => {
            return 'properties' in schema;
        },
        metaSchema: {
            type: 'object',
            properties: {
                // properties of the meta schema
                properties: {
                    // schema should have properties
                    type: 'object', // of type object
                    properties: {
                        // with properties
                        example: { type: 'string' }, // with example of type string
                        description: { type: 'string' }, // with description of type string
                    },
                    required: ['example', 'description'], // and both example and description are required
                },
            },
            required: ['properties'],
        },
        knownExceptions: [
            'adminFeaturesQuerySchema',
            'addonParameterSchema',
            'addonSchema',
            'addonsSchema',
            'addonTypeSchema',
            'apiTokenSchema',
            'apiTokensSchema',
            'applicationSchema',
            'applicationsSchema',
            'batchFeaturesSchema',
            'batchStaleSchema',
            'bulkRegistrationSchema',
            'bulkMetricsSchema',
            'changePasswordSchema',
            'clientApplicationSchema',
            'clientFeatureSchema',
            'clientFeaturesQuerySchema',
            'clientFeaturesSchema',
            'clientMetricsSchema',
            'clientMetricsEnvSchema',
            'cloneFeatureSchema',
            'constraintSchema',
            'contextFieldSchema',
            'createApiTokenSchema',
            'createFeatureSchema',
            'createFeatureStrategySchema',
            'createInvitedUserSchema',
            'createUserSchema',
            'edgeTokenSchema',
            'emailSchema',
            'environmentSchema',
            'environmentProjectSchema',
            'environmentsSchema',
            'environmentsProjectSchema',
            'eventSchema',
            'eventsSchema',
            'exportResultSchema',
            'exportQuerySchema',
            'featureEnvironmentMetricsSchema',
            'featureEnvironmentSchema',
            'featureEventsSchema',
            'featureMetricsSchema',
            'featureSchema',
            'featuresSchema',
            'featureStrategySchema',
            'featureStrategySegmentSchema',
            'featureTagSchema',
            'featureTypeSchema',
            'featureTypesSchema',
            'featureUsageSchema',
            'featureVariantsSchema',
            'feedbackSchema',
            'groupSchema',
            'groupsSchema',
            'groupUserModelSchema',
            'healthCheckSchema',
            'healthOverviewSchema',
            'healthReportSchema',
            'idSchema',
            'instanceAdminStatsSchema',
            'legalValueSchema',
            'loginSchema',
            'maintenanceSchema',
            'toggleMaintenanceSchema',
            'meSchema',
            'nameSchema',
            'overrideSchema',
            'passwordSchema',
            'patchSchema',
            'patSchema',
            'patsSchema',
            'permissionSchema',
            'playgroundConstraintSchema',
            'playgroundFeatureSchema',
            'playgroundRequestSchema',
            'playgroundResponseSchema',
            'playgroundSegmentSchema',
            'playgroundStrategySchema',
            'profileSchema',
            'projectEnvironmentSchema',
            'projectSchema',
            'projectsSchema',
            'proxyClientSchema',
            'proxyFeatureSchema',
            'proxyFeaturesSchema',
            'publicSignupTokenCreateSchema',
            'publicSignupTokenSchema',
            'publicSignupTokensSchema',
            'publicSignupTokenUpdateSchema',
            'pushVariantsSchema',
            'projectStatsSchema',
            'resetPasswordSchema',
            'requestsPerSecondSchema',
            'requestsPerSecondSegmentedSchema',
            'roleSchema',
            'sdkContextSchema',
            'searchEventsSchema',
            'segmentSchema',
            'setUiConfigSchema',
            'splashSchema',
            'stateSchema',
            'strategiesSchema',
            'strategySchema',
            'tagsBulkAddSchema',
            'tagSchema',
            'tagsSchema',
            'tagTypeSchema',
            'tagTypesSchema',
            'tagWithVersionSchema',
            'tokenUserSchema',
            'uiConfigSchema',
            'updateApiTokenSchema',
            'updateFeatureSchema',
            'updateFeatureStrategySchema',
            'updateTagTypeSchema',
            'updateUserSchema',
            'updateTagsSchema',
            'upsertContextFieldSchema',
            'upsertSegmentSchema',
            'upsertStrategySchema',
            'userSchema',
            'usersGroupsBaseSchema',
            'usersSchema',
            'validateEdgeTokensSchema',
            'validatePasswordSchema',
            'validateTagTypeSchema',
            'variantSchema',
            'versionSchema',
            'projectOverviewSchema',
            'importTogglesSchema',
            'importTogglesValidateSchema',
            'importTogglesValidateItemSchema',
        ],
    },
];

describe.each(metaRules)('OpenAPI schemas $name', (rule) => {
    const validateMetaSchema = ajv.compile(rule.metaSchema);

    // test all schemas agaisnt the rule
    Object.entries(schemas).forEach(([schemaName, schema]) => {
        if (!rule.match || rule.match(schemaName, schema)) {
            it(`${schemaName}`, () => {
                validateMetaSchema(schema);

                // note: whenever you resolve an exception please remove it from the list
                if (rule.knownExceptions?.includes(schemaName)) {
                    console.warn(
                        `${schemaName} is a known exception to rule "${rule.name}" that should be fixed`,
                    );
                    expect(validateMetaSchema.errors).not.toBeNull();
                } else {
                    expect(validateMetaSchema.errors).toBeNull();
                }
            });
        }
    });
});
