/* tslint:disable */
/* eslint-disable */
/**
 * Unleash API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.15.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ValidateEdgeTokensSchema,
} from '../models';
import {
    ValidateEdgeTokensSchemaFromJSON,
    ValidateEdgeTokensSchemaToJSON,
} from '../models';

export interface GetValidTokensRequest {
    validateEdgeTokensSchema: ValidateEdgeTokensSchema;
}

/**
 * 
 */
export class EdgeApi extends runtime.BaseAPI {

    /**
     */
    async getValidTokensRaw(requestParameters: GetValidTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ValidateEdgeTokensSchema>> {
        if (requestParameters.validateEdgeTokensSchema === null || requestParameters.validateEdgeTokensSchema === undefined) {
            throw new runtime.RequiredError('validateEdgeTokensSchema','Required parameter requestParameters.validateEdgeTokensSchema was null or undefined when calling getValidTokens.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // apiKey authentication
        }

        const response = await this.request({
            path: `/edge/validate`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ValidateEdgeTokensSchemaToJSON(requestParameters.validateEdgeTokensSchema),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ValidateEdgeTokensSchemaFromJSON(jsonValue));
    }

    /**
     */
    async getValidTokens(requestParameters: GetValidTokensRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ValidateEdgeTokensSchema> {
        const response = await this.getValidTokensRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
