/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.2
 */
import useSwr from 'swr';
import type { SWRConfiguration, Key } from 'swr';
import type {
    ProjectsSchema,
    ProjectCreatedSchema,
    CreateProjectSchema,
    ValidateProjectSchema,
    UpdateProjectSchema,
    HealthOverviewSchema,
    ProjectUsers,
    ProjectAccessSchema,
    ProjectEnvironmentSchema,
    HealthReportSchema,
} from '../models';
import { fetcher } from '../fetcher';
import type { ErrorType, BodyType } from '../fetcher';

export const getProjects = () => {
    return fetcher<ProjectsSchema>({
        url: `/api/admin/projects`,
        method: 'get',
    });
};

export const getGetProjectsKey = () => [`/api/admin/projects`];

export type GetProjectsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjects>>
>;
export type GetProjectsQueryError = ErrorType<unknown>;

export const useGetProjects = <TError = ErrorType<unknown>>(options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getProjects>>, TError> & {
        swrKey?: Key;
        enabled?: boolean;
    };
}) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false;
    const swrKey =
        swrOptions?.swrKey ?? (() => (isEnabled ? getGetProjectsKey() : null));
    const swrFn = () => getProjects();

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

export const createProject = (
    createProjectSchema: BodyType<CreateProjectSchema>
) => {
    return fetcher<ProjectCreatedSchema>({
        url: `/api/admin/projects`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: createProjectSchema,
    });
};

export const validateProject = (
    validateProjectSchema: BodyType<ValidateProjectSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/projects/validate`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: validateProjectSchema,
    });
};

export const updateProject = (
    projectId: string,
    updateProjectSchema: BodyType<UpdateProjectSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}`,
        method: 'put',
        headers: { 'Content-Type': 'application/json' },
        data: updateProjectSchema,
    });
};

export const deleteProject = (projectId: string) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}`,
        method: 'delete',
    });
};

export const getProjectHealthOverview = (projectId: string) => {
    return fetcher<HealthOverviewSchema>({
        url: `/api/admin/projects/${projectId}`,
        method: 'get',
    });
};

export const getGetProjectHealthOverviewKey = (projectId: string) => [
    `/api/admin/projects/${projectId}`,
];

export type GetProjectHealthOverviewQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjectHealthOverview>>
>;
export type GetProjectHealthOverviewQueryError = ErrorType<unknown>;

export const useGetProjectHealthOverview = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getProjectHealthOverview>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetProjectHealthOverviewKey(projectId) : null));
    const swrFn = () => getProjectHealthOverview(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * @deprecated
 */
export const getProjectUsers = (projectId: string) => {
    return fetcher<ProjectUsers>({
        url: `/api/admin/projects/${projectId}/users`,
        method: 'get',
    });
};

export const getGetProjectUsersKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/users`,
];

export type GetProjectUsersQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjectUsers>>
>;
export type GetProjectUsersQueryError = ErrorType<unknown>;

export const useGetProjectUsers = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getProjectUsers>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetProjectUsersKey(projectId) : null));
    const swrFn = () => getProjectUsers(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

export const getProjectAccess = (projectId: string) => {
    return fetcher<ProjectAccessSchema>({
        url: `/api/admin/projects/${projectId}/access`,
        method: 'get',
    });
};

export const getGetProjectAccessKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/access`,
];

export type GetProjectAccessQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjectAccess>>
>;
export type GetProjectAccessQueryError = ErrorType<unknown>;

export const useGetProjectAccess = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getProjectAccess>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetProjectAccessKey(projectId) : null));
    const swrFn = () => getProjectAccess(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

export const addRoleToUser = (
    projectId: string,
    userId: string,
    roleId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/users/${userId}/roles/${roleId}`,
        method: 'post',
    });
};

export const removeRoleForUser = (
    projectId: string,
    userId: string,
    roleId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/users/${userId}/roles/${roleId}`,
        method: 'delete',
    });
};

export const changeRoleForUser = (
    projectId: string,
    userId: string,
    roleId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/users/${userId}/roles/${roleId}`,
        method: 'put',
    });
};

export const changeRoleForGroup = (
    projectId: string,
    groupId: string,
    roleId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/groups/${groupId}/roles/${roleId}`,
        method: 'put',
    });
};

export const removeRoleFromGroup = (
    projectId: string,
    groupId: string,
    roleId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/groups/${groupId}/roles/${roleId}`,
        method: 'delete',
    });
};

export const addAccessToProject = (projectId: string, roleId: string) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/role/${roleId}/access`,
        method: 'post',
    });
};

export const addEnvironmentToProject = (
    projectId: string,
    projectEnvironmentSchema: BodyType<ProjectEnvironmentSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/environments`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: projectEnvironmentSchema,
    });
};

export const removeEnvironmentFromProject = (
    projectId: string,
    environment: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/environments/${environment}`,
        method: 'delete',
    });
};

export const getProjectHealthReport = (projectId: string) => {
    return fetcher<HealthReportSchema>({
        url: `/api/admin/projects/${projectId}/health-report`,
        method: 'get',
    });
};

export const getGetProjectHealthReportKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/health-report`,
];

export type GetProjectHealthReportQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjectHealthReport>>
>;
export type GetProjectHealthReportQueryError = ErrorType<unknown>;

export const useGetProjectHealthReport = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getProjectHealthReport>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetProjectHealthReportKey(projectId) : null));
    const swrFn = () => getProjectHealthReport(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};
