/**
 * Generated by Orval
 * Do not edit manually.
 * See `gen:api` script in package.json
 */
import useSwr from 'swr';
import type { SWRConfiguration, Key } from 'swr';
import type {
    NameSchema,
    SegmentsSchema,
    AdminStrategiesSchema,
    AdminSegmentSchema,
    GetSegment404,
    UpsertSegmentSchema,
} from '../models';
import { fetcher } from '../fetcher';
import type { ErrorType, BodyType } from '../fetcher';

/**
 * Uses the name provided in the body of the request to validate if the given name exists or not
 * @summary Validates if a segment name exists
 */
export const validateSegment = (nameSchema: BodyType<NameSchema>) => {
    return fetcher<void>({
        url: `/api/admin/segments/validate`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: nameSchema,
    });
};

/**
 * Retrieve all segments that are referenced by the specified strategy. Returns an empty list of segments if the strategy ID doesn't exist.
 * @summary Get strategy segments
 */
export const getSegmentsByStrategyId = (strategyId: string) => {
    return fetcher<SegmentsSchema>({
        url: `/api/admin/segments/strategies/${strategyId}`,
        method: 'get',
    });
};

export const getGetSegmentsByStrategyIdKey = (strategyId: string) =>
    [`/api/admin/segments/strategies/${strategyId}`] as const;

export type GetSegmentsByStrategyIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSegmentsByStrategyId>>
>;
export type GetSegmentsByStrategyIdQueryError = ErrorType<unknown>;

/**
 * @summary Get strategy segments
 */
export const useGetSegmentsByStrategyId = <TError = ErrorType<unknown>>(
    strategyId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getSegmentsByStrategyId>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!strategyId;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetSegmentsByStrategyIdKey(strategyId) : null));
    const swrFn = () => getSegmentsByStrategyId(strategyId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Retrieve all strategies that reference the specified segment.
 * @summary Get strategies that reference segment
 */
export const getStrategiesBySegmentId = (id: string) => {
    return fetcher<AdminStrategiesSchema>({
        url: `/api/admin/segments/${id}/strategies`,
        method: 'get',
    });
};

export const getGetStrategiesBySegmentIdKey = (id: string) =>
    [`/api/admin/segments/${id}/strategies`] as const;

export type GetStrategiesBySegmentIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getStrategiesBySegmentId>>
>;
export type GetStrategiesBySegmentIdQueryError = ErrorType<unknown>;

/**
 * @summary Get strategies that reference segment
 */
export const useGetStrategiesBySegmentId = <TError = ErrorType<unknown>>(
    id: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getStrategiesBySegmentId>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!id;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetStrategiesBySegmentIdKey(id) : null));
    const swrFn = () => getStrategiesBySegmentId(id);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Deletes a segment by its id, if not found returns a 409 error
 * @summary Deletes a segment by id
 */
export const removeSegment = (id: string) => {
    return fetcher<void>({
        url: `/api/admin/segments/${id}`,
        method: 'delete',
    });
};

/**
 * Updates the content of the segment with the provided payload. Any fields not specified will be left untouched.
 * @summary Update segment by id
 */
export const updateSegment = (id: string) => {
    return fetcher<void>({ url: `/api/admin/segments/${id}`, method: 'put' });
};

/**
 * Retrieves a segment based on its ID.
 * @summary Get a segment
 */
export const getSegment = (id: string) => {
    return fetcher<AdminSegmentSchema>({
        url: `/api/admin/segments/${id}`,
        method: 'get',
    });
};

export const getGetSegmentKey = (id: string) =>
    [`/api/admin/segments/${id}`] as const;

export type GetSegmentQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSegment>>
>;
export type GetSegmentQueryError = ErrorType<GetSegment404>;

/**
 * @summary Get a segment
 */
export const useGetSegment = <TError = ErrorType<GetSegment404>>(
    id: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getSegment>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!id;
    const swrKey =
        swrOptions?.swrKey ?? (() => (isEnabled ? getGetSegmentKey(id) : null));
    const swrFn = () => getSegment(id);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Creates a new segment using the payload provided
 * @summary Create a new segment
 */
export const createSegment = (
    upsertSegmentSchema: BodyType<UpsertSegmentSchema>
) => {
    return fetcher<AdminSegmentSchema>({
        url: `/api/admin/segments`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: upsertSegmentSchema,
    });
};

/**
 * Retrieves all segments that exist in this Unleash instance.
 * @summary Get all segments
 */
export const getSegments = () => {
    return fetcher<SegmentsSchema>({
        url: `/api/admin/segments`,
        method: 'get',
    });
};

export const getGetSegmentsKey = () => [`/api/admin/segments`] as const;

export type GetSegmentsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getSegments>>
>;
export type GetSegmentsQueryError = ErrorType<unknown>;

/**
 * @summary Get all segments
 */
export const useGetSegments = <TError = ErrorType<unknown>>(options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getSegments>>, TError> & {
        swrKey?: Key;
        enabled?: boolean;
    };
}) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false;
    const swrKey =
        swrOptions?.swrKey ?? (() => (isEnabled ? getGetSegmentsKey() : null));
    const swrFn = () => getSegments();

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};
