/**
 * Generated by orval v6.10.3 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.20.0-beta.2
 */
import type { ExportResultSchema, ExportQuerySchema } from '../models';
import { fetcher } from '../fetcher';
import type { BodyType } from '../fetcher';

export const exportFeatures = (
    exportQuerySchema: BodyType<ExportQuerySchema>
) => {
    return fetcher<ExportResultSchema>({
        url: `/api/admin/features-batch/export`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: exportQuerySchema,
    });
};
