/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * Unleash API
 * OpenAPI spec version: 4.22.0-beta.45
 */
import useSwr from 'swr';
import type { SWRConfiguration, Key } from 'swr';
import type {
    ChangeRequestSchema,
    ChangeRequestCreateSchema,
    ChangeRequestsSchema,
    ChangeRequestConfigSchema,
    UpdateChangeRequestEnvironmentConfigSchema,
    ChangeRequestStateSchema,
    ChangeRequestAddCommentSchema,
    ExportResultSchema,
    ExportQuerySchema,
    ImportTogglesValidateSchema,
    ImportTogglesSchema,
    NotificationsSchema,
    MarkNotificationsAsReadSchema,
    LoginHistorySchema,
} from '../models';
import { fetcher } from '../fetcher';
import type { ErrorType, BodyType } from '../fetcher';

/**
 * Given a change request exists, this endpoint will attempt to add a change to
                         an existing change request for the user. If a change request does not exist.
                         It will attempt to create it.
 * @summary Create/Add change to a change request
 */
export const changeRequest = (
    projectId: string,
    environment: string,
    changeRequestCreateSchema: BodyType<ChangeRequestCreateSchema>
) => {
    return fetcher<ChangeRequestSchema>({
        url: `/api/admin/projects/${projectId}/environments/${environment}/change-requests`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: changeRequestCreateSchema,
    });
};

/**
 * This endpoint will retrieve all change requests in a given environment for a given project.
 * @summary Retrieves all change requests for an environment in a project
 */
export const getChangeRequestsForEnvironment = (
    projectId: string,
    environment: string
) => {
    return fetcher<ChangeRequestsSchema>({
        url: `/api/admin/projects/${projectId}/environments/${environment}/change-requests`,
        method: 'get',
    });
};

export const getGetChangeRequestsForEnvironmentKey = (
    projectId: string,
    environment: string
) => [
    `/api/admin/projects/${projectId}/environments/${environment}/change-requests`,
];

export type GetChangeRequestsForEnvironmentQueryResult = NonNullable<
    Awaited<ReturnType<typeof getChangeRequestsForEnvironment>>
>;
export type GetChangeRequestsForEnvironmentQueryError = ErrorType<unknown>;

export const useGetChangeRequestsForEnvironment = <TError = ErrorType<unknown>>(
    projectId: string,
    environment: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getChangeRequestsForEnvironment>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled =
        swrOptions?.enabled !== false && !!(projectId && environment);
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled
                ? getGetChangeRequestsForEnvironmentKey(projectId, environment)
                : null);
    const swrFn = () => getChangeRequestsForEnvironment(projectId, environment);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Given a projectId, this endpoint will retrieve change request configuration for the project
 * @summary Retrieves change request configuration for a project
 */
export const getProjectChangeRequestConfig = (projectId: string) => {
    return fetcher<ChangeRequestConfigSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/config`,
        method: 'get',
    });
};

export const getGetProjectChangeRequestConfigKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/change-requests/config`,
];

export type GetProjectChangeRequestConfigQueryResult = NonNullable<
    Awaited<ReturnType<typeof getProjectChangeRequestConfig>>
>;
export type GetProjectChangeRequestConfigQueryError = ErrorType<unknown>;

export const useGetProjectChangeRequestConfig = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getProjectChangeRequestConfig>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled ? getGetProjectChangeRequestConfigKey(projectId) : null);
    const swrFn = () => getProjectChangeRequestConfig(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will change the change request             configuration for a given environment, set it to either on/off and optionally configure the number of approvals needed.
 * @summary Updates change request configuration for an environment in the project
 */
export const updateProjectChangeRequestConfig = (
    projectId: string,
    environment: string,
    updateChangeRequestEnvironmentConfigSchema: BodyType<UpdateChangeRequestEnvironmentConfigSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/environments/${environment}/change-requests/config`,
        method: 'put',
        headers: { 'Content-Type': 'application/json' },
        data: updateChangeRequestEnvironmentConfigSchema,
    });
};

/**
 * This endpoint will retrieve the pending change requests in the configured environments for the project, for the current user performing the request.
 * @summary Retrieves pending change requests in configured environments
 */
export const getOpenChangeRequestsForUser = (projectId: string) => {
    return fetcher<ChangeRequestsSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/open`,
        method: 'get',
    });
};

export const getGetOpenChangeRequestsForUserKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/change-requests/open`,
];

export type GetOpenChangeRequestsForUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof getOpenChangeRequestsForUser>>
>;
export type GetOpenChangeRequestsForUserQueryError = ErrorType<unknown>;

export const useGetOpenChangeRequestsForUser = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getOpenChangeRequestsForUser>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled ? getGetOpenChangeRequestsForUserKey(projectId) : null);
    const swrFn = () => getOpenChangeRequestsForUser(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will retrieve the pending change requests in the configured environments for the project, for the current user performing the request.
 * @summary Retrieves pending change requests in configured environments
 */
export const getPendingChangeRequestsForUser = (projectId: string) => {
    return fetcher<ChangeRequestsSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/pending`,
        method: 'get',
    });
};

export const getGetPendingChangeRequestsForUserKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/change-requests/pending`,
];

export type GetPendingChangeRequestsForUserQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPendingChangeRequestsForUser>>
>;
export type GetPendingChangeRequestsForUserQueryError = ErrorType<unknown>;

export const useGetPendingChangeRequestsForUser = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getPendingChangeRequestsForUser>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled
                ? getGetPendingChangeRequestsForUserKey(projectId)
                : null);
    const swrFn = () => getPendingChangeRequestsForUser(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will retrieve all change requests regardless of status for a given project.
 * @summary Retrieves all change requests for a project
 */
export const getChangeRequestsForProject = (projectId: string) => {
    return fetcher<ChangeRequestsSchema>({
        url: `/api/admin/projects/${projectId}/change-requests`,
        method: 'get',
    });
};

export const getGetChangeRequestsForProjectKey = (projectId: string) => [
    `/api/admin/projects/${projectId}/change-requests`,
];

export type GetChangeRequestsForProjectQueryResult = NonNullable<
    Awaited<ReturnType<typeof getChangeRequestsForProject>>
>;
export type GetChangeRequestsForProjectQueryError = ErrorType<unknown>;

export const useGetChangeRequestsForProject = <TError = ErrorType<unknown>>(
    projectId: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getChangeRequestsForProject>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!projectId;
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled ? getGetChangeRequestsForProjectKey(projectId) : null);
    const swrFn = () => getChangeRequestsForProject(projectId);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will retrieve all pending change requests (change requests with a status of Draft | In review | Approved) referencing the given feature toggle name.
 * @summary Retrieves all pending change requests referencing a feature in the project
 */
export const getPendingChangeRequestsForFeature = (
    projectId: string,
    featureName: string
) => {
    return fetcher<ChangeRequestsSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/pending/${featureName}`,
        method: 'get',
    });
};

export const getGetPendingChangeRequestsForFeatureKey = (
    projectId: string,
    featureName: string
) => [
    `/api/admin/projects/${projectId}/change-requests/pending/${featureName}`,
];

export type GetPendingChangeRequestsForFeatureQueryResult = NonNullable<
    Awaited<ReturnType<typeof getPendingChangeRequestsForFeature>>
>;
export type GetPendingChangeRequestsForFeatureQueryError = ErrorType<unknown>;

export const useGetPendingChangeRequestsForFeature = <
    TError = ErrorType<unknown>
>(
    projectId: string,
    featureName: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getPendingChangeRequestsForFeature>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled =
        swrOptions?.enabled !== false && !!(projectId && featureName);
    const swrKey =
        swrOptions?.swrKey ??
        (() =>
            isEnabled
                ? getGetPendingChangeRequestsForFeatureKey(
                      projectId,
                      featureName
                  )
                : null);
    const swrFn = () =>
        getPendingChangeRequestsForFeature(projectId, featureName);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will retrieve one change request if it matches the provided id.
 * @summary Retrieves one change request by id
 */
export const getChangeRequest = (projectId: string, id: string) => {
    return fetcher<ChangeRequestSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/${id}`,
        method: 'get',
    });
};

export const getGetChangeRequestKey = (projectId: string, id: string) => [
    `/api/admin/projects/${projectId}/change-requests/${id}`,
];

export type GetChangeRequestQueryResult = NonNullable<
    Awaited<ReturnType<typeof getChangeRequest>>
>;
export type GetChangeRequestQueryError = ErrorType<void>;

export const useGetChangeRequest = <TError = ErrorType<void>>(
    projectId: string,
    id: string,
    options?: {
        swr?: SWRConfiguration<
            Awaited<ReturnType<typeof getChangeRequest>>,
            TError
        > & { swrKey?: Key; enabled?: boolean };
    }
) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false && !!(projectId && id);
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetChangeRequestKey(projectId, id) : null));
    const swrFn = () => getChangeRequest(projectId, id);

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * This endpoint will delete one change request if it matches the provided id.
 * @summary Deletes a change request by id
 */
export const deleteChangeRequest = (projectId: string, id: string) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/change-requests/${id}`,
        method: 'delete',
    });
};

/**
 * This endpoint will discard one change from a change request if it matches the provided id.
 * @summary Discards a change from a change request by change id
 */
export const deleteChange = (
    projectId: string,
    changeRequestId: string,
    eventId: string
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/change-requests/${changeRequestId}/changes/${eventId}`,
        method: 'delete',
    });
};

/**
 * This endpoint will update the state of a change request if the business rules allow it. The state can be one of the following: Draft, In review, Approved, Cancelled, Applied. In order to be approved, the change request must have at least one change and the number of approvals must be greater than or equal to the number of approvals required for the environment.

                    Once a change request has been approved, it can be applied. Once a change request has been applied, it cannot be changed. Once a change request has been cancelled, it cannot be changed. Any change to a change request in the state of Approved will result in the state being set to In Review and the number of approvals will be reset.
 * @summary This endpoint will update the state of a change request
 */
export const updateChangeRequestState = (projectId: string, id: string) => {
    return fetcher<ChangeRequestStateSchema>({
        url: `/api/admin/projects/${projectId}/change-requests/${id}/state`,
        method: 'put',
    });
};

/**
 * This endpoint will add a comment to a change request for the user making the request.
 * @summary This endpoint will add a comment to a change request
 */
export const addChangeRequestComment = (
    projectId: string,
    id: string,
    changeRequestAddCommentSchema: BodyType<ChangeRequestAddCommentSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/projects/${projectId}/change-requests/${id}/comments`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: changeRequestAddCommentSchema,
    });
};

export const exportFeatures = (
    exportQuerySchema: BodyType<ExportQuerySchema>
) => {
    return fetcher<ExportResultSchema>({
        url: `/api/admin/features-batch/export`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: exportQuerySchema,
    });
};

/**
 * Unleash toggles exported from a different instance can be imported into a new project and environment
 * @summary Validate import of feature toggles for an environment in the project
 */
export const validateImport = (
    importTogglesSchema: BodyType<ImportTogglesSchema>
) => {
    return fetcher<ImportTogglesValidateSchema>({
        url: `/api/admin/features-batch/validate`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: importTogglesSchema,
    });
};

/**
 * Unleash toggles exported from a different instance can be imported into a new project and environment
 * @summary Import feature toggles for an environment in the project
 */
export const importToggles = (
    importTogglesSchema: BodyType<ImportTogglesSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/features-batch/import`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: importTogglesSchema,
    });
};

/**
 * A user may get relevant notifications from the projects they are a member of
 * @summary Retrieves a list of notifications
 */
export const getNotifications = () => {
    return fetcher<NotificationsSchema>({
        url: `/api/admin/notifications`,
        method: 'get',
    });
};

export const getGetNotificationsKey = () => [`/api/admin/notifications`];

export type GetNotificationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getNotifications>>
>;
export type GetNotificationsQueryError = ErrorType<unknown>;

export const useGetNotifications = <TError = ErrorType<unknown>>(options?: {
    swr?: SWRConfiguration<
        Awaited<ReturnType<typeof getNotifications>>,
        TError
    > & { swrKey?: Key; enabled?: boolean };
}) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetNotificationsKey() : null));
    const swrFn = () => getNotifications();

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Allow to select which notifications were read and saving a read date
 * @summary Mark notifications as read
 */
export const markNotificationsAsRead = (
    markNotificationsAsReadSchema: BodyType<MarkNotificationsAsReadSchema>
) => {
    return fetcher<void>({
        url: `/api/admin/notifications/read`,
        method: 'post',
        headers: { 'Content-Type': 'application/json' },
        data: markNotificationsAsReadSchema,
    });
};

/**
 * Returns **all** login events in the Unleash system. You can optionally get them in CSV format by specifying the `Accept` header as `text/csv`.
 * @summary Get all login events.
 */
export const getLoginHistory = () => {
    return fetcher<LoginHistorySchema | string | void>({
        url: `/api/admin/logins`,
        method: 'get',
    });
};

export const getGetLoginHistoryKey = () => [`/api/admin/logins`];

export type GetLoginHistoryQueryResult = NonNullable<
    Awaited<ReturnType<typeof getLoginHistory>>
>;
export type GetLoginHistoryQueryError = ErrorType<unknown>;

export const useGetLoginHistory = <TError = ErrorType<unknown>>(options?: {
    swr?: SWRConfiguration<
        Awaited<ReturnType<typeof getLoginHistory>>,
        TError
    > & { swrKey?: Key; enabled?: boolean };
}) => {
    const { swr: swrOptions } = options ?? {};

    const isEnabled = swrOptions?.enabled !== false;
    const swrKey =
        swrOptions?.swrKey ??
        (() => (isEnabled ? getGetLoginHistoryKey() : null));
    const swrFn = () => getLoginHistory();

    const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
        swrKey,
        swrFn,
        swrOptions
    );

    return {
        swrKey,
        ...query,
    };
};

/**
 * Clears the login log, deleting **all** login events.
 * @summary Clear the login log.
 */
export const deleteLoginHistory = () => {
    return fetcher<void>({ url: `/api/admin/logins`, method: 'delete' });
};

/**
 * Deletes the specified login event.
 * @summary Delete a login event.
 */
export const deleteLoginEvent = (id: string) => {
    return fetcher<void>({ url: `/api/admin/logins/${id}`, method: 'delete' });
};
