# OGCIO

variables:
  awsServiceConnection: building-blocks-shared-ecr
  awsRegion: eu-west-1
  ecrEndpoint: 428528001781.dkr.ecr.eu-west-1.amazonaws.com
  buildArguments: ""
  environment: LifeEvents-dev
  