'use strict';

module.exports = {
    APPLICATION_CREATED: 'application-created',
    FEATURE_CREATED: 'feature-created',
    FEATURE_UPDATED: 'feature-updated',
    FEATURE_ARCHIVED: 'feature-archived',
    FEATURE_REVIVED: 'feature-revived',
    FEATURE_IMPORT: 'feature-import',
    FEATURE_TAGGED: 'feature-tagged',
    FEATURE_UNTAGGED: 'feature-untagged',
    DROP_FEATURES: 'drop-features',
    STRATEGY_CREATED: 'strategy-created',
    STRATEGY_DELETED: 'strategy-deleted',
    STRATEGY_DEPRECATED: 'strategy-deprecated',
    STRATEGY_REACTIVATED: 'strategy-reactivated',
    STRATEGY_UPDATED: 'strategy-updated',
    STRATEGY_IMPORT: 'strategy-import',
    DROP_STRATEGIES: 'drop-strategies',
    CONTEXT_FIELD_CREATED: 'context-field-created',
    CONTEXT_FIELD_UPDATED: 'context-field-updated',
    CONTEXT_FIELD_DELETED: 'context-field-deleted',
    PROJECT_CREATED: 'project-created',
    PROJECT_UPDATED: 'project-updated',
    PROJECT_DELETED: 'project-deleted',
    TAG_CREATED: 'tag-created',
    TAG_DELETED: 'tag-deleted',
    TAG_TYPE_CREATED: 'tag-type-created',
    TAG_TYPE_DELETED: 'tag-type-deleted',
    TAG_TYPE_UPDATED: 'tag-type-updated',
    ADDON_CONFIG_CREATED: 'addon-config-created',
    ADDON_CONFIG_UPDATED: 'addon-config-updated',
    ADDON_CONFIG_DELETED: 'addon-config-deleted',
    DB_POOL_UPDATE: 'db-pool-update',
};
