'use strict';

const ADMIN = 'ADMIN';
const CLIENT = 'CLIENT';
const CREATE_FEATURE = 'CREATE_FEATURE';
const UPDATE_FEATURE = 'UPDATE_FEATURE';
const DELETE_FEATURE = 'DELETE_FEATURE';
const CREATE_STRATEGY = 'CREATE_STRATEGY';
const UPDATE_STRATEGY = 'UPDATE_STRATEGY';
const DELETE_STRATEGY = 'DELETE_STRATEGY';
const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
const CREATE_CONTEXT_FIELD = 'CREATE_CONTEXT_FIELD';
const UPDATE_CONTEXT_FIELD = 'UPDATE_CONTEXT_FIELD';
const DELETE_CONTEXT_FIELD = 'DELETE_CONTEXT_FIELD';
const CREATE_PROJECT = 'CREATE_PROJECT';
const UPDATE_PROJECT = 'UPDATE_PROJECT';
const DELETE_PROJECT = 'DELETE_PROJECT';

module.exports = {
    ADMIN,
    CLIENT,
    CREATE_FEATURE,
    UPDATE_FEATURE,
    DELETE_FEATURE,
    CREATE_STRATEGY,
    UPDATE_STRATEGY,
    DELETE_STRATEGY,
    UPDATE_APPLICATION,
    CREATE_CONTEXT_FIELD,
    UPDATE_CONTEXT_FIELD,
    DELETE_CONTEXT_FIELD,
    CREATE_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
};
