import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
    apisidebar: [
        {
            type: 'doc',
            id: 'api/unleash-api',
        },
        {
            type: 'category',
            label: 'Addons',
            link: {
                type: 'doc',
                id: 'api/addons',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-addons',
                    label: 'Get all addons and providers',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-addon',
                    label: 'Create a new addon',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-addon',
                    label: 'Get a specific addon',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-addon',
                    label: 'Update an addon',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-addon',
                    label: 'Delete an addon',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-integration-events',
                    label: 'Get integration events for a specific integration configuration.',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Admin UI',
            link: {
                type: 'doc',
                id: 'api/admin-ui',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/create-feedback',
                    label: 'Send Unleash feedback',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-lifecycle-trends',
                    label: 'Get lifecycle trends',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-ui-config',
                    label: 'Get UI configuration',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-cors',
                    label: 'Sets allowed CORS origins',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-feedback',
                    label: 'Update Unleash feedback',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/update-splash-settings',
                    label: 'Update splash settings',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/ui-observability',
                    label: 'Accepts errors from the UI client',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'API tokens',
            link: {
                type: 'doc',
                id: 'api/api-tokens',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-all-api-tokens',
                    label: 'Get API tokens',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-api-token',
                    label: 'Create API token',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-api-tokens-by-name',
                    label: 'Get API tokens by name',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-api-token',
                    label: 'Update API token',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-api-token',
                    label: 'Delete API token',
                    className: 'api-method delete',
                },
            ],
        },
        {
            type: 'category',
            label: 'Archive',
            link: {
                type: 'doc',
                id: 'api/archive',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/delete-feature',
                    label: 'Archives a feature',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/revive-feature',
                    label: 'Revives a feature',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-features',
                    label: 'Deletes a list of features',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/revive-features',
                    label: 'Revives a list of features',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Auth',
            link: {
                type: 'doc',
                id: 'api/auth',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/login',
                    label: 'Log in',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-saml-settings',
                    label: 'Get SAML auth settings',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-saml-settings',
                    label: 'Update SAML auth settings',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-oidc-settings',
                    label: 'Get OIDC auth settings',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-oidc-settings',
                    label: 'Set OIDC settings',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-simple-settings',
                    label: 'Get Simple auth settings',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-simple-settings',
                    label: 'Update Simple auth settings',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-service-account-permissions',
                    label: 'Returns the list of permissions for the service account.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-access-overview',
                    label: 'Gets access overview',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-permissions',
                    label: 'Gets available permissions',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/validate-token',
                    label: 'Validates a token',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/change-password',
                    label: 'Changes a user password',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-password',
                    label: 'Validates password',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/send-reset-password-email',
                    label: 'Reset password',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Banners',
            link: {
                type: 'doc',
                id: 'api/banners',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-banners',
                    label: 'Get all banners.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-banner',
                    label: 'Create a banner.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-banner',
                    label: 'Update a banner.',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-banner',
                    label: 'Delete a banner.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/enable-banner',
                    label: 'Enables a banner.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/disable-banner',
                    label: 'Disables a banner.',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Change Requests',
            link: {
                type: 'doc',
                id: 'api/change-requests',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-project-change-request-config',
                    label: 'Retrieves change request configuration for a project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-project-change-request-config',
                    label: 'Updates change request configuration for an environment in the project',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/get-scheduled-change-requests',
                    label: 'Get scheduled change requests matching a query.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/change-request',
                    label: 'Create/Add change to a change request',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-change-requests-count',
                    label: 'Retrieves number of project change requests in each state',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-open-change-requests-for-user',
                    label: 'Retrieves pending change requests in configured environments',
                    className: 'menu__list-item--deprecated api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-pending-change-requests-for-user',
                    label: 'Retrieves pending change requests in configured environments',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-change-requests-for-project',
                    label: 'Retrieves all change requests for a project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-pending-change-requests-for-feature',
                    label: 'Retrieves all pending change requests referencing a feature in the project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-change-request',
                    label: 'Retrieves one change request by id',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/delete-change-request',
                    label: 'Deletes a change request by id',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/delete-change',
                    label: 'Discards a change from a change request by change id',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/edit-change',
                    label: 'Edits a single change in a change request',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/update-change-request-state',
                    label: 'This endpoint will update the state of a change request',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/update-change-request-title',
                    label: 'This endpoint will update the custom title of a change request',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/add-change-request-reviewers',
                    label: 'This endpoint will update the reviewers of a change request',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/get-change-request-approvers',
                    label: 'This endpoint fetches the requested approvers of a change request',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/add-change-request-comment',
                    label: 'This endpoint will add a comment to a change request',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-available-change-request-reviewers',
                    label: 'This endpoint will return users available to review/approve this change request',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Client',
            link: {
                type: 'doc',
                id: 'api/client',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-client-feature',
                    label: 'Get a single feature flag',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-all-client-features',
                    label: 'Get all flags (SDK)',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/register-client-metrics',
                    label: 'Register client usage metrics',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/client-custom-metrics',
                    label: 'Send custom metrics',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/register-client-application',
                    label: 'Register a client SDK',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Context',
            link: {
                type: 'doc',
                id: 'api/context',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-context-fields',
                    label: 'Gets configured context fields',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-context-field',
                    label: 'Create a context field',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-context-field',
                    label: 'Gets context field',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-context-field',
                    label: 'Update an existing context field',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-context-field',
                    label: 'Delete an existing context field',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/update-context-field-legal-value',
                    label: 'Add or update legal value for the context field',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-context-field-legal-value',
                    label: 'Delete legal value for the context field',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/validate',
                    label: 'Validate a context field',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Dependencies',
            link: {
                type: 'doc',
                id: 'api/dependencies',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/add-feature-dependency',
                    label: 'Add a feature dependency.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-feature-dependencies',
                    label: 'Deletes feature dependencies.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/delete-feature-dependency',
                    label: 'Deletes a feature dependency.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/list-parent-options',
                    label: 'List parent options.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/list-parent-variant-options',
                    label: 'List parent feature variants.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/check-dependencies-exist',
                    label: 'Check dependencies exist.',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Environments',
            link: {
                type: 'doc',
                id: 'api/environments',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/create-environment',
                    label: 'Creates a new environment',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-all-environments',
                    label: 'Get all environments',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/validate-environment-name',
                    label: 'Validates if an environment name exists',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-environment',
                    label: 'Updates an environment by name',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remove-environment',
                    label: 'Deletes an environment by name',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-environment',
                    label: 'Get the environment with `name`',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/clone-environment',
                    label: 'Clones an environment',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-environments',
                    label: 'Get the environments available to a project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-sort-order',
                    label: 'Update environment sort orders',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/toggle-environment-on',
                    label: 'Toggle the environment with `name` on',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/toggle-environment-off',
                    label: 'Toggle the environment with `name` off',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Events',
            link: {
                type: 'doc',
                id: 'api/events',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-events',
                    label: 'Get the most recent events from the Unleash instance or all events related to a project.',
                    className: 'menu__list-item--deprecated api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-events-for-toggle',
                    label: 'Get all events related to a specific feature flag.',
                    className: 'menu__list-item--deprecated api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-event-creators',
                    label: 'Get a list of all users that have created events',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/search-events',
                    label: 'Search for events',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Feature Types',
            link: {
                type: 'doc',
                id: 'api/feature-types',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-all-feature-types',
                    label: 'Get all feature types',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-feature-type-lifetime',
                    label: 'Update feature type lifetime',
                    className: 'api-method put',
                },
            ],
        },
        {
            type: 'category',
            label: 'Features',
            link: {
                type: 'doc',
                id: 'api/features',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/change-project',
                    label: 'Move feature to project',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-feature',
                    label: 'Validate a feature flag name.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/list-tags',
                    label: 'Get all tags for a feature.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/add-tag',
                    label: 'Adds a tag to a feature.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-tags',
                    label: 'Updates multiple tags for a feature.',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remove-tag',
                    label: 'Removes a tag from a feature.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-environment',
                    label: 'Get a feature environment',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/toggle-feature-environment-off',
                    label: 'Disable a feature flag',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/toggle-feature-environment-on',
                    label: 'Enable a feature flag',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/bulk-toggle-features-environment-on',
                    label: 'Bulk enable a list of features',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/bulk-toggle-features-environment-off',
                    label: 'Bulk disable a list of features',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-strategies',
                    label: 'Get feature flag strategies',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/add-feature-strategy',
                    label: 'Add a strategy to a feature flag',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-strategy',
                    label: 'Get a strategy configuration',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-feature-strategy',
                    label: 'Update a strategy',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/patch-feature-strategy',
                    label: 'Change specific properties of a strategy',
                    className: 'api-method patch',
                },
                {
                    type: 'doc',
                    id: 'api/delete-feature-strategy',
                    label: 'Delete a strategy from a feature flag',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/set-strategy-sort-order',
                    label: 'Set strategy sort order',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-features',
                    label: 'Get all features in a project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-feature',
                    label: 'Add a new feature flag',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/clone-feature',
                    label: 'Clone a feature flag',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature',
                    label: 'Get a feature',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-feature',
                    label: 'Update a feature flag',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/patch-feature',
                    label: 'Modify a feature flag',
                    className: 'api-method patch',
                },
                {
                    type: 'doc',
                    id: 'api/archive-feature',
                    label: 'Archive a feature flag',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/stale-features',
                    label: 'Mark features as stale / not stale',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-environment-feature-variants',
                    label: 'Get variants for a feature in an environment',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/patch-environments-feature-variants',
                    label: "Patch a feature's variants in an environment",
                    className: 'api-method patch',
                },
                {
                    type: 'doc',
                    id: 'api/overwrite-environment-feature-variants',
                    label: 'Create (overwrite) variants for a feature in an environment',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/overwrite-feature-variants-on-environments',
                    label: 'Create (overwrite) variants for a feature flag in multiple environments',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/validate-archive-features',
                    label: 'Validates archive features',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/archive-features',
                    label: 'Archives a list of features',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-constraint',
                    label: 'Validate constraint',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/add-favorite-feature',
                    label: 'Add feature to favorites',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/remove-favorite-feature',
                    label: 'Remove feature from favorites',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/add-favorite-project',
                    label: 'Add project to favorites',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/remove-favorite-project',
                    label: 'Remove project from favorites',
                    className: 'api-method delete',
                },
            ],
        },
        {
            type: 'category',
            label: 'Frontend API',
            link: {
                type: 'doc',
                id: 'api/frontend-api',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-frontend-features',
                    label: 'Retrieve enabled feature flags for the provided context.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-frontend-api-features-with-post',
                    label: 'Retrieve enabled feature flags for the provided context, using POST.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/register-frontend-metrics',
                    label: 'Register client usage metrics',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/register-frontend-client',
                    label: 'Register a client SDK',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Import/Export',
            link: {
                type: 'doc',
                id: 'api/import-export',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/export-features',
                    label: 'Export feature flags from an environment',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-import',
                    label: 'Validate feature import data',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/import-toggles',
                    label: 'Import feature flags',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Instance Admin',
            link: {
                type: 'doc',
                id: 'api/instance-admin',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-login-history',
                    label: 'Get all login events.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/check-license',
                    label: 'Validates the Unleash license.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/read-license',
                    label: 'Reads the Unleash license.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-license',
                    label: 'Set a new Unleash license.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-instance-admin-stats-csv',
                    label: 'Instance usage statistics',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-instance-admin-stats',
                    label: 'Instance usage statistics',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Maintenance',
            link: {
                type: 'doc',
                id: 'api/maintenance',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/toggle-maintenance',
                    label: 'Enabled/disabled maintenance mode',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-maintenance',
                    label: 'Get maintenance mode status',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Metrics',
            link: {
                type: 'doc',
                id: 'api/metrics',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-requests-per-second',
                    label: 'Gets usage data',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-traffic-data-usage-for-period',
                    label: 'Get aggregated traffic data for a given time period.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-application',
                    label: 'Create an application to connect reported metrics',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-application',
                    label: 'Delete an application',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-application',
                    label: 'Get application data',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-applications',
                    label: 'Get all applications',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-application-overview',
                    label: 'Get application overview',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-application-environment-instances',
                    label: 'Get application environment instances (Last 24h)',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-outdated-sdks',
                    label: 'Get outdated SDKs',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-raw-feature-metrics',
                    label: 'Get feature metrics',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-usage-summary',
                    label: 'Last hour of usage and a list of applications that have reported seeing this feature flag',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-custom-metrics',
                    label: 'Get stored custom metrics',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-prometheus-metrics',
                    label: 'Get metrics in Prometheus format',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Notifications',
            link: {
                type: 'doc',
                id: 'api/notifications',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-notifications',
                    label: 'Retrieves a list of notifications',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/mark-notifications-as-read',
                    label: 'Mark notifications as read',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Operational',
            link: {
                type: 'doc',
                id: 'api/operational',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-invoices',
                    label: 'getInvoices',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-health',
                    label: 'Get instance operational status',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Personal access tokens',
            link: {
                type: 'doc',
                id: 'api/personal-access-tokens',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-pats',
                    label: 'Get all personal access tokens (PATs) for the current user.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-pat',
                    label: 'Create a new personal access token (PAT) for the current user.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-pat',
                    label: 'Delete a personal access token (PAT) for the current user.',
                    className: 'api-method delete',
                },
            ],
        },
        {
            type: 'category',
            label: 'Playground',
            link: {
                type: 'doc',
                id: 'api/playground',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-change-request-playground',
                    label: 'Evaluate an Unleash context against a change request preview.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-playground',
                    label: 'Evaluate an Unleash context against a set of environments and projects.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-advanced-playground',
                    label: 'Batch evaluate an Unleash context against a set of environments and projects.',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Projects',
            link: {
                type: 'doc',
                id: 'api/projects',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-projects',
                    label: 'Get a list of all projects.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-project',
                    label: 'Create project',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-project',
                    label: 'Validate project ID',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-project',
                    label: 'Update project',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-project',
                    label: 'Delete project',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/update-project-enterprise-settings',
                    label: 'Update project enterprise settings',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-access',
                    label: 'Get users and groups in project',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-project-access',
                    label: 'Set users and groups to roles in the current project',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/add-access-to-project',
                    label: 'Configure project access',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-role-project-access',
                    label: 'Get project-role mappings',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-roles-for-user',
                    label: 'Sets roles for user',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remove-user-access',
                    label: 'Remove project access for a user',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/set-roles-for-group',
                    label: 'Sets roles for group',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remove-group-access',
                    label: 'Remove project access for a group',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-overview',
                    label: 'Get an overview of a project.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-dora',
                    label: 'Get an overview project dora metrics.',
                    className: 'menu__list-item--deprecated api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-applications',
                    label: 'Get a list of all applications for a project.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-flag-creators',
                    label: 'Get a list of all flag creators for a project.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-outdated-project-sdks',
                    label: 'Get outdated project SDKs',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/add-environment-to-project',
                    label: 'Add an environment to a project.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/remove-environment-from-project',
                    label: 'Remove an environment from a project.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/add-default-strategy-to-project-environment',
                    label: 'Set environment-default strategy',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-health-report',
                    label: 'Get a health report for a project.',
                    className: 'menu__list-item--deprecated api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-api-tokens',
                    label: 'Get api tokens for project.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-project-api-token',
                    label: 'Create a project API token.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-project-api-token',
                    label: 'Delete a project API token.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-insights',
                    label: 'Get an overview of a project insights.',
                    className: 'menu__list-item--deprecated api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Public signup tokens',
            link: {
                type: 'doc',
                id: 'api/public-signup-tokens',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/validate-public-signup-token',
                    label: 'Validate signup token',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/add-public-signup-token-user',
                    label: 'Add a user via a signup token',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-all-public-signup-tokens',
                    label: 'Get public signup tokens',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-public-signup-token',
                    label: 'Create a public signup token',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-public-signup-token',
                    label: 'Retrieve a token',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-public-signup-token',
                    label: 'Update a public signup token',
                    className: 'api-method put',
                },
            ],
        },
        {
            type: 'category',
            label: 'Search',
            link: {
                type: 'doc',
                id: 'api/search',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/search-features',
                    label: 'Search and filter features',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Segments',
            link: {
                type: 'doc',
                id: 'api/segments',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/validate-segment',
                    label: 'Validates if a segment name exists',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-segments-by-strategy-id',
                    label: 'Get strategy segments',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-strategies-by-segment-id',
                    label: 'Get strategies that reference segment',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/remove-segment',
                    label: 'Deletes a segment by id',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/update-segment',
                    label: 'Update segment by id',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/get-segment',
                    label: 'Get a segment',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-segment',
                    label: 'Create a new segment',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-segments',
                    label: 'Get all segments',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Service Accounts',
            link: {
                type: 'doc',
                id: 'api/service-accounts',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-service-accounts',
                    label: 'List service accounts.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-service-account',
                    label: 'Create a service account.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-service-account',
                    label: 'Update a service account.',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-service-account',
                    label: 'Delete a service account.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-service-account-tokens',
                    label: 'List all tokens for a service account.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-service-account-token',
                    label: 'Create a token for a service account.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/delete-service-account-token',
                    label: 'Delete a token for a service account.',
                    className: 'api-method delete',
                },
            ],
        },
        {
            type: 'category',
            label: 'Strategies',
            link: {
                type: 'doc',
                id: 'api/strategies',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-all-strategies',
                    label: 'Get all strategies',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-strategy',
                    label: 'Create a strategy',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-strategy',
                    label: 'Get a strategy definition',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/remove-strategy',
                    label: 'Delete a strategy',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/update-strategy',
                    label: 'Update a strategy type',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/deprecate-strategy',
                    label: 'Deprecate a strategy',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/reactivate-strategy',
                    label: 'Reactivate a strategy',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-strategies-by-context-field',
                    label: 'Get strategies that use a context field',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-feature-strategy-segments',
                    label: 'Update strategy segments',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'category',
            label: 'Tags',
            link: {
                type: 'doc',
                id: 'api/tags',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-tags',
                    label: 'List all tags.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-tag',
                    label: 'Create a new tag.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-tags-by-type',
                    label: 'List all tags of a given type.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-tag',
                    label: 'Get a tag by type and value.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/delete-tag',
                    label: 'Delete a tag.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-tag-types',
                    label: 'Get all tag types',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-tag-type',
                    label: 'Create a tag type',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-tag-type',
                    label: 'Validate a tag type',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-tag-type',
                    label: 'Get a tag type',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-tag-type',
                    label: 'Update a tag type',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-tag-type',
                    label: 'Delete a tag type',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/add-tag-to-features',
                    label: 'Adds a tag to the specified features',
                    className: 'api-method put',
                },
            ],
        },
        {
            type: 'category',
            label: 'Telemetry',
            link: {
                type: 'doc',
                id: 'api/telemetry',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-telemetry-settings',
                    label: 'Get telemetry settings',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Unleash Edge',
            link: {
                type: 'doc',
                id: 'api/unleash-edge',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/register-edge-observability-metrics',
                    label: 'Register Edge observability metrics.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/client-bulk-metrics',
                    label: 'Send metrics in bulk',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-valid-tokens',
                    label: 'Check which tokens are valid',
                    className: 'api-method post',
                },
            ],
        },
        {
            type: 'doc',
            id: 'api/release-templates',
            label: 'Release templates',
        },
        {
            type: 'doc',
            id: 'api/unknown-flags',
            label: 'Unknown flags',
        },
        {
            type: 'category',
            label: 'Unstable',
            link: {
                type: 'doc',
                id: 'api/unstable',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-actionable-change-requests',
                    label: 'Get the number of change requests you can do something with',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-feedback',
                    label: 'Get all feedback events.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/provide-feedback',
                    label: 'Submit user feedback',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/create-cdn-token',
                    label: 'Create a CDN token.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-cdn-tokens',
                    label: 'Get a CDN tokens.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-scim-settings',
                    label: 'Get SCIM settings.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/set-scim-settings',
                    label: 'Set SCIM settings.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/generate-new-token',
                    label: 'Generates a new SCIM API token.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-all-release-plan-templates',
                    label: 'Get all release plan templates.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-release-plan-template',
                    label: 'Create a release template.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-release-plan-template',
                    label: 'Get a release plan template by its id.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/delete-release-plan-template',
                    label: 'Deletes a release plan template by its id.',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/update-release-plan-template',
                    label: 'Updates a release plan template by its id.',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/archive-release-plan-template',
                    label: 'Archives a release plan template by its id.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/add-milestone-to-release-plan-template',
                    label: 'Adds a milestone to a release plan.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-release-plan-template-milestone',
                    label: 'Updates existing milestone',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remove-release-plan-milestone',
                    label: 'Removes an existing milestone',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/add-strategy-to-milestone',
                    label: 'Adds a strategy to a milestone.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-milestone-strategy',
                    label: 'Updates a strategy attached to a milestone',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/remote-milestone-strategy',
                    label: 'Removes a strategy attached to a milestone',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/connect',
                    label: 'Connect to the streaming API.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-delta',
                    label: 'Get partial updates (SDK)',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/disconnect-all',
                    label: 'Disconnect all clients.',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/archive-project',
                    label: 'Archive project',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/revive-project',
                    label: 'Revive project',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-connections-for-period',
                    label: 'Get aggregated metered connections for a given time period.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-requests-for-period',
                    label: 'Get aggregated metered requests for a given time period.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-instance-insights',
                    label: 'Get instance information',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/subscribe-email-subscription',
                    label: 'Subscribe to email subscription',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/unsubscribe-email-subscription',
                    label: 'Unsubscribe from email subscription',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-all-licensed-users',
                    label: 'Retrieves all licensed users data.',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-unknown-flags',
                    label: 'Get latest reported unknown flag names',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-user-permissions',
                    label: 'Returns the list of permissions for the user',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-project-status',
                    label: 'Get project status',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-lifecycle',
                    label: 'Get feature lifecycle',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/complete',
                    label: 'Set feature completed',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/uncomplete',
                    label: 'Set feature uncompleted',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/create-feature-link',
                    label: 'Create a feature link',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/update-feature-link',
                    label: 'Update a feature link',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-feature-link',
                    label: 'Delete a feature link',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-feature-lifecycle-stage-count',
                    label: 'Get all features lifecycle stage count',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-personal-dashboard',
                    label: 'Get personal dashboard',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-personal-dashboard-project-details',
                    label: 'Get personal project details',
                    className: 'api-method get',
                },
            ],
        },
        {
            type: 'category',
            label: 'Users',
            link: {
                type: 'doc',
                id: 'api/users',
            },
            items: [
                {
                    type: 'doc',
                    id: 'api/get-groups',
                    label: 'Get a list of groups',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-group',
                    label: 'Create a new group',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-group',
                    label: 'Get a single group',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-group',
                    label: 'Update a group',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-group',
                    label: 'Delete a single group',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/delete-scim-groups',
                    label: 'Delete all SCIM groups',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/get-roles',
                    label: 'Get a list of roles',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-role',
                    label: 'Create a new role',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-role-by-id',
                    label: 'Get a single role',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-role',
                    label: 'Update a role',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-role',
                    label: 'Delete a custom role',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/validate-role',
                    label: 'Validate a role',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-me',
                    label: 'Get your own user details',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-profile',
                    label: 'Get your own user profile',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/change-my-password',
                    label: 'Change your own password',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-user-roles',
                    label: 'Get roles for currently logged in user',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-inactive-users',
                    label: 'Gets inactive users',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/delete-inactive-users',
                    label: 'Deletes inactive users',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/validate-user-password',
                    label: 'Validate password for a user',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/change-user-password',
                    label: 'Change password for a user',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/reset-user-password',
                    label: 'Reset user password',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/get-users',
                    label: 'Get all users and [root roles](https://docs.getunleash.io/reference/rbac#predefined-roles)',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/create-user',
                    label: 'Create a new user',
                    className: 'api-method post',
                },
                {
                    type: 'doc',
                    id: 'api/search-users',
                    label: 'Search users',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-base-users-and-groups',
                    label: 'Get basic user and group information',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-admin-count',
                    label: 'Get total count of admin accounts',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/get-user',
                    label: 'Get user',
                    className: 'api-method get',
                },
                {
                    type: 'doc',
                    id: 'api/update-user',
                    label: 'Update a user',
                    className: 'api-method put',
                },
                {
                    type: 'doc',
                    id: 'api/delete-user',
                    label: 'Delete a user',
                    className: 'api-method delete',
                },
                {
                    type: 'doc',
                    id: 'api/delete-scim-users',
                    label: 'Delete all SCIM users',
                    className: 'api-method delete',
                },
            ],
        },
    ],
};

export default sidebar.apisidebar;
