import type { FromSchema } from 'json-schema-to-ts';
import { addonSchema } from './addon-schema.js';
import { addonTypeSchema } from './addon-type-schema.js';
import { addonParameterSchema } from './addon-parameter-schema.js';
import { tagTypeSchema } from './tag-type-schema.js';
import {
    ADDON_CONFIG_CREATED,
    ADDON_CONFIG_DELETED,
    ADDON_CONFIG_UPDATED,
    API_TOKEN_CREATED,
    API_TOKEN_DELETED,
    BANNER_CREATED,
    BANNER_DELETED,
    BANNER_UPDATED,
    CHANGE_ADDED,
    CHANGE_DISCARDED,
    CHANGE_EDITED,
    CHANGE_REQUEST_APPLIED,
    CHANGE_REQUEST_APPROVAL_ADDED,
    CHANGE_REQUEST_APPROVED,
    CHANGE_REQUEST_CANCELLED,
    CHANGE_REQUEST_CREATED,
    CHANGE_REQUEST_DISCARDED,
    CHANGE_REQUEST_REJECTED,
    CHANGE_REQUEST_SCHEDULE_SUSPENDED,
    CHANGE_REQUEST_SCHEDULED,
    CHANGE_REQUEST_SCHEDULED_APPLICATION_FAILURE,
    CHANGE_REQUEST_SCHEDULED_APPLICATION_SUCCESS,
    CHANGE_REQUEST_SENT_TO_REVIEW,
    CONTEXT_FIELD_CREATED,
    CONTEXT_FIELD_DELETED,
    CONTEXT_FIELD_UPDATED,
    FEATURE_ARCHIVED,
    FEATURE_CREATED,
    FEATURE_DELETED,
    FEATURE_ENVIRONMENT_DISABLED,
    FEATURE_ENVIRONMENT_ENABLED,
    FEATURE_ENVIRONMENT_VARIANTS_UPDATED,
    FEATURE_METADATA_UPDATED,
    FEATURE_POTENTIALLY_STALE_ON,
    FEATURE_PROJECT_CHANGE,
    FEATURE_REVIVED,
    FEATURE_STALE_OFF,
    FEATURE_STALE_ON,
    FEATURE_STRATEGY_ADD,
    FEATURE_STRATEGY_REMOVE,
    FEATURE_STRATEGY_UPDATE,
    FEATURE_TAGGED,
    FEATURE_UNTAGGED,
    GROUP_CREATED,
    GROUP_DELETED,
    GROUP_UPDATED,
    PROJECT_ARCHIVED,
    PROJECT_CREATED,
    PROJECT_DELETED,
    RELEASE_PLAN_PROGRESSIONS_PAUSED,
    RELEASE_PLAN_PROGRESSIONS_RESUMED,
    SEGMENT_CREATED,
    SEGMENT_DELETED,
    SEGMENT_UPDATED,
    SERVICE_ACCOUNT_CREATED,
    SERVICE_ACCOUNT_DELETED,
    SERVICE_ACCOUNT_UPDATED,
    USER_ACCESS_REQUEST_APPROVED,
    USER_ACCESS_REQUEST_REGISTERED,
    USER_ACCESS_REQUEST_REJECTED,
    USER_CREATED,
    USER_DELETED,
    USER_UPDATED,
} from '../../events/index.js';

export const addonsSchema = {
    $id: '#/components/schemas/addonsSchema',
    type: 'object',
    required: ['addons', 'providers'],
    description: `An object containing two things:
1. A list of all [addons](https://docs.getunleash.io/integrate) defined on this Unleash instance
2. A list of all addon providers defined on this instance`,
    properties: {
        addons: {
            type: 'array',
            description:
                'All the addons that exist on this instance of Unleash.',
            items: {
                $ref: '#/components/schemas/addonSchema',
            },
        },
        providers: {
            type: 'array',
            description:
                'A list of  all available addon providers, along with their parameters and descriptions.',
            example: [
                {
                    name: 'webhook',
                    displayName: 'Webhook',
                    description:
                        'A Webhook is a generic way to post messages from Unleash to third party services.',
                    documentationUrl:
                        'https://docs.getunleash.io/integrate/webhook',
                    parameters: [
                        {
                            name: 'url',
                            displayName: 'Webhook URL',
                            description:
                                '(Required) Unleash will perform a HTTP Post to the specified URL (one retry if first attempt fails)',
                            type: 'url',
                            required: true,
                            sensitive: true,
                        },
                        {
                            name: 'contentType',
                            displayName: 'Content-Type',
                            placeholder: 'application/json',
                            description:
                                '(Optional) The Content-Type header to use. Defaults to "application/json".',
                            type: 'text',
                            required: false,
                            sensitive: false,
                        },
                        {
                            name: 'authorization',
                            displayName: 'Authorization',
                            placeholder: '',
                            description:
                                '(Optional) The Authorization header to use. Not used if left blank.',
                            type: 'text',
                            required: false,
                            sensitive: true,
                        },
                        {
                            name: 'bodyTemplate',
                            displayName: 'Body template',
                            placeholder: `{
  "event": "{{event.type}}",
  "createdBy": "{{event.createdBy}}",
  "featureToggle": "{{event.data.name}}",
  "timestamp": "{{event.data.createdAt}}"
}`,
                            description:
                                "(Optional) You may format the body using a mustache template. If you don't specify anything, the format will be similar to the events format (https://docs.getunleash.io/concepts/events)",
                            type: 'textfield',
                            required: false,
                            sensitive: false,
                        },
                    ],
                    events: [
                        'feature-created',
                        'feature-updated',
                        'feature-archived',
                        'feature-revived',
                        'feature-stale-on',
                        'feature-stale-off',
                        'feature-environment-enabled',
                        'feature-environment-disabled',
                        'feature-strategy-remove',
                        'feature-strategy-update',
                        'feature-strategy-add',
                        'feature-metadata-updated',
                        'feature-variants-updated',
                        'feature-project-change',
                        'feature-tagged',
                        'feature-untagged',
                        'change-request-created',
                        'change-request-discarded',
                        'change-added',
                        'change-discarded',
                        'change-request-approved',
                        'change-request-approval-added',
                        'change-request-cancelled',
                        'change-request-sent-to-review',
                        'change-request-applied',
                    ],
                },
                {
                    name: 'slack-app',
                    displayName: 'Slack App',
                    description:
                        'The Unleash App for Slack posts messages to the selected channels in your Slack workspace.',
                    documentationUrl:
                        'https://docs.getunleash.io/integrate/slack-app',
                    installation: {
                        url: 'https://app-for-slack.getunleash.io/install',
                        title: 'App for Slack installation',
                        helpText:
                            'After installing the Unleash App for Slack in your Slack workspace, paste the access token into the appropriate field below in order to configure this integration.',
                    },
                    parameters: [
                        {
                            name: 'accessToken',
                            displayName: 'Access token',
                            description: '(Required)',
                            type: 'text',
                            required: true,
                            sensitive: true,
                        },
                        {
                            name: 'defaultChannels',
                            displayName: 'Channels',
                            description:
                                'A comma-separated list of channels to post the configured events to. These channels are always notified, regardless of the event type or the presence of a slack tag.',
                            type: 'text',
                            required: false,
                            sensitive: false,
                        },
                    ],
                    events: [
                        ADDON_CONFIG_CREATED,
                        ADDON_CONFIG_DELETED,
                        ADDON_CONFIG_UPDATED,
                        API_TOKEN_CREATED,
                        API_TOKEN_DELETED,
                        CHANGE_ADDED,
                        CHANGE_DISCARDED,
                        CHANGE_EDITED,
                        CHANGE_REQUEST_APPLIED,
                        CHANGE_REQUEST_APPROVAL_ADDED,
                        CHANGE_REQUEST_APPROVED,
                        CHANGE_REQUEST_CANCELLED,
                        CHANGE_REQUEST_CREATED,
                        CHANGE_REQUEST_DISCARDED,
                        CHANGE_REQUEST_REJECTED,
                        CHANGE_REQUEST_SENT_TO_REVIEW,
                        CHANGE_REQUEST_SCHEDULED,
                        CHANGE_REQUEST_SCHEDULED_APPLICATION_SUCCESS,
                        CHANGE_REQUEST_SCHEDULED_APPLICATION_FAILURE,
                        CHANGE_REQUEST_SCHEDULE_SUSPENDED,
                        RELEASE_PLAN_PROGRESSIONS_PAUSED,
                        RELEASE_PLAN_PROGRESSIONS_RESUMED,
                        CONTEXT_FIELD_CREATED,
                        CONTEXT_FIELD_DELETED,
                        CONTEXT_FIELD_UPDATED,
                        FEATURE_ARCHIVED,
                        FEATURE_CREATED,
                        FEATURE_DELETED,
                        FEATURE_ENVIRONMENT_DISABLED,
                        FEATURE_ENVIRONMENT_ENABLED,
                        FEATURE_ENVIRONMENT_VARIANTS_UPDATED,
                        FEATURE_METADATA_UPDATED,
                        FEATURE_POTENTIALLY_STALE_ON,
                        FEATURE_PROJECT_CHANGE,
                        FEATURE_REVIVED,
                        FEATURE_STALE_OFF,
                        FEATURE_STALE_ON,
                        FEATURE_STRATEGY_ADD,
                        FEATURE_STRATEGY_REMOVE,
                        FEATURE_STRATEGY_UPDATE,
                        FEATURE_TAGGED,
                        FEATURE_UNTAGGED,
                        GROUP_CREATED,
                        GROUP_DELETED,
                        GROUP_UPDATED,
                        BANNER_CREATED,
                        BANNER_UPDATED,
                        BANNER_DELETED,
                        PROJECT_CREATED,
                        PROJECT_ARCHIVED,
                        PROJECT_DELETED,
                        SEGMENT_CREATED,
                        SEGMENT_DELETED,
                        SEGMENT_UPDATED,
                        SERVICE_ACCOUNT_CREATED,
                        SERVICE_ACCOUNT_DELETED,
                        SERVICE_ACCOUNT_UPDATED,
                        USER_CREATED,
                        USER_DELETED,
                        USER_UPDATED,
                        USER_ACCESS_REQUEST_REGISTERED,
                        USER_ACCESS_REQUEST_APPROVED,
                        USER_ACCESS_REQUEST_REJECTED,
                    ],
                    tagTypes: [
                        {
                            name: 'slack',
                            description:
                                'Slack tag used by the slack-addon to specify the slack channel.',
                            icon: 'S',
                        },
                    ],
                },
                {
                    name: 'teams',
                    displayName: 'Microsoft Teams',
                    description:
                        'Allows Unleash to post updates to Microsoft Teams.',
                    documentationUrl:
                        'https://docs.getunleash.io/integrate/teams',
                    parameters: [
                        {
                            name: 'url',
                            displayName: 'Microsoft Teams webhook URL',
                            description: '(Required)',
                            type: 'url',
                            required: true,
                            sensitive: true,
                        },
                    ],
                    events: [
                        'feature-created',
                        'feature-updated',
                        'feature-archived',
                        'feature-revived',
                        'feature-stale-on',
                        'feature-stale-off',
                        'feature-environment-enabled',
                        'feature-environment-disabled',
                        'feature-strategy-remove',
                        'feature-strategy-update',
                        'feature-strategy-add',
                        'feature-metadata-updated',
                        'feature-variants-updated',
                        'feature-project-change',
                    ],
                },
                {
                    name: 'datadog',
                    displayName: 'Datadog',
                    description: 'Allows Unleash to post updates to Datadog.',
                    documentationUrl:
                        'https://docs.getunleash.io/integrate/datadog',
                    parameters: [
                        {
                            name: 'url',
                            displayName: 'Datadog Events URL',
                            description:
                                "Default URL: https://api.datadoghq.com/api/v1/events. Needs to be changed if your're not using the US1 site.",
                            type: 'url',
                            required: false,
                            sensitive: false,
                        },
                        {
                            name: 'apiKey',
                            displayName: 'Datadog API key',
                            placeholder: 'j96c23b0f12a6b3434a8d710110bd862',
                            description:
                                '(Required) API key to connect to Datadog',
                            type: 'text',
                            required: true,
                            sensitive: true,
                        },
                    ],
                    events: [
                        'feature-created',
                        'feature-updated',
                        'feature-archived',
                        'feature-revived',
                        'feature-stale-on',
                        'feature-stale-off',
                        'feature-environment-enabled',
                        'feature-environment-disabled',
                        'feature-strategy-remove',
                        'feature-strategy-update',
                        'feature-strategy-add',
                        'feature-metadata-updated',
                        'feature-project-change',
                        'feature-variants-updated',
                    ],
                    tagTypes: [
                        {
                            name: 'datadog',
                            description:
                                'All Datadog tags added to a specific feature are sent to datadog event stream.',
                            icon: 'D',
                        },
                    ],
                },
            ],
            items: {
                $ref: '#/components/schemas/addonTypeSchema',
            },
        },
    },
    components: {
        schemas: {
            addonSchema,
            addonTypeSchema,
            tagTypeSchema,
            addonParameterSchema,
        },
    },
} as const;

export type AddonsSchema = FromSchema<typeof addonsSchema>;
