module.exports = {
    Card: 'react-mdl-Card',
    CardActions: 'react-mdl-CardActions',
    CardTitle: 'react-mdl-CardTitle',
    CardText: 'react-mdl-CardText',
    CardMenu: 'react-mdl-CardMenu',
    DataTable: 'react-mdl-DataTable',
    Cell: 'react-mdl-Cell',
    Chip: 'react-mdl-Chip',
    Grid: 'react-mdl-Grid',
    Icon: 'react-mdl-Icon',
    IconButton: 'react-mdl-IconButton',
    List: 'react-mdl-List',
    ListItem: 'react-mdl-ListItem',
    ListItemContent: 'react-mdl-ListItemContent',
    ListItemAction: 'react-mdl-ListItemAction',
    Menu: 'react-mdl-Menu',
    MenuItem: 'react-mdl-MenuItem',
    ProgressBar: 'react-mdl-ProgressBar',
    Switch: 'react-mdl-Switch',
    Tab: 'react-mdl-Tab',
    Tabs: 'react-mdl-Tabs',
    TableHeader: 'react-mdl-TableHeader',
    Textfield: 'react-mdl-Textfield',
    FooterSection: 'react-mdl-FooterSection',
    FooterLinkList: 'react-mdl-FooterLinkList',
};
