import type { ProjectSchema } from 'openapi';

export const loadingData: ProjectSchema[] = [
    {
        id: 'loading1',
        name: 'loading1',
        memberCount: 1,
        health: 95,
        featureCount: 4,
        createdAt: '',
        description: '',
        mode: 'open' as const,
        owners: [{ ownerType: 'user', name: 'Loading data' }],
    },
    {
        id: 'loading2',
        name: 'loading2',
        memberCount: 1,
        health: 95,
        featureCount: 4,
        createdAt: '',
        description: '',
        mode: 'open' as const,
        owners: [{ ownerType: 'user', name: 'Loading data' }],
    },
    {
        id: 'loading3',
        name: 'loading3',
        memberCount: 1,
        health: 95,
        featureCount: 4,
        createdAt: '',
        description: '',
        mode: 'open' as const,
        owners: [{ ownerType: 'user', name: 'Loading data' }],
    },
    {
        id: 'loading4',
        name: 'loading4',
        memberCount: 1,
        health: 95,
        featureCount: 4,
        createdAt: '',
        description: '',
        mode: 'open' as const,
        owners: [{ ownerType: 'user', name: 'Loading data' }],
    },
];
