name: TestReport
on:
  pull_request:

jobs:
  testreport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: yarn install --frozen-lockfile --ignore-scripts
      - run: yarn build:backend
      - run: yarn test:report
      - name: Upload test report to build # Done this way since external PRs would not be able to write the check. See https://github.com/marketplace/actions/test-reporter#recommended-setup-for-public-repositories
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: jest-junit.xml
