name: PR -> Frontend Build & Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/**frontend**

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm run lint:material:icons
      - run: pnpm run lint:check
      - run: pnpm run test
      - run: pnpm run ts:check # TODO: optimize
