name: e2e:frontend
on:
  pull_request:
    # paths:
    #   - 'frontend/**'
# If two events are triggered within a short time in the same PR, cancel the run of the oldest event
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  e2ebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}
      - name: Install frontend dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --immutable
        working-directory: frontend
      - name: Build static frontend
        run: yarn build
        working-directory: frontend
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
          retention-days: 1

  e2e:
    needs: e2ebuild
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test:
          - enterprise/feature.spec.ts
          - enterprise/groups.spec.ts
          - enterprise/projects/access.spec.ts
          - oss/segments/segments.spec.ts
          - oss/feature/feature.spec.ts
          # - oss/login/login.spec.ts
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Download frontend build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/build
      - name: Restore node modules
        uses: actions/cache/restore@v4
        with:
          path: frontend/node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}
      - name: Start Unleash test instance
        run: |
          docker compose -f .github/docker-compose.test.yml up -d --wait -t 90
        env:
          FRONTEND_TEST_LICENSE: ${{ secrets.FRONTEND_TEST_LICENSE }}
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          env: AUTH_USER=admin,AUTH_PASSWORD=unleash4all
          config: baseUrl=http://localhost:3000
          spec: cypress/${{ matrix.test }}
          install: false
      - name: Set artifact name
        if: always()
        id: artifact-name
        run: echo "name=cypress-screenshots-$(echo '${{ matrix.test }}' | tr '/' '-')" >> $GITHUB_OUTPUT
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ steps.artifact-name.outputs.name }}
          path: frontend/cypress/screenshots
          if-no-files-found: ignore
