name: Notify enterprise of new OSS version

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.UNLEASH_CI_BUILDER_GITHUB_TOKEN }}
          result-encoding: string
          script: |
            echo "${{ github.repository }}"
