name: Notify enterprise of new OSS version

#on:
#  push:
#    branches:
#      - main
on:
  pull_request:

jobs:
  react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          result-encoding: string
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ivarconr',
              repo: 'unleash-enterprise',
              workflow_id: 'continuous_version_sync.yaml',
              ref: 'master'
              inputs: {
                repository: "${{ github.repository }}",
                commit: "${{ github.event.head_commit.id }}",
                actor: "${{ github.event.head_commit.committer.username }}",
                message: ${{ toJSON(github.event.head_commit.message) }},
              }
            })
