name: Notify enterprise of new OSS version

#on:
#  push:
#    branches:
#      - main

on:
  pull_request:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.UNLEASH_CI_BUILDER_GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: 'ivarconr',
              repo: 'unleash-enterprise',
              workflow_id: 'continuous_version_sync.yaml',
              ref: 'master'
            })
