name: 'Attach Test report'
on:
  workflow_run:
    workflows: [TestReport]
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results # artifact name
          name: Unit Tests # Name of the check run which will be created
          path: '*.xml' # Path to test results (inside artifact .zip)
          reporter: jest-junit
