name: Test CI versioning

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAIN_BRANCH: main

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Get the commit hash
        id: get_commit_hash
        run: |
          COMMIT_HASH=${{ github.event.pull_request.head.sha }}
          echo "Commit hash: $COMMIT_HASH"
          echo "::set-output name=COMMIT_HASH::$COMMIT_HASH"
