name: Trigger Unleash CI builder

on:
  workflow_run:
    workflows: ["Build & Tests"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Trigger CI build
        if: github.event.commits
        env:
          UNLEASH_CI_BUILDER_GITHUB_TOKEN: ${{ secrets.UNLEASH_CI_BUILDER_GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${UNLEASH_CI_BUILDER_GITHUB_TOKEN}" \
            https://api.github.com/repos/bricks-software/unleash-ci-builder/dispatches \
            -d '{"event_type":"trigger-unleash-cloud-build","client_payload":{"commits":${{toJSON(github.event.commits)}}}}'
